### ISSUE TITLE
Feature request: i18n / localization

### ISSUE THREAD

**Issue by Reggino** [justinrainbow/json-schema#108]
Thanks for this great library.

It would be awesome if error messages could be localized.

**Comment by Lube** [comment]
+1

**Comment by bighappyface** [comment]
Is the idea that translated error messages would be helpful to developers using this package or for end users of an application using this package?

**Comment by Lube** [comment]
The latter of course. The idea is we should have some way to translate the messages for end users without having to fork the project or parse the errors ourselves.

**Comment by bighappyface** [comment]
Error messages provide the property, failing constraint, and constraint details in a consumable format independent of any given language/locale.

For an end-user application I am curious how the user would find value in schema validation error messages over specialized messages focused on the user experience. Printing what in some cases are cryptic messages wouldn't be very helpful to an end user unless the application was a json schema validator like jsonschema.net, but that is my opinion.

If we introduced translated/localized messages, who provides those translations, and what languages/locales would be appropriate? If the language you need is not available, a PR would still be unavoidable, and no PR would be accepted unless all strings were translated.

I believe there are bigger fish to fry for this package, and that there are adequate facilities present in the package to provide package consumers with the ability to integrate validation error into their localized end-user application. That being said, PRs are always welcome.

**Comment by jojo1981** [comment]
I agree with @bighappyface that translated/localized messages doesn't belong into the schema. A solution for the problem can be to attach unique error codes to the constraint errors (the current English messages will be untouched). so the library user can map the error codes to there own translated/localized messages. @bighappyface what do you think this as a solution?

**Comment by Lube** [comment]
Great Input @jojo1981  I was thinking something along those lines, not actually providing error strings on different languages, just a more happy way to parse and interface with the schema errors.

**Comment by bighappyface** [comment]
@Lube I believe these facilities already exist:

https://github.com/justinrainbow/json-schema/blob/61a95a151aac86eaa9bbd31311d3d12a78c971b8/src/JsonSchema/Constraints/Constraint.php#L85-L89

**Comment by Lube** [comment]
@bighappyface You are absolutely correct, the symfony bundle I used, didn't expose the constraints, thanks for taking the time to answer this.

**Comment by jojo1981** [comment]
@Lube When the answer is sufficient enough, can you please close this issue? Thanks in advanced.

**Comment by Lube** [comment]
I would but I don't think I can, I didn't open this issue.

**Comment by jojo1981** [comment]
@Reggino When the answer is sufficient enough, can you please close this issue? Thanks in advanced.

**Comment by bighappyface** [comment]
Closing as part of clean up.
