### ISSUE TITLE
FileGetContents retriever : SSL errors

### ISSUE THREAD

**Issue by willgarcia** [justinrainbow/json-schema#116]
This retriever does not permit SSL configuration. Issue #114 starts fixing a part of the problem, but basically, it would be nice to allow developers to customize SSL options.

A specific case could be to disable any SSL verification (verify_peer for example, http://php.net/manual/en/context.ssl.php) which is not possible due to the current implementation. As an example a temporary fix to my specific probleme (on my very own fork), not reusable of course...:

```
$context = stream_context_create(array(
            'http' => array(
                'method' => 'GET',
                'header' => "Accept: " . Validator::SCHEMA_MEDIA_TYPE
            ),
            "ssl"=>array(
                'verify_peer'=>false,
                'verify_peer_name'=>false,
));
```

**Comment by bighappyface** [comment]
Closing due to age
