### ISSUE TITLE
The validators never actually check that what they get is indeed a JSON schema

### ISSUE THREAD

**Issue by skqr** [justinrainbow/json-schema#118]
Hi, Justin.

I'm trying to incorporate your package to my project, the [GOintegro HATEOAS Bundle](https://github.com/GoIntegro/hateoas-bundle/).

I accidentally passed an instance of a random object to the `JsonSchema\Validator::check` method, and only realized it when @acmenna pointed it out in the pull request.

The problem was that the `check` method returned `true`, even though it didn't even have a schema to check against.

I've been browsing the code, and it seems that at no point does any validator object validate that what it gets is actually a JSON schema of some kind.

Would it be possible for this validation to be added?

Thanks!

**Comment by bighappyface** [comment]
@skqr PRs are always welcome, but I think this is covered with https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/SchemaConstraint.php
