### ISSUE TITLE
Warn if trying to UriRetrieve::retrieve() an absolute path?

### ISSUE THREAD

**Issue by soundasleep** [justinrainbow/json-schema#123]
I was having an issue on Ubuntu with the following code, although it worked fine on Windows:

```php
    $retriever = new \JsonSchema\Uri\UriRetriever;
    $schema = $retriever->retrieve(__DIR__ . "/../composer-schema.json");
```

Adding the `file://` URI prefix worked fine. I know this is in the README but it's easy to miss...

```php
    $retriever = new \JsonSchema\Uri\UriRetriever;
    $schema = $retriever->retrieve("file://" . __DIR__ . "/../composer-schema.json");
```

Perhaps if the URI starts with "/", throw an exception or warning that it isn't a valid URI? Or automatically prepend it with `file://`?

**Comment by bighappyface** [comment]
Closing due to age. Please re-open if necessary.
