### ISSUE TITLE
validation not working correctly

### ISSUE THREAD

**Issue by bazo** [justinrainbow/json-schema#127]
you can find the schema and the data here https://gist.github.com/bazo/3361082c7b39f2a58f84

problem is i get an error Given schema must be an object in expenses[0] but is a array which is obviously not true

and it also throws an exception which the docs say nothing about, so the code won't even reach this part

    if ($validator->isValid()) {....

the same schema and data work correctly with https://github.com/hasbridge/php-json-schema

**Comment by alexrada** [comment]
have some similar issue with this library as well. 
Also error do not contain property names.

**Comment by toastedpark** [comment]
@bazo Could you please provide more detailed information. It seems to me that your json data instance is not valid against the schema you provided.

```
Array
(
    [0] => Array
        (
            [property] => 
            [message] => the property deviceToken is required
        )

    [1] => Array
        (
            [property] => 
            [message] => the property supplierCompanyId is required
        )

    [2] => Array
        (
            [property] => 
            [message] => the property expenses is required
        )

)
```

**Comment by bazo** [comment]
yeah, i validate just the data property against the schema, not the whole object sorry

**Comment by toastedpark** [comment]
I see, thanks. The schema you provided is not a valid json schema.

```
(...)
    "properties": {
        (...)
        "required": ["name", "price", (...)]
    }
```

In this form "required" is defining the schema for an instance property "required" and thus must be a schema object. That is what the exception states.
To make "required" work as a schema keyword you'd have to move it outside of the "properties" definition. Seemed to work for me as expected then.

**Comment by bazo** [comment]
i would never guess that from the exception message :)

**Comment by toastedpark** [comment]
ya, it could be more descriptive, maybe state that "the schema is invalid" even :O

**Comment by bighappyface** [comment]
Closing due to age. Please re-open if necessary.
