### ISSUE TITLE
Media type check too strict

### ISSUE THREAD

**Issue by bartfeenstra** [justinrainbow/json-schema#130]
The media type check seems a bit too strict. One of my schemas on file has a reference to https://raw.githubusercontent.com/iziteq/izi-api-schemes/master/sections/uuid_schema, which is marked text/plain, yet should be a valid schema file. As I have no control over the schema files other than that I can use them, I am wondering whether this check is too strict.

**Comment by Maks3w** [comment]
:+1: However is possible use a custom `URIRetriever`

**Comment by guinness74** [comment]
@Maks3w Would you expound upon that?

My workaround was to change line 29 in /vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php from:

`const SCHEMA_MEDIA_TYPE = 'application/schema+json';`

to:

`const SCHEMA_MEDIA_TYPE = 'application/json';`

I appreciate any help.

**Comment by jojo1981** [comment]
According the specs: http://json-schema.org/latest/json-schema-core.html#anchor34 it's not too restrict I think?

**Comment by Maks3w** [comment]
> The MIME type MUST be "application/json", **or any other subtype**

**Comment by jojo1981** [comment]
OK, then I think this issue can be closed?

**Comment by jojo1981** [comment]
thx!
