### ISSUE TITLE
Enum string comparison is not strict

### ISSUE THREAD

**Issue by loucho** [justinrainbow/json-schema#133]
I created a [pull request](https://github.com/justinrainbow/json-schema/pull/132) for this, right now the check for enums does a normal "==" comparison for enum values, and this is erroneously matching when the strings are numeric: 

"604.1" == "604.10" <-- this returns a match, because of the way PHP performs numeric string comparison

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/pull/132
