### ISSUE TITLE
php7 issue

### ISSUE THREAD

**Issue by ThaDafinser** [justinrainbow/json-schema#137]
Hello,

i'm having a build failure on tavis, because one classname is `String` on php7
https://travis-ci.org/ThaDafinser/ZfcDatagrid/jobs/55606988#L99

**Comment by xabbuh** [comment]
Travis is not using the latest Composer version. Running `composer self-update` at the beginning of the build will probably solve your issue.

**Comment by martinlindhe** [comment]
I see this:

$ composer --version
Composer version 1.0-dev (ab3622dff1db71024f327387408250208c139a0d) 2015-03-23 11:56:30
0.15s$ composer install
PHP Fatal error:  "string" cannot be used as a class name in phar:///home/travis/.phpenv/versions/nightly/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18
Fatal error: "string" cannot be used as a class name in phar:///home/travis/.phpenv/versions/nightly/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/String.php on line 18
The command "composer install" failed and exited with 255 during .


Will try to see if a "composer self-update" solves the issue

**Comment by ThaDafinser** [comment]
@xabbuh i added the update and it worked
https://travis-ci.org/ThaDafinser/ZfcDatagrid/jobs/55614932#L96

Now i need to fix my string class :+1: 
https://travis-ci.org/ThaDafinser/ZfcDatagrid/jobs/55614932#L335

**Comment by martinlindhe** [comment]
Yep that solved it for me too
