### ISSUE TITLE
uri format should allow protocol-relative urls

### ISSUE THREAD

**Issue by legoktm** [justinrainbow/json-schema#144]
Per <https://tools.ietf.org/html/rfc3986#section-4.2> protocol-relative urls are valid (it claims they're "rarely used" but that's not true anymore).

Downstream MediaWiki bug is https://phabricator.wikimedia.org/T93010

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/pull/174

**Comment by legoktm** [comment]
Huh? What does #174 and phpunit have to do with this bug?

**Comment by bighappyface** [comment]
@legoktm good catch! I meant https://github.com/justinrainbow/json-schema/pull/245
