### ISSUE TITLE
Internal Refs for Linked Schemas Looking in Wrong File

### ISSUE THREAD

**Issue by bshaffer** [justinrainbow/json-schema#147]
I am simply trying to validate swagger 2.0 schema.

My code looks like the following:

``` php
    $schemaDir = 'file://path/to/swagger-api/swagger-spec/schemas/v2.0';
    $retriever = new JsonSchema\Uri\UriRetriever;
    $schema = $retriever->retrieve($schemaDir.'/schema.json');

    $refResolver = new JsonSchema\RefResolver($retriever);
    $refResolver->resolve($schema, $schemaDir.'/schema.json');
```

I am receiving the following error:

```
Fragment "/definitions/positiveInteger" not found in file:///path/to/swagger-api/swagger-spec/schemas/v2.0/schema.json#/definitions/positiveInteger
```

As you can see from my [`schema.json`](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L928), every instance of `definitions/positiveInteger` includes an absolute URL to http://json-schema.org/draft-04/schema, yet this library is looking for `definitions/positiveInteger` inside the main document (`swagger-spec/../schema.json`) rather than inside the [`specified schema url`](http://json-schema.org/draft-04/schema#/definitions/positiveInteger).

Is this a bug or am I doing something incorrectly? I'm only trying to load the Swagger 2.0 schema and validate it, which I feel like should be a very standard use-case.

**Comment by bighappyface** [comment]
@bshaffer please try out v2.0.0 to see if this is resolved?
