### ISSUE TITLE
[Feature request] callbacks on recognitions of elements

### ISSUE THREAD

**Issue by patricksavalle** [justinrainbow/json-schema#148]
Might I suggest implementing some callback mechanism for successful element recognition. A simple function or a visitor-pattern reporting type and name etc.

A visitor-pattern comes to mind. Simple, effective, flexible.

https://sourcemaking.com/design_patterns/visitor 

    interface JsonSchemaVisitor 
    {
        public checkedInt( $value, $name, $path );
        public checkedDouble( $value, $name, $path );
       ....
    }
    $visitor = new JsonSchemaVisitor();
    $validator->check($data, $schema, $visitor);

blabla etc. etc. :)

**Comment by bighappyface** [comment]
@patricksavalle PRs are always welcome.
