### ISSUE TITLE
Cannot resolve references

### ISSUE THREAD

**Issue by claudiu-cristea** [justinrainbow/json-schema#151]
For some good reasons I'm caching the schema locally so I don't need to retrieve it from an URL. What I need is simply to resolve the references inside schema. I did:

```php
$schema = retrieve_schema_from_local_cache();
$ref_resolver = new JsonSchema\RefResolver();
$ref_resolver->resolve($schema);
```
Unfortunately, I'm getting:
```
JsonSchema\Exception\InvalidSchemaMediaTypeException: Media type application/schema+json expected in JsonSchema\Uri\UriRetriever->confirmMediaType() (line 64 of json-schema/src/JsonSchema/Uri/UriRetriever.php).
```

What I'm doing wrong?

**Comment by leftdevel** [comment]
I'm also wondering how to use the RefResolver. The Validator::check() method doesn't seems to trigger anything related to references. I'd expect it to automatically resolve all references and run a full validation.

I'll keep reading the source code, I'm hitting this issue just now. Leaving a comment to follow up :)

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/releases/tag/2.0.0

Please see updated README
