### ISSUE TITLE
Release current master as 1.4.2

### ISSUE THREAD

**Issue by Maks3w** [justinrainbow/json-schema#158]
Current master has important fixes let me remove big workarounds on https://github.com/Maks3w/SwaggerAssertions

Since 1.4.1 I only see bugfixes so next version could be 1.4.1

**Comment by GrahamCampbell** [comment]
We should probably get https://github.com/justinrainbow/json-schema/pull/153 and https://github.com/justinrainbow/json-schema/pull/154 merged first.

**Comment by Maks3w** [comment]
Not required. Be agile and release again when PRs become complete

**Comment by GrahamCampbell** [comment]
You say that, but that's clearly not happening...

**Comment by bighappyface** [comment]
Team,

#153 has been merged and I have asked for tests to verify #154.

I am going to issue release 1.4.2 now based on the various other PRs I have merged today, and will be happy to issue another release sometime after.

@GrahamCampbell you are correct; releases are not being tagged on each PR merge. I appreciate your help calling out project maintenance shortcoming to help keep things more professional, and I appreciate continued assistance from you, @Maks3w and @alecsammon for your contributions. I'll try to stay engaged, and reminders from the team are a big help.

**Comment by bighappyface** [comment]
Closed: https://github.com/justinrainbow/json-schema/releases/tag/1.4.2
