### ISSUE TITLE
"type" not correctly validated?

### ISSUE THREAD

**Issue by narcoticfresh** [justinrainbow/json-schema#162]
Hi all ;-)

I'm writing a schema that I want to validate against the draft-04 spec.. I made a standalone example here:

```php
<?php
require 'vendor/autoload.php';

use \JsonSchema\Uri\Retrievers\FileGetContents;
use \JsonSchema\Validator;

$schemaUrl = 'http://json-schema.org/draft-04/schema';

$retriever = new FileGetContents();
$schema = $retriever->retrieve($schemaUrl);

$data = <<<EOF
{
  "title": "A test schema",
  "id": "http://github.com/libgraviton...",
  "\$schema": "http://json-schema.org/draft-04/schema#",
  "type": "random-type",
  "properties": {
    "property": {
        "type": "random-type"
    }
  }
}
EOF;

$validator = new Validator();
$validator->check(json_decode($data), json_decode($schema));

if (!$validator->isValid()) {
    var_dump($validator->getErrors());
}

```

The `Validator` returns `true` on `isValid()` - AFAIK this should not be valid as `random-type` is not a valid primitive `type`..

Am I doing something completely wrong?

Thanks

**Comment by jojo1981** [comment]
@narcoticfresh tested this with the newest version (2.0.0) of this library and now it returns `false` on `isValid()`.

Errors output:
    
    [
        {
            "property": "properties.property.type",
            "message": "Does not have a value in the enumeration [\"array\",\"boolean\",\"integer\",\"null\",\"number\",\"object\",\"string\"]",
            "constraint": "enum",
            "enum": [
                "array",
                "boolean",
                "integer",
                "null",
                "number",
                "object",
                "string"
            ]
        },
        {
            "property": "properties.property.type",
            "message": "String value found, but an array is required",
            "constraint": "type"
        },
        {
            "property": "properties.property.type",
            "message": "Failed to match at least one schema",
            "constraint": "anyOf"
        },
        {
            "property": "type",
            "message": "Does not have a value in the enumeration [\"array\",\"boolean\",\"integer\",\"null\",\"number\",\"object\",\"string\"]",
            "constraint": "enum",
            "enum": [
                "array",
                "boolean",
                "integer",
                "null",
                "number",
                "object",
                "string"
            ]
        },
        {
            "property": "type",
            "message": "String value found, but an array is required",
            "constraint": "type"
        },
        {
            "property": "type",
            "message": "Failed to match at least one schema",
            "constraint": "anyOf"
        }
    ]

I don't think this is an issue anymore? If this is the case can you close this issue please? Thanks in advance!

**Comment by jojo1981** [comment]
@bighappyface I think this one can also be closed?

**Comment by jojo1981** [comment]
@narcoticfresh thanks for closing this issue.
