### ISSUE TITLE
URI Resolver not resolving absolute file paths correctly

### ISSUE THREAD

**Issue by georgeholt** [justinrainbow/json-schema#17]
Attempting to validate against a schema which extends another schema at say:
```
/path/to/abstract/schema.json
```
...throws a UriResolverException, stating that it's was unable to resolve the URI from base ''.

I'm not sure if I have to set a base somewhere, or if every schema requires an id (I see the code tries to use an id property as base if it's defined), but from my testing I can fix it by doing the following:

```php
// src/JsonSchema/Uri/UriResolver.php:27
public function parse($uri)
{
    preg_match('|^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?|', $uri, $match);

    $components = array();
    if (5 < count($match)) {
        $components =  array(
            'scheme'   => empty($match[2]) ? 'file' : $match[2], // Default the scheme to file://
            'authority' => $match[4],
            'path'         => empty($match[5]) ? '/' : $match[5]           // Default the path to /
        );
    } 
    if (7 < count($match)) {
        $components['query'] = $match[7];
    }
    if (9 < count($match)) {
        $components['fragment'] = $match[9];
    }
        
    return $components;
}
```

From what I can tell, when the resolve function is called with an empty base, then the condition on line 109 is met, causing the exception. This is because parsing the base (which in this case is empty) returns an empty path, meaning the number of basePathSegments will be zero.

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/pull/174

Please re-open if that is not the case.
