### ISSUE TITLE
Issues with enforced ID property in validated JSON

### ISSUE THREAD

**Issue by darh** [justinrainbow/json-schema#175]
Looks like UriRetriever::retrieve() adds id property to validated JSON. 

Please see https://github.com/alecsammon/php-raml-parser/issues/84 for details, samples and tests

Disabling the line and running tests again removes the issue. But I doubt that this is so trivial.

**Comment by bighappyface** [comment]
@darh please try out v2.0.0 to see if this is resolved?

**Comment by darh** [comment]
Sorry, I do not have that project/code active anymore.

**Comment by bighappyface** [comment]
Thanks for the update!
