### ISSUE TITLE
required method not working

### ISSUE THREAD

**Issue by rajeevchoudhary22** [justinrainbow/json-schema#177]
Hi,
I am trying to validate fields through required but not working its always return true.

using latest version

Working email and orderdate type but not working with required Please see below json format that i am using

{
  "type": "object",
  "properties": {
      "first_name":       {"type": "string"},
      "last_name":        {"type": "string"},
      "language":         {"type": "string"},
      "email":            {"type": "string", "format": "email"},
      "order_date":       {"type": "string", "format": "date"},
      "gender":           {"type": "string"}
  },
  "required" : ["first_name","last_name"]
}

I also try with below method

{
  "type": "object",
  "properties": {
      "first_name":       {"type": "string","required" : "true"},
      "last_name":        {"type": "string","required" : "true"},
      "language":         {"type": "string","required" : "true"},
      "email":            {"type": "string","required" : "true","format": "email"},
      "order_date":       {"type": "string","required" : "true","format": "date"},
      "gender":           {"type": "string","required" : "true"}
  }

}

Please suggest me what i need to do.

**Comment by jojo1981** [comment]
@rajeevchoudhary22 I've tested this with the newest version (2.0.0) of this library.

**Schema:**
    
    {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "order_date": {
          "type": "string",
          "format": "date"
        },
        "gender": {
          "type": "string"
        }
      },
      "required": [
        "first_name",
        "last_name"
      ]
    }

**Test data:**
    
    {}

**Not valid, errors:**
    
    [
        {
            "property": "first_name",
            "message": "The property first_name is required",
            "constraint": "required"
        },
        {
            "property": "last_name",
            "message": "The property last_name is required",
            "constraint": "required"
        }
    ]

I think it works as supposed? Can you test this and closed this issue? Thanks in advance.

**Comment by lukeoliff** [comment]
I am also having this problem.

Payload:
```
{
  "location": "homepage",
  "referer": "http://www.google.co.uk"
}
```

Schema:
```
{
  "type": "object",
  "properties": {
    "location": {
      "type": "string"
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "userId": {
      "type": "integer"
    },
    "sessionId": {
      "type": "string"
    },
    "referer": {
      "type": "string"
    },
    "userAgent": {
      "type": "string"
    },
    "ipAddress": {
      "type": "string"
    }
  },
  "required": [
    "location",
    "referer",
    "userAgent",
    "ipAddress"
  ]
}
```

Returns true on `->isValid()`. 

Version in composer.lock is `2.0.1` @ `9ef71fdf8aa`.

**Comment by lukeoliff** [comment]
@jojo1981 I've just modified my composer.json to specifically install `2.0.0` in a vein attempt to avoid debugging the library, but `->isValid()` is still returning `true`.

If I manage to identify a problem then I'll create a pull request.

**Comment by jojo1981** [comment]
@lukeoliff Tested this with version: 2.0.2 of this library.

**Schema:**

    {
      "type": "object",
      "properties": {
        "location": {
          "type": "string"
        },
        "time": {
          "type": "string",
          "format": "date-time"
        },
        "userId": {
          "type": "integer"
        },
        "sessionId": {
          "type": "string"
        },
        "referer": {
          "type": "string"
        },
        "userAgent": {
          "type": "string"
        },
        "ipAddress": {
          "type": "string"
        }
      },
      "required": [
        "location",
        "referer",
        "userAgent",
        "ipAddress"
      ]
    }

**Data:**

    {
      "location": "homepage",
      "referer": "http://www.google.co.uk"
    }

**isValid:** false

**Errors:**

    [
      {
        "property": "userAgent",
        "message": "The property userAgent is required",
        "constraint": "required"
      },
      {
        "property": "ipAddress",
        "message": "The property ipAddress is required",
        "constraint": "required"
      }
    ]

As you can see here it works like supposed. I think you're using an older version of this library. Please re-test this, but make sure you use the **newest version of this library**!.

**Comment by Keirua** [comment]
I'm using version 2.0.5 and I also have the same issue.

My validation code is the one from the samples (see below), and in order to see what I'm doing wrong, I used the 2 test data (input data and schema) from @jojo1981 supplied here. They are supposed to return invalid results but they do not behave as such, they all are considered valid.

Any idea what could be wrong ?

```
$validator = new JsonSchema\Validator;
$validator->check($data, (object)['$ref' => 'file://' . realpath('schema.json')]);

if ($validator->isValid()) {
    echo "The supplied JSON validates against the schema.\n";
} else {
    echo "JSON does not validate. Violations:\n";
    foreach ($validator->getErrors() as $error) {
        echo sprintf("[%s] %s\n", $error['property'], $error['message']);
    }
}
```

**Comment by Keirua** [comment]
Ok, I managed to get it to work. The sample code, that uses an object that contains the file to validate against as a reference, does not behave as expected.
`
$validator->check($data, (object)['$ref' => 'file://' . realpath('schema.json')]);`

With an line schema (that could be loaded in another way), I have a working sample (v2.0.5)

```
<?php

require 'vendor/autoload.php';

$dataValid = json_decode(
'{
  "location": "homepage",
  "referer": "http://www.google.co.uk"
}');


$schema =
'{
  "type": "object",
  "properties": {
    "location": {
      "type": "string"
    },
    "time": {
      "type": "string",
      "format": "date-time"
    },
    "userId": {
      "type": "integer"
    },
    "sessionId": {
      "type": "string"
    },
    "referer": {
      "type": "string"
    },
    "userAgent": {
      "type": "string"
    },
    "ipAddress": {
      "type": "string"
    }
  },
  "required": [
    "location",
    "referer",
    "userAgent",
    "ipAddress"
  ]
}';


// Validate
$validator = new JsonSchema\Validator;
$validator->check($dataValid, json_decode($schema));

if ($validator->isValid()) {
    echo "The supplied JSON validates against the schema.\n";
} else {
    echo "JSON does not validate. Violations:\n";
    foreach ($validator->getErrors() as $error) {
        echo sprintf("[%s] %s\n", $error['property'], $error['message']);
    }
}

```


Output:


```
JSON does not validate. Violations:
[userAgent] The property userAgent is required
[ipAddress] The property ipAddress is required
```

**Comment by lukadschaak** [comment]
Knowing this thread is ages ago, i want to share an experience with the same problem, that required properties are ignored.

No idea, whether this is intended or not.

See this example (modified from the one above):
One difference is that i am usind `json_decode` with the second parameter `true` that forces the decoder to produce arrays instead of stdClasses. Second difference: I am assuming in the schema, that the type is array. Result: required is ignored.
```
$dataInvalid = json_decode(
    '{"location": "homepage", "referer": "http://www.google.co.uk"}',
    true
);

$schema =
'{
    "type": "array",
    "properties": {
        "location": {
            "type": "string"
        },
        "referer": {
            "type": "string"
        },
        "userAgent": {
            "type": "string"
        },
        "ipAddress": {
            "type": "string"
        }
    },
    "required": [
        "location",
        "referer",
        "userAgent",
        "ipAddress"
    ]
}';

$validator = new \JsonSchema\Validator;
$validator->validate($dataInvalid, json_decode($schema));

if ($validator->isValid()) {
    echo "The supplied JSON validates against the schema.\n";
} else {
    echo "JSON does not validate. Violations:\n";
    foreach ($validator->getErrors() as $error) {
        echo sprintf("[%s] %s\n", $error['property'], $error['message']);
    }
}

```
Output:
```
The supplied JSON validates against the schema.
```

**Comment by erayd** [comment]
`properties` and `required` are both object constraints; they aren't applicable to arrays, which you have used `type` to enforce.

> I am usind json_decode with the second parameter true that forces the decoder to produce arrays instead of stdClasses.

Don't do that. Associative arrays aren't a valid JSON type, and the validator isn't designed with them in mind. You may get undesirable behavior if you insist on doing so anyway - even though PHP does allow some similarities, they aren't actually objects, and cannot be treated as equivalent.

**Comment by lukadschaak** [comment]
Alright. Thanks a lot. For usual serialization with json i prefer assoziated arrays, but for this puporse here, it's absolutly understandable and i will use the object decoding. 👍

**Comment by HSweta** [comment]
@lukadschaak 
I am trying to use sub-schema like, diving the schema into multiple sub schema but the required field is not working.
Can you please let me know what's the issue with my schema?

address.json
{
  "definitions": {
        "type": "object",
        "properties": {
          "item_id": { "type": "number" },
          "quantity": { "type": "number" },
          "title": { "type": "string" },
          "description": { "type": "string" }
        },
        "required": [ "item_id", "quantity", "title", "description" ],
      }
  }

demoschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "address": {
      "$ref": "address.json#/definitions"

    }
  }
}

validator function 

 
            var json = await File.ReadAllTextAsync(@"JsonFiles\test1.json");
            using (StreamReader file = File.OpenText(@"schema\demoschema.json"))
            using (JsonTextReader reader = new JsonTextReader(file))
            {
                JSchemaUrlResolver resolver = new JSchemaUrlResolver();

                JSchema schema = JSchema.Load(reader, new JSchemaReaderSettings
                {
                    Resolver = resolver,
                    BaseUri = new Uri(@"\schema\demoschema.json")
                });
            }

            var jsonSchema = await NJsonSchema.JsonSchema.FromFileAsync(@"schema\demoschema.json");
            var errors = jsonSchema.Validate(json);

**Comment by lukadschaak** [comment]
First, please re-format your code snippets. In this way, they are hard to read. When i copy paste it, it seams that your JSON syntax is incorrect. There is a comma in the line of the required array
wrong: `"required": [ "item_id", "quantity", "title", "description" ],`
right: `"required": [ "item_id", "quantity", "title", "description" ]`

What do you exactly mean by "required filed is not working" ?
Also, what is the input, that you are trying to validate?

I don't think, that your problem is related to my post, as you are using the type `object` correctly, where i was using the type `array`.

**Comment by HSweta** [comment]
@lukadschaak 
yeah, the comma is mistake while copy-paste.
Just want to know what you mean by object decoding.

basically, I am working on validating the json file, if it has required field or not, as you have also kind of same problem that required is not working so, want to ask.

the required file that mentioned in schema (address.json) which is referenced by demoschema.json.
when I am passing empty json in test1.json file to validate the schema, the validation function showing true which is wrong.

**Comment by lukadschaak** [comment]
What i meant by object decoding is `"type": "object",` vs. `"type": "array",`

As the following post said, `required` does not work together with `type: array`. But your code uses `type: object`. So it is a completly different situation that you have.

> `properties` and `required` are both object constraints; they aren't applicable to arrays, which you have used `type` to enforce.
> 
> > I am usind json_decode with the second parameter true that forces the decoder to produce arrays instead of stdClasses.
> 
> Don't do that. Associative arrays aren't a valid JSON type, and the validator isn't designed with them in mind. You may get undesirable behavior if you insist on doing so anyway - even though PHP does allow some similarities, they aren't actually objects, and cannot be treated as equivalent.

**Comment by erayd** [comment]
@HSweta I feel I should also chime in here to point out that this isn't a general support forum for the JSON schema spec. You aren't even using this library; your validator code is not PHP - so this is not the right venue to be bumping years-old old issues to get help with the spec, or assistance with using a different validator library.
