### ISSUE TITLE
Recursive nested object - The maximum stack depth has been exceeded

### ISSUE THREAD

**Issue by bosbaber** [justinrainbow/json-schema#180]
The following example schema breaks when trying to resolve recursive references. 

'JsonSchema\Exception\JsonDecodingException: The maximum stack depth has been exceeded'

# Example
## Schema
```json
{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "title":"Experiment",
   "description":"Testing recursive objects",
   "type":"object",
   "properties":{
       "root" : {
           "type" : ["array"],
           "oneOf": [
                {"$ref":"#/definitions/treeObj"}
           ]
        }          
   },
   "required" : [
       "root"
   ],
   "definitions":{
       "treeObj":{
           "type":"array",
           "items" : {
               "oneOf": [
                    { "type" : "string"},
                    { "$ref":"#/definitions/treeObj" }
               ]
           }
       }    
   }
}
```
## Json Document
The json I'm trying to validate would look something like this

```json
{
        "root" : [
            "some-tree-heading",
            [
                "some-tree-deeper-heading",
                [
                     "some-even-deeper-heading",
                     [
                        "the-deepest-heading"
                     ]
                ]
            ]
        ]
}
```

The validator at http://jsonschemalint.com/draft4/ is quite happy with these inputs and I would expect a json validator to be able to do this. 

I missing something?

**Comment by bighappyface** [comment]
@bosbaber what version of this package are you using?

**Comment by bosbaber** [comment]
According to composer I'm using v 1.4.4

I used "justinrainbow/json-schema": "~1.4"  in my composer require.

Code used 
```php
require_once "vendor/autoload.php";

$data = json_decode(file_get_contents('data.json'));
$schemaPath = "schema.json";
        
$retriever = new JsonSchema\Uri\UriRetriever;
$schema = $retriever->retrieve('file://' . realpath($schemaPath));        

$refResolver = new JsonSchema\RefResolver($retriever);
$refResolver->resolve($schema, 'file://' .realpath($schemaPath));        
        
$validator = new JsonSchema\Validator();
$validator->check($data, $schema);

if($validator->isValid()){
	echo "It worked!";
} else {
        echo "error ---".$validator->getErrors()[0]['property']." ".$validator->getErrors()[0]['message'];        
}        

echo "\n\n".json_encode($result)."\n\n";

```

**Comment by bosbaber** [comment]
It seems that a temporary solution is to revert back to 1.4.3

**Comment by bighappyface** [comment]
Try setting the `maxDepth` static variable for `JsonSchema\RefResolver` as is shown in the unit test:

https://github.com/justinrainbow/json-schema/blob/34ca930d9fbfb439ae8d3b87ca046b914e190295/tests/JsonSchema/Tests/RefResolverTest.php#L353-L354

Does increasing the value from 7 to 20 avoid the exception?

**Comment by bosbaber** [comment]
I've played around trying to set it to a variety of values and it doesn't seem to make a difference.

1.4.3 seems to be working great though. I'll see if I can do some actual debugging tomorrow.

**Comment by gbradley** [comment]
I'm having the same issue but 1.4.3 isn't working for me either.

**Comment by nncas** [comment]
I'm having the same issue, I'm using v 1.5.0 and the example above.

**Comment by bighappyface** [comment]
Are you sure this is an issue with the validator? Before the exception was added, the validator was just doing a `return` and not evaluating JSON data any further than the max depth, so it was effectively lying to you about validity below the max depth.

**Comment by maximumduncan** [comment]
I don't think it's got anything to do with the validation - for me the exception gets thrown when calling `RefResolver::resolve()`, before I even instantiate a validator.

I think the fundamental issue here is that this validation library *cannot* support recursive schema definitions when it's `$ref` handing logic tries to resolve all `$ref`s up front to "flesh out" a single schema.

By definition, a recursive schema built using `$ref`s has a non-`$ref` equivalent of infinite size.

**Comment by bighappyface** [comment]
@maximumduncan you are correct: the exception is thrown via the `RefResolver` and has nothing to do with the validator because the exception is thrown prior to validating the resolved schema. Thanks for keeping my comments honest.

That being said, the outcome I described still stands. The `RefResolver` was not producing a complete schema so any validations that occurred with the incomplete schema were inaccurate.

This is clearly the most important outstanding issue with this package. Most contributors simply fix things for their needs and with @justinrainbow out of the mix there is no central maintainer to add core functionality.

I'll see what I can work in, but all contributions are welcome nonetheless ;)

**Comment by jojo1981** [comment]
@bighappyface I think this one can also be closed?

**Comment by bighappyface** [comment]
@jojo1981 thanks!

**Comment by golabiusz** [comment]
Worth mentioning: Closed with https://github.com/justinrainbow/json-schema/releases/tag/2.0.0
