### ISSUE TITLE
Configure RefResolver:$maxDepth?

### ISSUE THREAD

**Issue by eschwartz** [justinrainbow/json-schema#181]
I kept getting `The maximum stack depth has been exceeded` errors, and I couldn't figure out what was going on. Finally, I found a public static `RefResolver$maxDepth` resolver property. I tried setting it to 20 (default was 7), and the schema validated fine.

I feel a little funny overriding a public static property on a test utility. What would you think about making this a configurable property on the `RefResolver` instance?

**Comment by vdespa** [comment]
Same issue here.

**Comment by micahgodbolt** [comment]
This is also required for our project. We either have to manually change the file after installation, or we'll need to fork the project. Would much rather just have a param we could set.

**Comment by bighappyface** [comment]
@micahgodbolt why not submit a PR instead of working from a fork? If you are going to make a change that will help others, you should consider giving it back.

**Comment by micahgodbolt** [comment]
@bighappyface oh I certainly would! I totally agree with contributing > complaining :) I was going to say that #184 already submitted one, but it seems you already closed that.

**Comment by bighappyface** [comment]
I'll help with any PR that has support from the community. I don't think #184 accomplishes anything and closed it predicting that it would not pass community scrutiny.

PRs are very welcome and the exclusive source of maintenance on this project. My only ask is that you submit changes with suitable tests and consider helping review other PRs in need of a review.

**Comment by mathroc** [comment]
`RefResolver:$maxDepth` is a public (static) property  so it's already configurable:

```php
RefResolver:$maxDepth = 42;
```

**Comment by eschwartz** [comment]
Yes, you can do that. I guess my point was that I felt kind of dirty overriding a global static property, that is used by all instances of RefResolver.

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/releases/tag/2.0.0
