### ISSUE TITLE
The maximum stack depth has been exceeded

### ISSUE THREAD

**Issue by mguacci** [justinrainbow/json-schema#193]
I report the following log trace from apache log:

[Wed Oct 21 13:24:32 2015] [error] [client 10.100.100.2] PHP Fatal error: Uncaught exception 'JsonSchema\Exception\JsonDecodingException' with message 'The maximum stack depth has been exceeded' in /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php:105\nStack trace:\n#0 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(198): JsonSchema\RefResolver->resolve(false, 'file:///var/www...')\n#1 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(128): JsonSchema\RefResolver->resolveProperty(Object(stdClass), 'additionalPrope...', 'file:///var/www...')\n#2 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(198): JsonSchema\RefResolver->resolve(Object(stdClass), 'file:///var/www...')\n#3 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(128): JsonSchema\RefResolver->resolveProperty(Object(stdClass), 'items', 'file:///var/www...')\n#4 /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php(180): JsonSchema\RefResolver->resolve(Ob in /var/www/poi_dp/vendor/justinrainbow/json-schema/src/JsonSchema/RefResolver.php on line 105

Is there a solution?

I try to increase the maxDepth value, but it doesn't work. I follow these instructions:
 $ wget http://getcomposer.org/composer.phar
 $ php composer.phar require justinrainbow/json-schema:~1.3
 $ sudo cp -r vendor /var/www/poi_dp/

Thank you,
Massimiliano.

**Comment by mguacci** [comment]
I resolved! After increasing value I correct postgresql query in radial_search.php that referred to table fields that didn't exist.

Thank you.

Massimiliano

**Comment by jojo1981** [comment]
Also this problem is solved after #245 is merged.

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/releases/tag/2.0.0
