### ISSUE TITLE
Suggestion EnumConstraint

### ISSUE THREAD

**Issue by silverpark** [justinrainbow/json-schema#195]
Hi,

I have a suggestion, in the [code](https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/EnumConstraint.php#L44) why not change `print_r($schema->enum, true)` by `json_encode($schema->enum, true)` ?

Because it show 

```
[key.exemple] Does not have a value in the enumeration Array\n(\n    [0] => toto\n    [1] => tata\n)\n)
```

My suggestion display :

```
[key.exemple] Does not have a value in the enumeration [\"toto\",\"tata\"])
```

If you approve, I can do an PR.

**Comment by bighappyface** [comment]
See https://github.com/justinrainbow/json-schema/pull/196
