### ISSUE TITLE
NumberConstraint allows 0.00 for an exclusive minimum of 0

### ISSUE THREAD

**Issue by wpillar** [justinrainbow/json-schema#199]
When validating this:

```json
{
  "amount": 0.00
}
```

Against this:

```json
{
  "properties": {
    "amount": {
      "type": "number",
      "minimum": 0,
      "exclusiveMinimum": true
    }
  }
}
```

It passes, when it should fail according to this json schema linter:

![image](https://cloud.githubusercontent.com/assets/188514/11394756/fbfae5ae-935e-11e5-86c8-9850ef5590ec.png)

http://jsonschemalint.com/draft4/

This is because of the strict equality check here: https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/NumberConstraint.php#L28

**Comment by wpillar** [comment]
Any acknowledgement of this one?

**Comment by bighappyface** [comment]
@wpillar good catch. PRs welcome.
