### ISSUE TITLE
$validator->check expects an json in form of an object but throws no error

### ISSUE THREAD

**Issue by jonathan-s** [justinrainbow/json-schema#203]
I was trying to figure out why the validator didn't work properly because I was getting the error in $validator->getErrors() instead of $validator->check throwing an error because it was expecting an object rather than a string or an array.

**Comment by mirfilip** [comment]
@jonathan-s 
I'm not sure I follow. I've added a [sample playground](https://github.com/mirfilip/json-schema-playground/tree/issue/203) where you can verify object validation:
Schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "test",
  "type": "object"
}
```
* String:
```
Input "a string"
Validation status (Validator::isValid): false
Errors:
[
    {
        "property": "",
        "message": "String value found, but an object is required",
        "constraint": "type"
    }
]
```
* Array:
```
Input []
Validation status (Validator::isValid): false
Errors:
[
    {
        "property": "",
        "message": "Array value found, but an object is required",
        "constraint": "type"
    }
]
```

**Comment by bighappyface** [comment]
@jonathan-s sorry for the confusion. The JSON must be decoded prior to use:

https://github.com/justinrainbow/json-schema/tree/f1f874d2c0eb546553290f56655c755f69cbaaa7#usage
