### ISSUE TITLE
$depth property overflow

### ISSUE THREAD

**Issue by Markard** [justinrainbow/json-schema#208]
Hi
I'm currently faced an issue with $depth property in RefResolver. Also I would like to notice that we have cyclic references and this is fine for us.

Example:
```php
$retriever = new UriRetriever();
$schema = $retriever->retrieve('file://1.json');
RefResolver::$maxDepth = 10;
$refResolver = new RefResolver($retriever);
try {
    $refResolver->resolve($schema, 'file://schemas/');
} catch (JsonDecodingException $e) {}
```

And for example we reached a depth. But we still need to resolve another file in our script:

```php
$retriever = new UriRetriever();
$schema = $retriever->retrieve('file://2.json');
$refResolver = new RefResolver($retriever);
try {
    $refResolver->resolve($schema, 'file://schemas/');
} catch (JsonDecodingException $e) {}
```

So we already get $depth on the start of second resolving. And I don't get why you use this property as "protected static". May it would be better to use just protected property or even function scope property?

**Comment by Markard** [comment]
Hello again. I figured out why the problem occurs. 
It looks like when JsonDecodingException is thrown the RefResolver::$depth doesn't restored to initial state.

**Comment by jojo1981** [comment]
@Markard I think this issue can be closed? Also after merging: #245 the $depth is not used anymore.

**Comment by Markard** [comment]
Sure, thanks.

**Comment by jojo1981** [comment]
@Markard Thanks for closing this issue!
