### ISSUE TITLE
Empty arrays errors

### ISSUE THREAD

**Issue by enyosolutions** [justinrainbow/json-schema#211]
Hello, 

thanks you for your hard work on this project. I'm facing some issues with validating empty arrays, when they have the type object.

Do you or anyone knows how to solve or hack that problem ?

```
array('prices' => array())
```

<code>
[prices] array value found, but an object is required
</code>

yelp !!!

**Comment by mirfilip** [comment]
@enyosolutions json-schema validates json data types. In the json world, object is an object and array is an array. They are not the same. You could call it a "hard type validation". In PHP world however, these are _sometimes_ interchangeable. Still, if your schema expects an object under `prices key`, `array()` is not the data type to satisfy it

Unlike in PHP, json arrays cannot have keys. In your particular case, you like your schema to look like [that](https://github.com/mirfilip/json-schema-playground/blob/issue/211/schema/211.json) and your input in PHP like:
```php
$inputData = new \stdClass();
$inputData->prices = new \stdClass();
```
you can replace `\stdClass()` with any object.

**Comment by jojo1981** [comment]
Also **typecast** an array to an object will work:
    
    $data = (object) array(
        'prices' => (object) array()
    );

**Comment by mirfilip** [comment]
@jojo1981 You're right in general. [There are some cases to be aware of](https://3v4l.org/hfIgB) - note the keys "0", "1" being created.

**Comment by jojo1981** [comment]
@mirfilip Thanks for your explanation, but I did **NOT** mean to cast the whole `$data` object, only use a short notation with the use of inline castings for building a data set without using a json string which you need to decode. So only cast an array (hash table) to an object when this is what you want.

JSON arrays are **always** indexed arrays.
JSON objects are the same as hash tables.

For example JSON:

    {
        "version": "v1",
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "required": [
            "size"
        ],
        "properties": {
            "size": {
                "type": "integer"
            }
        }
    }
    
Can be written like:
    
    $data = new \stdClass();
    $data->version = 'v1';
    $data->{'$schema'} = 'http://json-schema.org/draft-04/schema#';
    $data->type = 'object';
    $data->required = array(
        'size'
    );
    $data->properties = new \stdClass();
    $data->properties->size = new \stdClass();
    $data->properties->size->type = 'integer';
    

Or with the "inline" casting notation:
    
    $data = (object) array(
        'version' => 'v1',
        '$schema' => 'http://json-schema.org/draft-04/schema#',
        'type' => 'object',
        "required" => array(
            "size"
        ),
        'properties' => (object) array(
            'size' => (object) array(
                'type' => 'integer'
            )
        )
    );
    
**Note:** `required` is always an indexed array and will NOT be casted to an object!

**Comment by mirfilip** [comment]
@jojo1981 Yup, exactly that :+1: My comment was just a warning point not to go about and typecast everything to object.

**Comment by jojo1981** [comment]
@enyosolutions is this still an issue? If not please close this issue. Thanks in advance!

**Comment by jojo1981** [comment]
@bighappyface I think this one can also be closed?
