### ISSUE TITLE
Best way of using definitions in another file?

### ISSUE THREAD

**Issue by jonathan-s** [justinrainbow/json-schema#214]
I have a schema that looks like this. The pound sign signifies that the definitions should be found in the current schema. I'm guessing you could add the full path to `$ref` in the json schema. But at the same time when you use the `refResolver` you give the path to the schema where definitions are. 

    $refResolver = new JsonSchema\RefResolver($retriever);
    $refResolver->resolve($schema, 'file://' . $schemaPath);
       

    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "temp",
        "type": "object",
        "properties": {
            "first-name": {"$ref": "#/definitions/first-name"}
        }
    }

So is there a way to refer to that document in the json schema, or how should you do it?

**Comment by bighappyface** [comment]
@jonathan-s checkout https://github.com/justinrainbow/json-schema/pull/210
