### ISSUE TITLE
Pattern Limitations: Regex

### ISSUE THREAD

**Issue by xMolchy** [justinrainbow/json-schema#219]
Hi,

I really like this library but have seen that Regex  pattern is very limited.

**FILE:** StringConstraint.php
**CODE:**
```php
        // Verify a regex pattern 
        if ( isset( $schema->pattern ) && !preg_match( '#' . str_replace( '#', '\\#', $schema->pattern ) . '#', $element ) ) {
            $this->addError( $path, "Does not match the regex pattern " . $schema->pattern );
        }
```

**PROBLEM:** Options after regex pattern are not possible, simple example like /u (Unicode) ...
because you are starting and ending regex yourself ... i think whole regex should be done by developers ... if they make an error is their fault ...

**Comment by bighappyface** [comment]
@xMolchy pull requests welcome :wink:

**Comment by xMolchy** [comment]
Pull request created and patterns tested ... so should work ... ty

**Comment by jojo1981** [comment]
What's the state of this issue?

**Comment by xMolchy** [comment]
This has been resolved in new version ... you can not override default lib and specify your own when needed ... before it was not possible to override without influencing composer/vendor ...

Happy coding ...

**Comment by TFarla** [comment]
So how would we go about creating a pattern that respects Unicode?

**Comment by bighappyface** [comment]
@xMolchy to be clear, this issue is resolved for you? If so, which version of this package was the solution?

**Comment by xMolchy** [comment]
@bighappyface Yes it is resolved ty

**Comment by TFarla** [comment]
@xMolchy can you show me an example on how you have fixed it?

**Comment by xMolchy** [comment]
The library works good now, only thing you need todo is specify correct REGEX:

**PATTERN example which i user for username:**
(*UTF8)^[0-9\\p{L}\\p{Pd}\\p{N}]{3,25}+$"

You need to specify (*UTF8) on the start of your REGEX pattern then it will work.
