### ISSUE TITLE
Would you be interested in a pull request ?

### ISSUE THREAD

**Issue by enyosolutions** [justinrainbow/json-schema#235]
Hello,

First of all thanks for this project, it's saving me a lot of trouble while using schema less databases.

I have extended the project with some additions to make more useful to me and i was wondering if you'd be interested in having those added to the project :+1: 

1. A generate function, that generate an empty array from a model. => **Generating a skeleton before inserting data.**
2. A casting function that casts the types of the fields according the a schema => **preventing cast related errors  eg.  "1" <> 1**

If you are indeed interested, let me know i'll send a pull request.

**Comment by bighappyface** [comment]
PRs are always welcome
