### ISSUE TITLE
New package owner

### ISSUE THREAD

**Issue by bighappyface** [justinrainbow/json-schema#244]
All,

I propose we migrate this package to another owner.

@justinrainbow hasn't been spotted in some time. The last time @justinrainbow jumped he granted me collaborator access and I have tried to manage the steady stream of PRs in his absence. It is very clear that there is still a lot of work to be done on this package, especially in the ref resolver, and I think all of the consumers of this package would benefit greatly from an engaged owner with full rights to the repo and composer package listing.

I suggest the following:
1. We find someone willing to fork and adopt this package
2. We modify this repo/package to be listed as "abandoned" on the composer side and indicate the new package/owner
3. We establish a proper "contributing" file and set of guidelines
4. We establish a protocol for updating the package version
5. We establish a set of collaborators on the new repo so that multiple contributors can help keep things progressing

I am fine with adopting the package but I want to give anyone else out there a chance to volunteer. Many of the contributors are very passionate about all aspects, from functionality to versioning, and I think the most engaged volunteer deserves the adoption.

Please submit your thoughts to this proposal and we can get this figured out.

**Comment by jojo1981** [comment]
I want contribute, did you see my created issue: Fix RefResolver and make it compatible with draft-04 #240. I can create a PR?

**Comment by bighappyface** [comment]
@jojo1981 thanks for your interest and contribution. Regarding the refresolver, have you reviewed the extensive PR under development by @araines ?

https://github.com/justinrainbow/json-schema/pull/210

**Comment by jojo1981** [comment]
@bighappyface I did see his fix, but I did no review.
I had a solution in my mind and because I wanted to have a clear mind I did not look at his code.
I will now check the extensive PR under development by @araines

**Comment by jojo1981** [comment]
Just to speed things up, I also have created a PR of my solution [Let the public decide ;-)] just kidding.
This evening I will check extensive PR under development by @araines but I have noticed the build of that PR is still failing.

**Comment by jojo1981** [comment]
@bighappyface I think you have earned it to be the new package owner, because you're already maintaining this package for a while.

**Comment by mirfilip** [comment]
@bighappyface @jojo1981 I see there is a lot of issues hanging open. It's hard to check what is implemented, what is bugged etc. As I'm becoming a heavy user of this validation, I can at least help sort out some of these. What do you think?

**Comment by bighappyface** [comment]
@mirfilip great feedback. Your interest in helping is a key reason (#5) why I want to move this package to another owner. We need multiple trusted folks available to help maintain things.

I'll start working on the migration but I don't want to hold things up on this repo at the moment. I want to focus on getting #245 out the door so that we can get closer to full coverage for Draft 4.

**Comment by jojo1981** [comment]
@bighappyface You can put me on the list, I'm available as collaborator when starting to migrate to a new owner.

**Comment by bighappyface** [comment]
I have kickstarted a new owner/vendor for this package but I have not gotten any feedback from @justinrainbow about working with me to abandon this vendor. I will initiate contact with the Packagist folks to see what options I have but we may just have to leave this repo as-is and update the readme to make it clear that we have moved on. Personally I think the abandonment warning during `composer install` is the best way to go, and perhaps we will get there, but I am into the action of moving forward so we can expand collaborative participation.

In moving to a new vendor/repo, we may have the opportunity to leverage #245 as the new version and "2.0.0" becomes the new version in the new repo. Thoughts?

**Comment by Maks3w** [comment]
@bighappyface You are not discussing what owner wil have the new package.

Do you propose bighappyface/json-schema which is hosted in your personal account?

Please NO.

Host the project under a new GitHub organization. Don't own the project under the power of a single person.

**Comment by bighappyface** [comment]
@Maks3w this issue IS a discussion on how to go about a possible ownership change, and nothing has really happened yet because the original owner has gone missing completely.

I'm open to migrating this to a group but that isn't the only option. This repo, and MANY others, operate under individual user repos with lots of collaborators, so user-based ownership isn't bad or evil.

I'm more concerned about responsive collaborators helping progress the software than ownership details.

**Comment by mathroc** [comment]
I'm fine with either bighappyface/json-schema or some-organization/json-schema. I'll be using this library more and more so I'll try to help.
there's currently a bug I'd like to report but it's hard to explain with a simple reproducible test case (and building the test case isn't that easy either)

**Comment by eldering** [comment]
What is the status of this issue? I'm asking because on https://github.com/bighappyface/json-schema it says that that repository is the formerly https://github.com/justinrainbow/json-schema. However, both repositories have seen updates, this one more recently, and the repositories seem to have diverged. So I'm wondering which one best to use.

**Comment by shmax** [comment]
Maybe it's time to move forward with the idea to create an organization?

https://help.github.com/articles/creating-a-new-organization-account/

**Comment by bighappyface** [comment]
I don't have admin access to this repo and the owner has abandoned us. I will close my copy of the repo.
