### ISSUE TITLE
oneOf / anyOf behaves like allOf in terms of errors reported

### ISSUE THREAD

**Issue by mirfilip** [justinrainbow/json-schema#248]
Hi,
I need to validate an input that has four possible forms:
* `null`
* `[]`
* `{}`
* non-empty object, with allowed key "description" that is a string longer than x

(It's just a simplification of a real life case)

Schema looks like:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "test",
  "anyOf": [
    {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "description": {
          "type": "string",
          "minLength": 2
        }
      }
    },
    {"type": "object", "maxProperties": 0},
    {"type": "array", "maxItems": 0},
    {"type": "null"}
  ]
}
```

Input `{}`, `[]`, `null`, `{"description: "foo"}` obviously returns a validation success. When I, however, pass `{"description": "f"}` (too short) and run against:
```
$validator = new \JsonSchema\Validator();
$validator->check($input, $schema);
if (!$validator->isValid()) {
  echo json_encode($validator->getErrors(), JSON_PRETTY_PRINT);
}
```
I get:
```
[
    {
        "property": "description",
        "message": "Must be at least 2 characters long",
        "constraint": "minLength",
        "minLength": 2
    },
    {
        "property": "",
        "message": "Must contain no more than 0 properties",
        "constraint": "maxProperties",
        "maxProperties": 0
    },
    {
        "property": "",
        "message": "Object value found, but an array is required",
        "constraint": "type"
    },
    {
        "property": "",
        "message": "Object value found, but a null is required",
        "constraint": "type"
    },
    {
        "property": "",
        "message": "Failed to match at least one schema",
        "constraint": "anyOf"
    }
]
```
As you can see, this looks like an expected output for `allOf`. `anyOf`, `oneOf` should have `OR` / `XOR` behaviour in terms of errors reported. Expected output in the mentioned case would be:
```
[
    {
        "property": "description",
        "message": "Must be at least 2 characters long",
        "constraint": "minLength",
        "minLength": 2
    }
]
```

This looks somewhat related to #89.

**Comment by jojo1981** [comment]
@mirfilip I do not agree. I think the only right error should be:

    [
        {
            "property": "",
            "message": "Failed to match at least one schema",
            "constraint": "anyOf"
        }
    ]

But maybe it's handy to add a `context` property to the error object and add all failed rules (of the sub schemas) in case validating `allOf`, `anyOf` and `oneOf`.

So for example:
    
    [
        {
            "property": "",
            "message": "Failed to match at least one schema",
            "constraint": "anyOf",
            "context": [
                {
                    "property": "description",
                    "message": "Must be at least 2 characters long",
                    "constraint": "minLength",
                    "minLength": 2
                },
                {
                    "property": "",
                    "message": "Must contain no more than 0 properties",
                    "constraint": "maxProperties",
                    "maxProperties": 0
                },
                {
                    "property": "",
                    "message": "Object value found, but an array is required",
                    "constraint": "type"
                },
                {
                    "property": "",
                    "message": "Object value found, but a null is required",
                    "constraint": "type"
                }
            ]
        }
    ]

**Comment by mirfilip** [comment]
@jojo1981 actually the truth lies somewhere in between:
- I [compared](https://tonicdev.com/5703657937a13d1200a5afa9/57036d0a76f90a11000996d8) the same situation with [ajv validator](https://github.com/epoberezkin/ajv) (which I consider the most feature complete json-schema v4 / v5 implementation I encountered to date) - as you can see, it returns exactly the same errors set as this one
- I had a quick look through [specs](http://json-schema.org/documentation.html) and couldn't find the definitive guidance - I will look into it deeper

So my conclusion is kind of a wishful thinking.

Also, I agree with your proposal. Having `Failed to match at least one schema` as the "top most" error message is ofc very nice. Then, having some kind of a switch to "expose more details" would be fine. Anyhow, if you have `anyOf`, with the allowed options being:
- an empty object
- an object with property `foo` a string
- an empty array
- a null
and the input is `{"foo": 1}` - then you're kinda interested about errors related to the _object validation_, aren't you? (you already met a type condition, property value is wrong though)

Nevertheless, with neither option present, if you have a schema complicated enough you end up with shitload of meaningless errors. I find myself implementing an extra layer to leave a validation errors I want. But it's a major PITA.

**Comment by jojo1981** [comment]
@mirfilip What you're suggesting is a kind of closest match error validation. Why only the property foo is not a string should apply? At the validation level there are 4 rules which need to be checked in order to apply if any matches. So when there is no rules matching we know that all defined rules (4 rules in this case) are validated and non of them successfully passes. So how can we determine which rule is the "bad guy"?

**Comment by jojo1981** [comment]
@mirfilip how do think this must be resolved?

**Comment by mirfilip** [comment]
@jojo1981 I was offline for the most of the previous week. Give me an extra day to make some examples.

**Comment by jojo1981** [comment]
@mirfilip No problem!

**Comment by mirfilip** [comment]
@jojo1981 
>At the validation level there are 4 rules which need to be checked in order to apply if any matches. So when there is no rules matching we know that all defined rules (4 rules in this case) are validated and non of them successfully passes. So how can we determine which rule is the "bad guy"?
Continuing the example, there are 4 rules, yes. 2 of them treat about the object. One null, one array. Every of them has a **type** constraint. In the example I wanted to show how input `{"foo": 1}` meets the `"type": "object"` constraint of **two** rules, but doesn't meet the details of how the object should look inside. This is the hint we could use.

Below is a simplified version of my json schema:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "test",
  "anyOf": [
    {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": true,
      "properties": {
        "foo": {
          "anyOf": [
            {"type": "null"},
            {"type": "string", "minLength": 2, "maxLength": 65535}
          ]
        },
        "bar": {
          "anyOf": [
            {"type": "null"},
            {"type": "string", "maxLength": 255}
          ]
        },
        "baz": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^[a-z0-9]{1,255}$": {
              "type": "object",
              "properties": {
                "value": {"type": "string", "maxLength": 2048}
              },
              "required": ["value"],
              "additionalProperties": false,
              "maxProperties": 1
            }
          }
        }
      }
    },
    {
      "anyOf": [
        {"type": "object", "maxProperties": 0},
        {"type": "array", "maxItems": 0},
        {"type": "null"}
      ]
    }
  ]
}
```

With the input like `{"foo": "a"}`, you get:
```
[
    {
        "property": "foo",
        "message": "String value found, but a null is required",
        "constraint": "type"
    },
    {
        "property": "foo",
        "message": "Must be at least 2 characters long",
        "constraint": "minLength",
        "minLength": 2
    },
    {
        "property": "foo",
        "message": "Failed to match at least one schema",
        "constraint": "anyOf"
    },
    {
        "property": "",
        "message": "Must contain no more than 0 properties",
        "constraint": "maxProperties",
        "maxProperties": 0
    },
    {
        "property": "",
        "message": "Object value found, but an array is required",
        "constraint": "type"
    },
    {
        "property": "",
        "message": "Object value found, but a null is required",
        "constraint": "type"
    },
    {
        "property": "",
        "message": "Failed to match at least one schema",
        "constraint": "anyOf"
    }
]
```

I come from the scenario of writing a json based API when throwing such an error at the user is really counter productive. That's where I started to implement a logic for cherry-picking error messages.

Surely, when you try to input `true` that doesn't match any type, having all the errors thrown at you is understandable. Less so if you already match the type.

Does that make sense?

**Comment by jojo1981** [comment]
@mirfilip Thanks for your clear explanation. I know what you mean, but it is still a _closest match algorithm_. 

What if there are 2 rules (subschemas) in the **anyOf** array both have the same type? For example both schema's are of type **object** and they both are describing a different object and the validated object doesn't match not one of them. In this case which schema is the closest one who doesn't matched?

**Example schema:**
    
    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "test",
        "anyOf": [
            {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "id"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    }
                }
            },
            {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    }
                }
            }
        ]
    }
    

Test data set:
    
    {
        "age": 34
    }
    

Do you know which problem I foresee here?

**Comment by mirfilip** [comment]
@jojo1981 yes, it's the closest match algorithm. I understand in some cases (your example) there would be no benefit of such an algorithm as the input partially matches both rules. In that case, it'd be valid to return all errors. Then the question is - "should we go further?" Properties matching, number of properties etc.

I see there is no good way approaching this and returning all errors is de facto a standard for validators in other languages. This can be closed then. Thx for bearing with me ;)

**Comment by jojo1981** [comment]
@mirfilip Thanks for the discussion. It keeps us focussed!

**Comment by Isinlor** [comment]
I'm currently building schema for my API and I'm looking for a good validator. My schema will be heavy based on "oneOf" validation (major use of polymorphism). I think that [nested validation message format proposed in this comment](https://github.com/justinrainbow/json-schema/issues/248#issuecomment-205943943) is way superior to the current flat one. Actually I may resign from JSON Schema validation if my users will be forced to face with dozens of messages and only the last one will provide an obscure reason of such situation (one must deduct that the reason for this noise is "oneOf" rule). Nested structure allows to group messages and bring the most important one to the top. The complexity of understanding messages goes from linear to logarithmic, as one can apply binary search, assuming that human will even find and understand the last validation message. It is major usability improvement.
