### ISSUE TITLE
Hyphen (-) in package name conflicts with PHP's use statement

### ISSUE THREAD

**Issue by sgoendoer** [justinrainbow/json-schema#250]
Hi,

when using this JsonSchema validation with composer's autoload functionality, you will end up having a statement like

    use justinrainbow\json-schema\JsonSchema;

which will throw an error because of the hyphen in the package name.

**Comment by jojo1981** [comment]
@sgoendoer The correct namespace you can use is: `JsonSchema`. For example when you need the validator you can import it into the current namespace by adding this line: `use JsonSchema\Validator`.

You must include the composer autoloader first: require `vendor/autoload.php`

The following file: ./vendor/composer/autoload_namespaces.php
Must contains an entry like: `'JsonSchema' => array($vendorDir . '/justinrainbow/json-schema/src'),`

**Comment by jojo1981** [comment]
@sgoendoer When the answer is sufficient enough, can you please close this issue? Thanks in advanced.
