### ISSUE TITLE
500 error PHP message: PHP Fatal error:  Uncaught exception 'JsonSchema\Exception\InvalidArgumentException' with message 'no schema found to verify against'

### ISSUE THREAD

**Issue by kaihendry** [justinrainbow/json-schema#251]
I'm using your sample code on a linux env:

     $schema = $refResolver->resolve('file://' . realpath('schema.json'));

schema.json is in the same directory, but it's not finding it! What am I missing? The file is most certainly there!

```
15/Apr/2016:03:48:10 +0000 [ERROR 500 /validate/] PHP message: PHP Warning:  First parameter must either be an object or the name of an existing class in /srv/spa/validate/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/SchemaConstraint.php on line 30
PHP message: PHP Fatal error:  Uncaught exception 'JsonSchema\Exception\InvalidArgumentException' with message 'no schema found to verify against' in /srv/spa/validate/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/SchemaConstraint.php:34
Stack trace:
#0 /srv/spa/validate/vendor/justinrainbow/json-schema/src/JsonSchema/Validator.php(36): JsonSchema\Constraints\SchemaConstraint->check(Array, NULL)
#1 /srv/spa/validate/index.php(28): JsonSchema\Validator->check(Array, NULL)
#2 {main}
  thrown in /srv/spa/validate/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/SchemaConstraint.php on line 34```

**Comment by jojo1981** [comment]
@kaihendry Can you add the `schema.json` file you're using. As I can see in the error message  `$schema = $refResolver->resolve('file://' . realpath('schema.json'));` will return NULL.

**Comment by jojo1981** [comment]
Maybe this is the same issue: #253

**Comment by bighappyface** [comment]
Try it without the protocol in favor of a relative path?

**Comment by kaihendry** [comment]
I got it working http://s.natalian.org/2016-04-16/diff.txt

Don't have time to figure out what I was doing wrong. I worked from another example found via https://github.com/search

Not a fan of this OO syntax.

**Comment by bighappyface** [comment]
We are glad you worked it out.
