### ISSUE TITLE
ContentType checking

### ISSUE THREAD

**Issue by guyradford** [justinrainbow/json-schema#257]
As expected out server returns the content type as application/json, this breaks the validation as you are looking for application/schema+json. I could update the server, but then all .json files will have the schema type.

Is there a way to override the default expected content type?

As I understand it there is no proposed extension for json schema files and a single extension can have two content types. This make this validation a little harsh.

Thank you
Guy

**Comment by bighappyface** [comment]
Perhaps a filename convention will help?

Something like "foo.schema.json" would make it clear for developers and server configurations to determine that file contains a schema and should be handled accordingly.

What is the exact issue you are having? Is there some code you are running that is having problems?

**Comment by guyradford** [comment]
Yes I could name our schema something like foo.schema.json and update nginx to set the content type for this extension to "application/schema+json".

However not everyone will be able to change the contentType on the server. If the contentType is wrong when loading a schema by http:// or https:// the schema gets rejected with "Media type application/schema+json expected". This validation cant be ignored. 

See file: /src/JsonSchema/Uri/UriRetriever.php
Line: 54
Exception thrown line 63 if line 54 fails.

**Comment by bighappyface** [comment]
@guyradford thoughts? https://github.com/justinrainbow/json-schema/pull/259

**Comment by guyradford** [comment]
@bighappyface Yes that seems to make sense, I cant imagine the need for any other contentTypes, or making it user defineable. So would work perfectly.

**Comment by bighappyface** [comment]
@guyradford please update to 2.0.1 and let me know if your issues are resolved.

**Comment by guyradford** [comment]
@bighappyface,  Yes that works perfectly, Thank you.
