### ISSUE TITLE
JSON considered valid when it has elements not described in the schema

### ISSUE THREAD

**Issue by novotnej** [justinrainbow/json-schema#297]
Case in point - recently we restructured most of our statistic nodes in JSON endpoints. Since not all profiles have statistics, this node is not required. However we added some new features and the validator didn't complain once, even though it was no longer valid.. (The JSON feed/endpoint contains elements that are not described in the schema)

This would be really important for us to be resolved, as we try to make sure our endpoints are valid before they go to production, but so far we haven't found a reliable PHP tool to do this..

**Comment by boekkooi-fresh** [comment]
Hi @novotnej,  
Did you by any chance for get to get [`additionalProperties`](https://spacetelescope.github.io/understanding-json-schema/reference/object.html) to false in the schema's?

**Comment by FlorianSW** [comment]
Like @boekkooi-fresh explained, setting `additionalProperties` to false (or any other valid value) will result in a schema error when a not-described property is set in the checked JSON (including this json-schema library) :) I think this is an invalid issue :-)

**Comment by bighappyface** [comment]
@FlorianSW @boekkooi-fresh  thanks for jumping on this!

Closing... please re-open if necessary.
