### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by FlorianSW** [justinrainbow/json-schema#298]
Since the last release in June, the library had [some commits](https://github.com/justinrainbow/json-schema/compare/2.0.5...master) (some of them could be inportant for users of the library). Is there any plan for the next release? When it comes, what it contains and what version number it'll have? :)

Best,
Florian

**Comment by bighappyface** [comment]
I'm ready to bump to 3.0.0 and am really just dithering on whether to include #277. If not then that PR will probably warrant another major bump to 4.0.0.

I'm open to suggestions.

**Comment by FlorianSW** [comment]
PR #277 looks like a really big change :/ However, having to major versions in a reasonable short time isn't really consumer friendly, too. So I (personally) would prefer to have the major change in the upcoming 3.0.0 major release.

However, I haven't reviewed the code so far (sorry), and it seems, that I don't plan to do so (sorry again :(). From a first glance it looks reasonable and _should_ work. So, if you've tested it and it works like expected (with the new example code in the README), count this as a "community-support", at least from me :P

**Comment by bighappyface** [comment]
Unfortunately many PRs come in that, well, completely overhaul things and those contributors are rarely concerned with a) the implications and b) helping ensure a smooth review/acceptance. They just put it on the maintainer and expect things to be merged, which really makes being a maintainer a thankless job (to say the least). Consumer friendliness isn't a hallmark of software development.

**Comment by bighappyface** [comment]
https://github.com/justinrainbow/json-schema/releases/tag/3.0.0

**Comment by steffkes** [comment]
i'm one of the guys bringing in a crazy PR and not having as much time as i'd like to review the work others did and help you out @bighappyface :/

I'll try to get a bit of time this week to review #277 and hopefully a few more - shouldn't be that hard. saying _i don't actually need it_ feels a bit to easy for my taste .. if everyone would go with that, i don't think this library would be where it is right now.

**Comment by steffkes** [comment]
okay, that went down fast *g nevertheless, i'm trying to scrape out a few minutes/hours every now and then and trying to help out reviewing PRs and issues. we'll see how good i am at this ;o

**Comment by bighappyface** [comment]
@steffkes I know how you feel :D

Thanks a ton for your help, no matter how big or small.
