### ISSUE TITLE
Documentation : Is the readme example actually working ?

### ISSUE THREAD

**Issue by etiennechabert** [justinrainbow/json-schema#299]
I am using your library for few days and I struggled a bit at the beginning to make it work with a very basic case.

I did my best to follow your example, but it was not really helping :

> $data = json_decode(file_get_contents('data.json'));

> // Validate
> $validator = new JsonSchema\Validator;
> $validator->check($data, (object)['$ref' => 'file://' . realpath('schema.json')]);

I created this stackoverflow post with my issue, please feel free to read it : http://stackoverflow.com/questions/39042346/json-schema-required-properties-ignored/39048262?noredirect=1#comment65497165_39048262

The answer was not really helping, for this reason I finally execute my code and your library step-by-step to understand what was going on. To be honest I don't understand how your example could work. After debugging your code, I am not able to tell where you are loading the JSON schema. 

Inside the  **UndefinedConstraint:validateCommonProperties** function, where you are checking if required properties are in, my schema is not loaded yet.

As you can see in the stackoverflow post, I finally make it work by loading the schema myself.

I created this ticket because I get quite confused by your example, I am definitely missing something about it... Is it possible for you to add more details on how dummies like me are supposed to use it ;) 

Best regards,

**Comment by bighappyface** [comment]
PRs are welcome.

I am not sure why you sent to SO first, but you are at the right place now.

**Comment by etiennechabert** [comment]
Well I was looking for help to solve my issue, in my mind I was doing something wrong.

After being able to solve it and found where the problem was coming from, I am now felling a bit more confident to create an issue here.

**Comment by bighappyface** [comment]
I see. You and all are welcome to raise an issue. We may not be the most responsive bunch, but we we are friendly and want to help.

**Comment by etiennechabert** [comment]
Glad to hear that @bighappyface, according to what you read here and in SO, do know where I messed up ? The example you are giving on the readme is supposed to work out of the box ?

More basically I am looking for some documentation / resources about this project, describing the different features. I did find the 'docs' folder after cloning the repo, but there is nothing really new in comparison with the actual readme.

Thank's for your help.

**Comment by bighappyface** [comment]
@etiennechabert I have not had a chance to dive in yet. I'll try to get back to you in the next week or so (super busy with work and school).

Thanks for your patience.

**Comment by miwels** [comment]
Hi there,

I have followed your stackoverflow question and, even though I can see my schema and data being loaded, the 'check' method returns NULL.

Any idea of why is this happening? I assumed that if there was something wrong loading the data and/or schema an Exception would be thrown but I'm just getting a NULL value so I cannot use any if the isValid or getErrors methods.

My code is as follows:

```
<?php
namespace Tests\Validator;

use JsonSchema\Validator;

class ValidatorTest {

    protected $validator;
    protected $sampleJson;

    public function __construct() {
        $this->validator = new Validator();
        $this->sampleJson = json_decode($this->generateSampleData());
        $this->schema = $this->getSchema(realpath("schema.json"));
    }

    public function run()
    {
        $validator = new \JsonSchema\Validator;
        $result = $validator->check($this->sampleJson, $this->schema);

        // at this point $result is NULL so none of the following functions can be used

        if($result->isValid()) {
            print "JSON data matches schema";
        }
        else {
            echo "JSON data does not match the schema";
            foreach($this->validator->getErrors() as $error) {
                echo sprintf("[%s] %s\n", $error['property'], $error['message']);
            }
        }
    }

    protected function getSchema($filePath) {
        return json_decode(file_get_contents($filePath));
    }

    protected function generateSampleData() {
        // return some sample json
    }
```

**Comment by etiennechabert** [comment]
Hey Buddy,

You should ignore the return value from the check function.

After the check just focus on $validator->isValid() which is going to return a boolean value.

If you are interrested by an array of errors you should try $validator->getErrors().

Good luck ;-)

**Comment by miwels** [comment]
Thanks for your reply @etiennechabert 

Unfortunately isValid() returns always true no matter what I pass in. I tried to add some garbage to the data and isValid() is still returning "true".

**Comment by etiennechabert** [comment]
Got you, so you are in the same situation than I was.

Could you please give me the print_r output for your json_data and json_schema ?

**Comment by miwels** [comment]
The problem (I think) is that json_decode() already parses and validates the JSON. If there are any syntax errors it will return, and if that's the case the validator will return "true". I don't know if this is a bug or a feature but maybe they author should look into that.

**Comment by etiennechabert** [comment]
json_schema role is not to check your JSON syntax validity, but to check the schema of the provided data. For example data_type, mendatory_value, extra properties and so on.

For this reason you should first provide a correct JSON before trying to check his schema

**Comment by miwels** [comment]
Well, I just ran a very simple test.

My schema:
```
{
    "title" : "Demo schema",
    "type" : "object",
    "properties" : {
        "success" : {
            "type" : "array"
        }
    }
}
```

My data:
```
{
    "success": ""
}
```

This is my output if I print the data and the schema to make sure it's reading it:

```
class stdClass#4 (1) {
  public $success =>
  string(0) ""
}
class stdClass#5 (3) {
  public $title =>
  string(15) "CatchApp schema"
  public $type =>
  string(6) "object"
  public $properties =>
  class stdClass#6 (1) {
    public $success =>
    class stdClass#7 (1) {
      public $type =>
      string(5) "array"
    }
  }
}
```
I'm using this validator to compare results:
http://www.jsonschemavalidator.net/
And using the exact same data I'm getting an error but this library is giving me a "true" value when I run isValid().

Am I doing something wrong?

**Comment by bighappyface** [comment]
To be clear, these tests are being performed against 3.0.0?

Are you encountering similar behavior on 2.0.5?

**Comment by stamster** [comment]
I'm using 2.0.x and it just doesn't work. `isValid()` always returns bool true. It just doesn't care about any data you'll pass to it.

Source code has this comment: 
```
 /**
     * Validates the given data against the schema and returns an object containing the results
     * Both the php object and the schema are supposed to be a result of a json_decode call.
     * The validation works as defined by the schema proposal in http://json-schema.org
     *
```

I don't see how this code is suppose to work, it lacks the very basic function - to actually load json schema from a file and to compare it with in memory object (decoded json). 

I guess no one uses this package, that's why we are discussing such a basic issue here. It just does not work, plain and simple. Sorry.

**Comment by etiennechabert** [comment]
@stamster It would be interesting to have a look at the source code leading to a isValid() always returning true, you probably failed somewhere.

Anyway I agree with you : the README exemple doesn't work and probably need to be fixed, but the library do work and I am actually using it to check user's input on a WS actually in production.

**Comment by stamster** [comment]
I just used official example posted here on GH. If that fails (actually validates), w/o any error reported back - user cannot be doing anything wrong, it's the app which fails (i.e. broken).

I took a 5 mins to try latest 3.0.x version, and guess what - it works. Documentation suggests 2.0 branch, which is obviously wrong and not working. 

That's the conclusion - by just upgrading to the new branch my code runs fine, so 2.0.x is totally broken.

Nevertheless, I already have switched to another lib, which is, IMHO, much more cleaner.

@etiennechabert thanks for reply!

**Comment by stamster** [comment]
I have created new PR for README file change.

**Comment by shmax** [comment]
@bighappyface Time to close this one?

**Comment by bighappyface** [comment]
Closing for now, can re-open if needed
