### ISSUE TITLE
$delimiter not used

### ISSUE THREAD

**Issue by calcinai** [justinrainbow/json-schema#303]
Is there a reason that `$delimiter` from the function signature on [TypeConstraint.php#L112](https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/TypeConstraint.php#L112) is unused and just hardcoded in the function itself?

**Comment by calcinai** [comment]
#304 includes a fix for this if it's unintentional.

**Comment by bighappyface** [comment]
#304 merged
