### ISSUE TITLE
Documentation: Following the readme does not work

### ISSUE THREAD

**Issue by nwolff** [justinrainbow/json-schema#311]
Following the current readme:

I installed json-schema:~2.0

I tried to follow the example in the usage section and the schema was never being read (and the validator always told me things were valid). It's because in version 2.0.x the validator expects an object containing a parsed schema and not a $ref->uri map.

Then I spent an hour in xdebug and then I found a discussion of a similar issue: https://github.com/justinrainbow/json-schema/issues/299 

I think there are 2 fixes for this:
- Upgrade the readme to tell people to install json-schema:~3.0
- Warn the user when the schema cannot be loaded. I don't know how to implement this throughout, but these are the lines that were giving me pain: https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/UndefinedConstraint.php#L28-L30

**Comment by stamster** [comment]
#299

**Comment by stamster** [comment]
I have tried with PR #309

**Comment by prewk** [comment]
Related because I'm confused: I'm getting `null` from `$validator->isValid()`, after running `check` with a schema. Does that mean my schema is invalid?
