### ISSUE TITLE
Error when trying to use cast and coerce

### ISSUE THREAD

**Issue by iongion** [justinrainbow/json-schema#321]
Using json-schema 4.0, for this code that respects documentation on github repo home page:
```
            $validator = new Validator(
                Constraint::CHECK_MODE_TYPE_CAST | Constraint::CHECK_MODE_COERCE
            );
```

The error is:
```
Uncaught TypeError: Argument 1 passed to JsonSchema\Constraints\Constraint::__construct() must be an instance of JsonSchema\Constraints\Factory, integer given .... defined in vendor\justinrainbow\json-schema\src\JsonSchema\Constraints\Constraint.php:40
```

I've noticed now it expects a factory, how can it be solved as I have no clue on how to pass the factory

**Comment by gtuccini** [comment]
I had the same problem. I solved it by using:
`
$validator = new \JsonSchema\Validator(new \JsonSchema\Constraints\Factory(null, null, \JsonSchema\Constraints\Constraint::CHECK_MODE_TYPE_CAST | \JsonSchema\Constraints\Constraint::CHECK_MODE_COERCE));
`

**Comment by steffkes** [comment]
@iongion where in the docs did you find this example? i remember a PR around `Factory` being merge some time ago - probably we forgot to update the docs for this topic

**Comment by shmax** [comment]
This PR syncs the readme with the code, but it also changes the API a bit:
https://github.com/justinrainbow/json-schema/pull/320

Comments welcome.

**Comment by iongion** [comment]
@steffkes I mentioned it is on the github home repo page, that is where I took it from, now I see the factory, which is good! 👍
