### ISSUE TITLE
allOf breaks CHECK_MODE_TYPE_CAST

### ISSUE THREAD

**Issue by pcjacobse** [justinrainbow/json-schema#334]
When validating simple input data (GET or POST) I use CHECK_MODE_TYPE_CAST for validating.
This work good when doing simple check, but when nested in allOf the validation breaks.

Schema:
```json
{
  "properties": {
    "test": {
      "type": "integer"
    }
  }
}
```

Data:
```json
{
  "test": "1"
}
```

Result: OK

But with the following schema:
```json
{
  "properties": {
    "test": {
      "allOf": [
        {
          "type": "integer"
        }
      ]
    }
  }
}
```

Result: String value found, but an integer is required + Failed to match all schemas

**Comment by shmax** [comment]
I started to work on this, but there are a few sticky points. @bighappyface do you know if ```allOf``` definitions can be nested inside one another? Same question for ```oneOf``` and ```anyOf```.  If so, we may need to rethink the coercion innards. This would all be easy if the ```check``` methods could accept a reference as their first argument, but that would break backwards compatibility for everybody inlining their checks. I'm wondering if it would make more sense to add a new top-level ```coerce``` method that does require a reference for the first arg... I'll start experimenting.
