### ISSUE TITLE
Object within object possible?

### ISSUE THREAD

**Issue by mark-sp** [justinrainbow/json-schema#343]
Hi,

I just found out about json-schema specification and its PHP library and I am wondering whether the library supports [nested JSON structures](https://spacetelescope.github.io/understanding-json-schema/structuring.html). 

If so, I'd like to know how I have to set up my schema file to do the right validation. I've been following guidelines from json-schema docs with no problem so far, but I couldn't manage to make it work when one of the properties is itself an object: the validation is always OK although the elements within the inner object are not right.

Any idea of what I could be doing wrong? Is that a limitation of the library?

```
{
	"id": "http://yourdomain.com/schemas/schema.json",
	"title" : "Person",
	"type" : "object",
	"properties" : {
		"birthdate" : {
			"type" : "string",
			"format" : "date-time"
		},
		"gender" : {
			"type" : { "enum" : ["M", "F"] } 
		},
		"region" : {
			"type" : "string"
		},
		"province": {
			"type" : "string"
		},
		"phisical" : {
			"type" : "object",
			"properties" : {
				"weight" : {
					"type" : "integer",
					"minimum" : 0
				},
				"height" : {
					"type" : "integer",
					"minimum" : 0
				}
			}
		},
```

**Comment by shmax** [comment]
> the elements within the inner object are not right

Please post a minimal (but complete) code sample demonstrating the problem you're having, including the input.

**Comment by mark-sp** [comment]
Code was taken directly from the github example:

```
<?php

$data = json_decode(file_get_contents('test.json'));
$schema = json_decode(file_get_contents('patient_solti_schema.json'));

require_once 'vendor/autoload.php';

// Validate
$validator = new JsonSchema\Validator;

$validator->check($data, $schema);

if ($validator->isValid()) {
    echo "The supplied JSON validates against the schema.\n";
} else {
    echo "JSON does not validate. Violations:\n";
    foreach ($validator->getErrors() as $error) {
        echo sprintf("[%s] %s\n", $error['property'], $error['message']);
    }
}
```

**Comment by mark-sp** [comment]
I've corrected the schema file and I validated it using an online tool, but still it does not work when I try the PHP code

**Comment by shmax** [comment]
Hi, unless you provide a complete code sample there's not much we can do for you. We need to see both the input being validated as well as the schema. If you can reduce your problem to a minimal code sample that illustrates the issue you're seeing there's a very good chance we can tell you what's happening.

**Comment by mark-sp** [comment]
Find below sample of the JSON I am trying to validate as well as the schema. The main PHP is as I posted before. I believe the problem is on the way I load the schema:
```
$schema = json_decode(file_get_contents('patient_solti_schema.json'));
$data = json_decode(file_get_contents('test.json'));
$validator->check($data, $schema);
```
if instead I use 
```
$data = json_decode(file_get_contents('test.json'));
$validator->check($data, (object)['$ref' => 'file://' . realpath('patient_solti_schema.json')]);
```
Then it works. This is fine for this example, but it won't work in my application, where I have to load the schema from a DB. Is there any alternative way to load the schema from, for instance, a variable?


Schema:

`{
	"$schema" : "http://json-schema.org/draft-04/schema#",

	"definitions" : {
		"phisical" : {
			"type" : "object",
			"properties" : {
				"weight" : { "type" : "integer" },
				"height" : { "type" : "integer" }
			},
			"required" : ["weight"]
		}
	},

	"title" : "Patient SOLTI schema",
	"type" : "object",

	"properties" : {
		"current patient status": {
			"type": "string",
			"enum": [ "Con ensayos", "Sin ensayos" ]
		},
		"collection site": {
			"type": "string"
		},
		"patient code" : {
			"type": "string"
		},
		"birthdate" : {
			"type" : "string",
			"format" : "date-time"
		},
		"gender" : {
			"type" : "string",
			"enum" : ["M", "F"]
		},
		"region" : {
			"type" : "string"
		},
		"province": {
			"type" : "string"
		},
		"ECOG" : {
			"type" : "integer",
			"minimum" : 0
		},
        "treatments" : { "type": "array", "id" : "treatments",
        	"items" : [{
 
   "type":"object",
   "properties":{  
      "name":{  
         "type":"string"
      },
      "dose":{  
         "type":"integer"
      }
   },
   "required" : ["dose","name"]
}]
        },
		"phisical1" : { "$ref": "#/definitions/phisical" },
		"recruitment date" : {
			"type" : "string",
			"format" : "date-time"
		}
	}
}`

Input:
```
{
	"current patient status" : "Con ensayos",
	"collection site": "ICO Hospitalet",
	"patient code" : "53",
	"gender" : "F",
	"weight" : 56,
	"height" : 162,
	"recruitment date" : "2015-07-18T12:34:54Z",
    "phisical1": {
      "ola" : 44,
      "weight" : 56
    },
    "treatments" : [{"name":"je", "dose" : 33}]
}
```

**Comment by shmax** [comment]
Hey there, sorry for the long delay. I finally had a chance to try out your code. You never really told us what was going wrong, but one thing I noticed is that you don't have a call to `addStorage` (to resolve your internal $ref):

```
$schemaStorage->addSchema('file://mySchema', $schema); // I took this line from the sample in the readme
```

Once I did that things seemed to work smoothly (although I didn't get any validation errros; are we expecting some?).

**Comment by DannyvdSluijs** [comment]
@mark-sp in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.
