### ISSUE TITLE
Include schema with file://

### ISSUE THREAD

**Issue by realshadow** [justinrainbow/json-schema#344]
Hey, 

I am trying to include a different schema, that should be reused in multiple schemas. Something like

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "additionalProperties": true,
    "allOf": [
        {
            "$ref": "file://request.json"
        }
    ]
}
```

The problem is the `FileGetContents.php` file is not able to find the schema (tried with `file://./request.json` as well) unless I specify the full path e.g. `/var/www/html/foo/bar/request.json`. 

Is it possible to reference a schema in the same directory?

**Comment by SereneAnt** [comment]
Take a look at the [code sample](https://github.com/justinrainbow/json-schema#with-inline-references) in `README.md` file.

**Comment by realshadow** [comment]
`SchemaStorage` wont help here, the error comes from `JsonSchema/Uri/Retrievers/FileGetContents.php ` which `SchemaStorage` uses as well.

What I would need is for `FileGetContents` retriever to look for the schema in the same directory as the checked schema.

I tried to set my own retriever in validator but it still keeps using the original one

**Comment by realshadow** [comment]
So, I managed to set my own retriever directly in schema storage and it works. Thanks
