### ISSUE TITLE
DateTime doesn't validates correct? 

### ISSUE THREAD

**Issue by mskoric** [justinrainbow/json-schema#348]
hi, 

i notice a problem with the "date-time" format.

They guys from spacetelescope say that there example is valid => 
https://spacetelescope.github.io/understanding-json-schema/about.html?highlight=date%20time 

but the validator says no :)

input: 
...
{
  "birthday": "2017-02-22"
}

json_spec
....
    "birthday": {
      "type": "string",
      "format": "date-time"
},

I think your version is correct because RFC3309 doesn't allow that TIME is optional. 
I don't know whats correct. Can you gimme a hint?

Greetz,

Majk

**Comment by shmax** [comment]
@mskoric Your interpretation looks correct to me.

**Comment by MichalOdchazel** [comment]
Hi,
is this correct behavior?

Input: `"time": "2019-13-37T10:06:30.857+0200"` -> look at the date: **37**
Schema: `date-time`

In `JsonSchema\Rfc3339\createFromString` return `DateTime` object with $date value is `2020-01-06 10:06:30.857000`

I think this should fall.

**Comment by DannyvdSluijs** [comment]
@mskoric in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.

@MichalOdchazel what you are seeing is called rollover where the calendar keeps counting days after 2019-12-31. Same applies in PHP when adding a day to the lat day of the month the result will be the first of the next month.
