### ISSUE TITLE
Could you support incasesensitive pattern matching?

### ISSUE THREAD

**Issue by markomanninen** [justinrainbow/json-schema#352]
Schema:

```
{
  "firstname": {
    "type": "string",
    "pattern": "alan",
    "inCaseSensitive": true
  }
}
```

would use -i modifier on preg_match and match with Alan, ALAN, aLaN, etc.

https://github.com/markomanninen/json-schema/commit/d1011e3ea6f44017e9c6d5c29e52ca2be8c11041#diff-9129e81a8f8053dcd8747c5b88dbaef4

**Comment by shmax** [comment]
I think you're out of luck; according to the Json Schema specification, `pattern` [SHOULD be valid according to the ECMA 262 [ecma262] regular expression dialect](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.8), and ECMA 262 doesn't allow for inline flag specifiers.

That said, there is certainly nothing stopping you from extending `StringConstraint` and overriding `check` to taste:

```PHP
class MyStringConstraint extends StringConstraint
{
    /**
     * {@inheritDoc}
     */
    public function check($element, $schema = null, JsonPointer $path = null, $i = null)
    {
        // Verify a regex pattern
        if (isset($schema->pattern) && !preg_match('#' . str_replace('#', '\\#', $schema->pattern) . '#ui', $element)) {
            $this->addError($path, "Does not match the regex pattern " . $schema->pattern, 'pattern', array(
                'pattern' => $schema->pattern,
            ));
        }
       else {
           parent::check($element, $schema, $path, $i);
       }
        
    }
```

Admittedly that's probably more duplicated code than needs to happen; it might be nice if the base StringConstraint class had a helper method for constructing the final pattern string. If you wanted to open a PR that adds that I would support it.

Hope that helps.

**Comment by DannyvdSluijs** [comment]
@markomanninen in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.
