### ISSUE TITLE
Validation of JSON-Schema

### ISSUE THREAD

**Issue by o5** [justinrainbow/json-schema#353]
Am I missing something or there is not validation of schema itself? I don't know if it is possible, but it would be nice to throw something like json-schema parse error.

For json-schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
      "id": {
        "type": "number"
      },
      "type": "object"
    }
}
```

I've expected similar error message as I got from [jsonschemavalidator.net](http://www.jsonschemavalidator.net): 

```
Unexpected token encountered when reading value for 'type'. Expected StartObject, got String. Path 'properties.type', line 7, position 22.
```

**Comment by shmax** [comment]
I don't think the library has that built-in, but if you want to set that up in your own code you might have a look at the files in `/tests/fixtures` for some ideas; they appear to be validation schemas for the different draft specs.

**Comment by mathroc** [comment]
@o5 you can validate it yourself using the validator and the [json-schema schema](http://json-schema.org/draft-04/schema)

```php
$validator->validate(json_decode($schema), (object)['$ref' => 'http://json-schema.org/draft-04/schema']);
```

**Comment by o5** [comment]
Hello @mathroc,

I'm sorry for my late response. I'm trying to use validate feature:

```php
$schema = json_decode('{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"properties": {
		"id": {
			"type": "number"
		},
		"type": "object"
	}
}');

$validator = new Validator();
$validator->validate(
    $schema,
    (object) ['$ref' => 'http://json-schema.org/draft-04/schema#'],
    Constraint::CHECK_MODE_VALIDATE_SCHEMA
);
```

I'm expecting some error like *Error parsing schema*, but none given. Am I missing something?

**Comment by erayd** [comment]
>I'm expecting some error like Error parsing schema, but none given. Am I missing something?

You're asking it to validate the schema, and the schema is valid (it's the official draft-04 meta-schema). That isn't an error condition.

`$schema` is not a valid schema, but you are presenting it as the document to be validated against the official spec, not as the schema. If I'm correctly understanding what you're doing there, the result should be a validation error.

**Comment by o5** [comment]
@erayd:

Sorry, the snippet should be this :)

```php
$schema = json_decode('{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "id": {
            "type": "number"
        },
        "type": "object"
    }
}');

$value = (object) [
    'id' => 10,
];

$validator = new Validator();
$validator->validate($value, $schema, Constraint::CHECK_MODE_VALIDATE_SCHEMA);
```

**Comment by erayd** [comment]
@o5 Thanks - have reproduced this, and it does look like there's a bug somewhere. I'll get see if I can nail down the root cause today.

**Comment by erayd** [comment]
Found it - there's an issue with object validation where `"properties"` is not defined, and `"additionalProperties"` is present.

Fixing this bug causes parts of the draft-04 test suite to fail - it looks like there is another bug that this one was hiding...

**Comment by erayd** [comment]
...and the second bug is a result of fixing the first bug.

The root cause is the library attempting to use the same variable for two different things:
 * As the schema definition of an entire object; and
 * As the list defined by `"properties"` in an object's schema.

I'll push a combined fix for both bugs hopefully sometime today (it's 12:22pm here).

**Comment by erayd** [comment]
Both fixed in #411. This PR will be backported to [5.x.x](https://github.com/justinrainbow/json-schema/tree/5.x.x) once it's merged.

**Comment by o5** [comment]
I would like to confirm that it works in version **5.2.1**. Thank you!

**Comment by erayd** [comment]
Most welcome :-).
