### ISSUE TITLE
ConstraintError throws unresolvable InvalidArgumentException

### ISSUE THREAD

**Issue by erayd** [justinrainbow/json-schema#369]
`ConstraintError` needs to either add a `use` line, or qualify the exception.

**Comment by shmax** [comment]
Whoops. Will fix.

**Comment by erayd** [comment]
Already done it - see PR #370 :-)

**Comment by erayd** [comment]
Have also added a test for this to #366.

**Comment by shmax** [comment]
Lovely, thank you!

**Comment by bighappyface** [comment]
Will be official in 6.0.0
