### ISSUE TITLE
successfull validation with empty schema

### ISSUE THREAD

**Issue by irodushka** [justinrainbow/json-schema#37]
If I pass "" as schema to $validator->check() $validator->isValid is always true.
If I pass incorrect path to $retriever->retrieve it always returns empty schema with id only property, and it always validates any json.

**Comment by bighappyface** [comment]
Closing due to age. Please re-open if necessary

**Comment by o5** [comment]
Am I missing something or there are not also validation of schema itself? I don't know it is possible, but I would be nice to throw something like json-schema parse error.

For json-schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
      "id": {
        "type": "number"
      },
      "type": "object"
    }
}
```

I was expected similar error message as I got from [jsonschemavalidator.net](http://www.jsonschemavalidator.net): 

`Unexpected token encountered when reading value for 'type'. Expected StartObject, got String. Path 'properties.type', line 7, position 22. `
