### ISSUE TITLE
ValidationException has a different behaviour from non-validation exception

### ISSUE THREAD

**Issue by CMCDragonkai** [justinrainbow/json-schema#387]
When enabling `CHECK_MODE_EXCEPTIONS`, on the first error the exception will be thrown and you only get 1 error. But if you don't enable it, then you get all the errors in 1 array.

There are times where you want to be interrupted on the very first error, but there are times where you want to capture all errors.

Shouldn't the choice be available to both styles? Right now if I prefer to receive an exception, I cannot get all validation errors.

**Comment by erayd** [comment]
This is a deliberate design choice. The intention is to halt validation immediately upon encountering an error.

If you just want to know whether the document is valid, but don't care about the errors, then it can be a significant performance improvement, as you don't need to keep processing a document after you've already answered the validity question.

If you wish to throw an exception that includes all the errors, you can easily do so using something like this:
```PHP
$v->validate($data, $schema);
if (!$v->isValid()) {
    throw new \Exception(json_encode($v->getErrors());
}
```

IMO adding a flag for 'exception-with-all-errors' is unnecessary, as your stated goal is already easily achievable in three lines.

**Comment by CMCDragonkai** [comment]
Ok.
