### ISSUE TITLE
PHP User Experience of using JSON-Schema

### ISSUE THREAD

**Issue by CMCDragonkai** [justinrainbow/json-schema#388]
Currently for an inline schema, it must be all objects. Since PHP mostly associative arrays to represent objects in Javascript, why not allow associative arrays to be valid schemas?

I always use the `Constraint::CHECK_MODE_TYPE_CAST` right now, and this is great since I always run `json_decode(..., true)`. But I find it very verbose to have to type coerce all my validator schemas as `(object) [...]`.

**Comment by erayd** [comment]
That's not a bad idea. Thanks for the suggestion - I will implement this :-).

**Comment by shmax** [comment]
👍 I like that idea a lot. All my schemas are simple PHP arrays, and it's always vaguely bothered me that I have to convert them to objects.

**Comment by erayd** [comment]
Implemented in #389. Will backport to 5.2.0 once merged.

**Comment by erayd** [comment]
@bighappyface Can this issue be closed? The fix is merged in both [6.0.0-dev](https://github.com/justinrainbow/json-schema/tree/6.0.0-dev) and [5.2.0](https://github.com/justinrainbow/json-schema/tree/5.2.0).
