### ISSUE TITLE
Support for Accented characters in Email

### ISSUE THREAD

**Issue by abhijit-gaonkar** [justinrainbow/json-schema#397]
We should allow unicode characters in email by adding filter FILTER_FLAG_EMAIL_UNICODE (this flag is available only in PHP 7x)

https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/FormatConstraint.php#L108

**Comment by erayd** [comment]
Excellent idea - I will add this. Thanks for the suggestion :-)

**Comment by erayd** [comment]
Added in #398. Note that this flag is only available in PHP >= 7.1.0.

**Comment by erayd** [comment]
@bighappyface Can this issue be closed? The fix is merged in both [6.0.0-dev](https://github.com/justinrainbow/json-schema/tree/6.0.0-dev) and [5.2.0](https://github.com/justinrainbow/json-schema/tree/5.2.0).
