### ISSUE TITLE
Schema Validation for more than one type

### ISSUE THREAD

**Issue by hkatkam2017** [justinrainbow/json-schema#399]
Version = 1.6
Because of the legacy systems, we are not in a position to upgrade to latest version.
It does appears validation is not working in the scenarios where json property can be either 1) string or null
2) object or null 3) array or null.

Please find the example below. Not sure if there is some thing I am missing here. Any help will be greatly appreciated.

### Schema

```
  "description": {
    "type": [
      "string", 
      null
    ]
  }
```

### Json

```
  "products": [
    {
      "Id": 1,
      "description": "description goes here",
    }
  ]
```

**Comment by handrews** [comment]
`null` (the literal) is not a valid type.  `"null"` (the string) is a valid type, indicating that the value should be `null` (the literal).  It's a bit confusing, but all types are given as strings.

**Comment by hkatkam2017** [comment]
@handrews , cheers mate. problem solved.
