### ISSUE TITLE
Bugfix Branch

### ISSUE THREAD

**Issue by erayd** [justinrainbow/json-schema#404]
@bighappyface Now that `6.0.0-dev` looks set to merge into `master` in the near future, could we please have a `5.x.x` branch with e3c9bccdc38bbd09bcac0131c00f3be58368b416 as the `HEAD`? That way there will still be somewhere to submit bugfix / backport PRs against for 5.x.

**Comment by bighappyface** [comment]
Done: https://github.com/justinrainbow/json-schema/tree/5.x.x

**Comment by erayd** [comment]
Perfect - thanks :-)
