### ISSUE TITLE
Should Validator::validate()  also use arrayToObjectRecursive() on $value?

### ISSUE THREAD

**Issue by shtrom** [justinrainbow/json-schema#410]
In the ilk of #408, I am wondering whether `Validator::validate()` should also transform the `$value` it needs to validate to an object.

**Comment by erayd** [comment]
@shtrom It doesn't need to, because it can deal with associative arrays internally already. This is what `CHECK_MODE_TYPE_CAST` is for.

**Comment by shtrom** [comment]
Right. I was just passing an invalid JSON file... Sorry about the noise (:
