### ISSUE TITLE
issues triage

### ISSUE THREAD

**Issue by mathroc** [justinrainbow/json-schema#423]
I just take a look at some issues, here are some that I think can be closed (because they are either solved or invalid)  :

* #90 
* #176
* #177
* #195

this one should be tested to confirm if it’s still an issue : #89

**Comment by erayd** [comment]
I have tested #83 against 2d404b8035f8dc349ebbf6b9281d173473a7c871, and it seems resolved:

```
steve@neith /tmp $ ~/dev/json-schema/bin/validate-json data.json schema.json 
JSON does not validate. Violations:
[[2].thing] String value found, but an integer is required
[[2].thing] String value found, but a boolean is required
[[2]] Failed to match exactly one schema
```

**Comment by bighappyface** [comment]
@mathroc thanks
