### ISSUE TITLE
UriResolver::generate does not properly reconstruct URLs with a query fragment.

### ISSUE THREAD

**Issue by TimothyBJacobs** [justinrainbow/json-schema#424]
The `UriResolver` appends the fragment to the path without a leading `?`  causing an incorrect URL.
Ex: `http://example.org/?rest=/route` becomes `http://example.org/rest=/route`. 

https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Uri/UriResolver.php#L65

Happy to submit a patch.

**Comment by erayd** [comment]
Thanks for the bug report! This is fixed in #425. I will backport the fix for 5.2.2 once it's merged.

**Comment by TimothyBJacobs** [comment]
Fantastic, thank you!

**Comment by bighappyface** [comment]
Closed with #425
