### ISSUE TITLE
How do you resolve schema recursively? like RefResolver@resolve

### ISSUE THREAD

**Issue by chocopowwwa** [justinrainbow/json-schema#427]
Hi, how do you resolve schema recursively in version 5 like you do in
https://github.com/justinrainbow/json-schema/blob/2.0.5/src/JsonSchema/RefResolver.php#L50

i do try SchemaStorage@refReolve but it doesn't resolve the schema reccursively ( it still has $ref somewhere in the schema )

**Comment by erayd** [comment]
Could you please clarify what you are trying to achieve? You should not need to manually resolve schema references; they are resolved automatically as needed.

**Comment by gitetsu** [comment]
Hi, @erayd.
As for me, I use '$ref resolved' schema in production to avoid runtime resolution.
Before deployment, I generate resolved one.
Currently, I check out old RefResolver class.

**Comment by chocopowwwa** [comment]
@erayd 
i just want to resolve all the schema and pass it to https://github.com/Leko/php-json-schema-faker

**Comment by mathroc** [comment]
I think Leko/php-json-schema-faker should be the only supporting references (if it does not already)

because if your schema is recursive you won't be able to fully resolve it

**Comment by chocopowwwa** [comment]
ok so the conclusion, there's no way to produce fully solved references schema in the newer v3 or up,
if you need one, you can implement the RefResolve class
