### ISSUE TITLE
x-nullable extension support

### ISSUE THREAD

**Issue by El-Sam** [justinrainbow/json-schema#434]
Hi, I'm using the  *x-nullable* extension for so many of my properties like so : 

```json
"archived": {
   "type": "integer",
   "x-nullable": true
 },
```

And I have trouble validating these properties when they're null against the schema.

Can you please support this extension ? I need it.

**Comment by erayd** [comment]
What is the purpose of `x-nullable`? It's not part of the JSON Schema specification.

Is there any reason why you cannot simply use `"type": ["integer", "null"]`? This is the correct (i.e. standards-compliant) way of defining a type restriction on a property while also allowing it to be `null`.

**Comment by El-Sam** [comment]
I'm using Swagger 2 to define my API, and it lacks support for nullable values and cannot use `"type": ["integer", "null"]` so they come up with the the extension x-nullable (along other extensions that start with x-) see [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#specification-extensions).

**Comment by erayd** [comment]
`x-nullable` is not listed on that page. Do you have a link to a spec definition for it?

**Comment by El-Sam** [comment]
please take a look at these links : 
[specs allow custom properties as long as they start with `x-`](https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#vendor-extensions)
and this [add "null value support" in spec](https://github.com/OAI/OpenAPI-Specification/issues/229)

**Comment by erayd** [comment]
I've now read those links in their entirety, and done a bit of further research. Unfortunately, based on what I've seen, `x-nullable` does not belong in this library, and my position is firmly *against* adding support for it.

My reasons for objecting to adding this are as follows:

 * Swagger and JSON Schema are not the same thing, nor is one a superset of the other - they are different and divergent standards.
 * This library is a JSON Schema validator, not a Swagger validator. While some Swagger definitions may also be valid JSON Schema, that is not always the case, and assuming you can always validate a Swagger definition with a JSON Schema validator is both incorrect and dangerous.
 * Even within Swagger, `x-nullable` is not part of the official spec, nor is it formally defined anywhere - it seems to simply be one of multiple competing conventions to solve the missing-null problem.
 * Swagger seems to be working (albeit slowly) to resolve this issue internally, so once that's done it should cease to be a problem.
 * Adding non-spec keywords to solve problems in somebody else's project is the start of a very slippery slope I do not wish to go down. It seems like a fundamentally bad idea.

If you wish to persist with using this library to validate your definitions *anyway*, then IMO the best approach to this would simply be to pre-process the Swagger definition prior to validation. A simple recursive function to replace all instances of `"type": "whatever", "x-nullable": true` with `"type": ["whatever", "null"]` prior to validation should do the trick nicely, and does not require any changes to the validator.

**Comment by El-Sam** [comment]
Thank you for replying and the effort you made.

Just to clarify something, I don't use JSON Schema to validate my Swagger definition, well not willingly, it's the library I'm using to test my swagger definition that uses JSON Schema to validate Swagger schema.

Anyway, thank you again for the effort. I guess I gotta find another solution for this problem.

**Comment by erayd** [comment]
> ...it's the library I'm using to test my swagger definition that uses JSON Schema to validate Swagger schema.

Ouch! I don't envy you that one. I wish you all the best with finding a solution to your problem :-).

**Comment by El-Sam** [comment]
Thank you.

**Comment by erayd** [comment]
One thing you might wish to try - if the library you're using to validate your swagger definitions is open to contributions, it may be worth submitting a PR for that project to pre-process definitions prior to validation. If you want to keep using the same validation library, that's probably the easiest way to resolve things, avoids the need to maintain your own fork of it, and will help other users of that project.

Another option could be to switch to a different Swagger validation library.

**Comment by El-Sam** [comment]
I'm looking into it to see if I can introduce this change. 

here's the situation : 

- I cannot switch to another Swagger validation library because this is the only one, in fact there's another one but it uses Swagger and Behat and I don't use the latter.

- Also the library's owner isn't really helpful and shuts down any opened issue without leaving room for discussing or further questions.

- I don't have much time left :(


Yep, this is how it's going for me, great, isn't it ?
