### ISSUE TITLE
PHPDoc Cleanup

### ISSUE THREAD

**Issue by erayd** [justinrainbow/json-schema#438]
The current codebase lacks useful PHPDoc comments in many places, and needs a significant overhaul.

I would like to propose the following:
 * Every class and interface must have:
    * A short description of what the class
    * A long description explaining the class in more depth if appropriate
    * `@package justinrainbow/json-schema`
    * `@license MIT`
 * Every method must have:
    * A short description of the method
    * A long description explaining the method in more depth if appropriate
    * `@api` if the method is part of the [official public API](https://github.com/justinrainbow/json-schema/issues/392#issuecomment-288608592)
    * `@param <type> <name>` for all parameters; mixed-type params should be stated as `mixed`
    * `@return <type> [description]` for all methods which return a value. The return description should be present for any method where the return value is not self-evident from reading the method description.
 * Every abstract method signature should be documented as per fully-defined methods.
 * Every property must have:
    * `@var <type> <description>`
 * Every class constant must have a PHPDoc description, but should not contain any @tags.

I would also like to add a config file for `sami/sami`, and delete the old documentation directory - `docs` hasn't been touched in 5+ years, and doesn't contain anything of substance anyway. Sami should *not* be added as a dev-time dependency, as it requires PHP >= 7.0 to run.

Before I go ahead and sink time into this, does what I've outlined above sound reasonable?

Finally, if someone else is keen and has the time, feel free to jump in with a PR. I'm quite happy to do all the work on this, but documentation isn't my favourite activity, so if you happen to harbour a secret passion for it...

**Comment by bighappyface** [comment]
Sounds good to me

**Comment by shmax** [comment]
Sure, sounds good. I recently went through the whole process of using Sami to deploy its output to github pages, so I can help with travis if you'd like to do something similar.

**Comment by erayd** [comment]
@shmax That would definitely be nice if you're willing to do that again here :-).

**Comment by shmax** [comment]
Can do, but we'll need someone with access to the settings to configure github pages. @bighappyface?

**Comment by erayd** [comment]
Oh. If that needs admin access, then we're SOL on that front, because @bighappyface isn't, and @justinrainbow is gone.

**Comment by shmax** [comment]
Ugh. Well, we could always deploy it somewhere else. Any ideas?

**Comment by erayd** [comment]
I have a webserver on DigitalOcean we can put this on, if that's a viable option. It has various PHP websites on it, but nothing too heavy-duty, and there's a fair bit of spare capacity on there.

**Comment by shmax** [comment]
That could work. We don't even need PHP; just anything that can host static pages. I've only deployed to github, but I've been meaning to learn how to do other destinations, so this will be interesting. Should this work happen independently of your PHPDoc stuff, or in concert?

**Comment by erayd** [comment]
Independently I reckon. Stand by, and I'll add a user account to the server for you.

**Comment by shmax** [comment]
Take your time, I'm off to bed. Should be able to dabble with this a bit on Sunday.

**Comment by erayd** [comment]
Already done it :-). See Slack.

**Comment by bighappyface** [comment]
^^ nvm

**Comment by erayd** [comment]
What do you guys think should be done with the @author tags? Are they still relevant, noting how many people have contributed to this library over the years?

If we keep them, how do we determine who is tagged - do we just tag everyone who has current code in the file where the tag appears, and not care about the list being huge?

Personally, I think it makes more sense to have a CONTRIBUTORS or AUTHORS file in the repo root that lists contributors, and remove the @author tags completely, as they get unweildy when there are a large number of contributors.

**Comment by erayd** [comment]
Progress checklist for PHPDoc comments on public API entities:

## Methods
-  [ ] `Validator::__construct` - create a validator instance with a custom factory
-  [ ] `Validator::validate` - main entry point for validation
-  [ ] `Validator::check` - BC alias of `validate` (pre-`5.0.0`), does not pass `$value` by reference
-  [ ] `Validator::coerce` - BC alias of `validate` (pre-`5.0.0`), sets `CHECK_MODE_COERCE_TYPES`
-  [ ] `Validator::getErrors` - get array of validation errors
-  [ ] `Validator::numErrors` - get number of validation errors
-  [ ] `Validator::getErrorMask` - get the error categories 
-  [ ] `Validator::isValid` - get overall validation status
-  [ ] `Validator::reset` - reset validation status
-  [ ] `Factory::__construct` - create a `Factory` instance with custom `SchemaStorage`, `UriRetriever` or `$checkmode`
 - [ ] `Factory::setConfig` - overwrite `$checkMode`
 - [ ] `Factory::getConfig` - get `$checkMode` or a filtered subset
 - [ ] `Factory::addConfig` - add options to `$checkMode`
 - [ ] `Factory::removeConfig` - remove options from `$checkMode`
 - [ ] `Factory::getSchemaStorage` - get the current `SchemaStorage` instance
 - [ ] `Factory::getUriRetriever` - get the current `UriRetriever` instance
 - [ ] `SchemaStorage::__construct` - create a `SchemaStorage` instance with custom `UriRetriever` or `UriResolver`
 - [ ] `SchemaStorage::addSchema` - add a schema to the storage instance by identifyng URI
 - [ ] `SchemaStorage::getSchema` - get a schema from the storage instance by identifying URI
 - [ ] `UriResolver::resolve` - resolve a URI to absolute
 - [ ] `UriRetriever::retrieve` - retrieve & return a decoded JSON schema object

## Class Constants
 - [ ] `Validator::SCHEMA_MEDIA_TYPE` - official JSON schema media type
 - [ ] `Validator::ERROR_*` - error categories (bitmask)
 - [ ] `Constraint::CHECK_MODE_*` - validation options (bitmask)

## Class Properties
 - [ ] `Validator::$factory` - dependency injection, state & instance management

## Data Formats
 - [ ] The array data returned by `Validator::getErrors()`

## Exceptions
 - [ ] `InvalidArgumentException`
 - [ ] `InvalidConfigException`
 - [ ] `InvalidSchemaException`
 - [ ] `InvalidSchemaMediaTypeException`
 - [ ] `InvalidSourceUriException`
 - [ ] `JsonDecodingException`
 - [ ] `ResourceNotFoundException`
 - [ ] `RuntimeException`
 - [ ] `UnresolvableJsonPointerException`
 - [ ] `UriResolverException`
 - [ ] `ValidationException`

**Comment by DannyvdSluijs** [comment]
Looking at this issue I've found a couple of things which might impact the original report.
- Sami has archived as of February 2019 (over 5 years ago) 
- Back in 2017 PHP 7.2 was not released and `@param` and `@return` were the default way of documenting the functions etc. Since the language and eco system have evolved with parameter and return types as well as tools like PHPStan and Rector.
- With regards to the `@author` tags, I'm not a big believer of code owners of individual files but would rather see the whole as a community effort, with the commit history to show for it. In addition the library is under [MIT license](https://github.com/justinrainbow/json-schema/blob/master/LICENSE) and therefor the claiming of being an author has no value as well (to my knowledge).
> A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
- We now know that time available from the maintainers is limited (no judgment here, just pointing out an observation)


With all of the above I would opt for dropping the issue and spend time more wisely.

**Comment by erayd** [comment]
@DannyvdSluijs Sounds sensible; I agree with your opinion on this.
