### ISSUE TITLE
Add support for json_decode($data, true)

### ISSUE THREAD

**Issue by pleonasm** [justinrainbow/json-schema#44]
The entire library right now only works if the calling code passes in both the schema and the data as it has been returned from json_decode($data).  It would be helpful for projects to be able to pass in the data and/or schema if it comes from a json_decode($data, true) call.

I'm thinking the simplest fix for this is to claim the mostly defunct Validator::CHECK_MODE_\* constants and either use CHECK_MODE_TYPE_CAST or a new constant to allow the calling code to indicate which format the data is coming in.

It would be fairly trivial to then convert the data to the expected types for validation so not much of the actual validation code has to change.

**Comment by neural-wetware** [comment]
I have application code which decodes JSON in the array style, but have to decode it again to validate against the schema. I'm in a situation where I have to either decode twice or rewrite the app code to use object style.

Is this a compelling enough case for adding this feature? Consider that the JSON structures can potentially be quite large and rewriting application code can be costly.
