### ISSUE TITLE
Changing the resolution base via 'id' does not work properly

### ISSUE THREAD

**Issue by erayd** [justinrainbow/json-schema#447]
Per issue #446. See below test case:

```PHP
$data = json_decode(<<<'eot'
{
    "propertyOne": "blue"
}
eot
);

$base = json_decode(<<<'eot'
{
    "id": "schema.json",
    "properties": {
        "propertyOne": {
            "$ref": "propertyOne.json"
        }
    }
}
eot
);

$validator = new \JsonSchema\Validator();
var_dump($validator->validate($data, $base));
```

@bighappyface Could you please mark this as blocking for 6.0.0? I need to stare at the code some more, but at first look this may require significant refactoring of the `$ref` code.

**Comment by erayd** [comment]
@shmax Have you had anything to do with with the ref processing when the scope has been changed? Some insight into how this is intended to work would be handy and would save a lot of time tracing stuff. No worries if not.

The tests in `draft4/refRemote.json` all pass, including the ones with a nested scope change (e.g. `folderInteger.json`), but the logic that actually achieves this isn't clear, and it's not covering all cases. In the test code above, the resolution base gets completely dropped somewhere along the line, despite being explicitly set in the base schema.

**Comment by shmax** [comment]
No, not only was that before my time, but I never really totally figured out how to get $ref functionality working in my own code; I had to resort to overriding the UriResolver and just cheeseballing the resolve method. I looked over this issue, but I think I'm a bit out of my depth; I don"t even know what a "behat" is. I'll see if I can get caught up a bit more this weekend.

**Comment by erayd** [comment]
Bugger. Will get to tracing stuff then. Thanks anyway :-).

**Comment by erayd** [comment]
For what it's worth, this bug has nothing to do with Behat. Behat just happens to depend on this validator, and @dkarlovi happened to find the bug while using Behat.

**Comment by shmax** [comment]
Gotcha. I'll load up his sample app tomorrow and see if I can make any sense of it.

**Comment by erayd** [comment]
No need, unless you're curious - the test case at the top of this thread reproduces the bug using only the json-schema validator.

**Comment by dkarlovi** [comment]
Behat is irrelevant here, I used it to replicate the bug the only way I knew how. :)

**Comment by mdeboer** [comment]
Same problem here and I have no clue how to get it to work except for writing my own resolver I guess. Can't we just add a getter/setter for the base path for the resolver? This would make all relative file references relative to that path.

I can probably cook something up but I'm not sure if it would break stuff as this is a bug apparently.

**Comment by erayd** [comment]
@mdeboer This is definitely a bug. I will fix it.

Regarding your suggestion of a base path setter... what purpose would this serve? The spec already defines the `id` keyword as filling this role; it's just the implementation which is broken.

**Comment by mdeboer** [comment]
Alright, awaiting the fix then 👍

**Comment by erayd** [comment]
@mdeboer See #448. Assuming code review is OK, I will backport this fix to 5.x.x after merge.

**Comment by erayd** [comment]
Have rebased this on #449 - the latest version of php-cs-fixer introduces some dangerous changes, and also causes CI failures on travis. #449 should be merged prior to this PR.

**Comment by dkarlovi** [comment]
@erayd is this actually backward compatible, will it even land in 5.x?

**Comment by erayd** [comment]
@dkarlovi Yes. I very deliberately implemented it in a manner that could be backported to 5.x.x without breaking anything.

**Comment by dkarlovi** [comment]
@erayd great, looking forward to seeing it released, thanks!

**Comment by erayd** [comment]
@dkarlovi Now backported for 5.2.2 - see PR #450.
