### ISSUE TITLE
Experiencing "Error: JSON schema not found at file://"

### ISSUE THREAD

**Issue by danielbachhuber** [justinrainbow/json-schema#451]
When updating our dependencies from 5.2.1 to 5.2.2 today, we experienced this error:

```
Error: JSON schema not found at file://
```

Ref https://github.com/wp-cli/wp-cli/pull/4393 and https://travis-ci.org/wp-cli/wp-cli/jobs/282809129

Let me know what situational details I can provide to help reproduce it. `justinrainbow/json-schema` is a dependency of Composer, which we use within our application.

**Comment by erayd** [comment]
Thanks for the heads-up. Could you please let me know the URI of the schema that's triggering the error, and how that schema is loaded? Also, does that schema contain an id, and / or any relative $ref?

**Comment by danielbachhuber** [comment]
> Could you please let me know the URI of the schema that's triggering the error, and how that schema is loaded? Also, does that schema contain an id, and / or any relative $ref?

I'm not entirely sure, but this looks like it could be it: https://github.com/composer/composer/blob/af519de0de087acb11450c2c10225377c8a909ff/res/composer-repository-schema.json

From https://github.com/composer/composer/search?utf8=%E2%9C%93&q=json-schema&type=

I also see https://github.com/composer/composer/blob/e12e0335a4d467878093fc76e3dea592ff3e1ce3/src/Composer/Json/JsonFile.php#L150

**Comment by erayd** [comment]
@danielbachhuber 

I'm having difficulty reproducing this. I've done the following:
 1. clone `wp-cli/wp-cli` locally into `/tmp/wp-cli`
 2. Run `composer install`
 3. Update `justinrainbow/json-schema` to 5.2.2
 4. Inside `/tmp/wp-cli`, run `./bin/wp package install danielbachhuber/wp-cli-reset-post-date-command`

Step 4 (i.e. the first failing travis test) seems to work perfectly without error.

Are you able to provide a minimal test case, or instructions to reproduce?

**Comment by erayd** [comment]
```
steve@neith /tmp/wp-cli $ ./bin/wp package install danielbachhuber/wp-cli-reset-post-date-command
Installing package danielbachhuber/wp-cli-reset-post-date-command (dev-master)
Updating /home/steve/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Analyzed 441 packages to resolve dependencies
Analyzed 50 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: danielbachhuber/wp-cli-reset-post-date-command:dev-master b8fee09
 - Installing danielbachhuber/wp-cli-reset-post-date-command (dev-master b8fee09)
Writing lock file
Generating autoload files
---
Success: Package installed.
```

**Comment by danielbachhuber** [comment]
I've triggered a build to reproduce: https://github.com/wp-cli/wp-cli/pull/4396

**Comment by danielbachhuber** [comment]
I suspect I know what the issue is (now that I've managed to compare 5.2.1 and 5.2.2).

WP-CLI is built and distributed as a Phar archive. As such, [prepending `file://` to a path is erroneous](https://github.com/justinrainbow/json-schema/compare/5.2.1...5.2.2#diff-8046bc5ad7d70824500d1207ec5ca4f9R79) because the file protocol inside a Phar is `phar://`.

I don't know enough about the json-schema codebase to offer an alternative at this point :/

**Comment by erayd** [comment]
@danielbachhuber It shouldn't be prepending `file://` to anything unless there's no protocol provided at all. If `phar://` is present in the base URI, then it will be left alone and relative URI will also be resolved as `phar://`.

I'll investigate to see if there's a possibility that something might be coming through from a phar archive that does *not* have a `phar://` URI prefix on the base, as that would certainly trigger the issue.

**Comment by erayd** [comment]
I think it's caused by [this](https://bugs.php.net/bug.php?id=52769). Nonsensical behavior, and apparently not a bug (although noting that phar archives are supposed to be filesystem-equivalentl it sure seems like a bug to me). I'll refactor this code to avoid the use of `realpath()`.

**Comment by erayd** [comment]
@danielbachhuber This is fixed in #455.

**Comment by danielbachhuber** [comment]
👌 Thanks for your help with this, @erayd

**Comment by erayd** [comment]
No problem. Thanks for reporting the issue :-).

I'll update this issue once the fix is merged (@bighappyface needs to do that part). It'll go to 6.0.0-dev first, then backported for v5.2.5.

**Comment by erayd** [comment]
@danielbachhuber Now merged in 6.0.0-dev, and backported for 5.2.5 in #457.

**Comment by danielbachhuber** [comment]
👍 Looking forward

**Comment by bighappyface** [comment]
https://github.com/justinrainbow/json-schema/releases/tag/5.2.5

**Comment by danielbachhuber** [comment]
Created a build in https://github.com/wp-cli/wp-cli/pull/4433

**Comment by danielbachhuber** [comment]
5.2.5 fixes our issue. Thanks for your help @erayd @bighappyface :)
