### ISSUE TITLE
Release v5.2.3 is based on the wrong branch

### ISSUE THREAD

**Issue by erayd** [justinrainbow/json-schema#454]
The v5.2.3 release was based on the master branch, instead of 5.x.x.

@bighappyface Any chance you could nuke 5.2.3 and roll a 5.2.4 release from the 5.x.x head? That's where 5.2.3 was supposed to point anyway, and incrementing the number (rather than re-releasing 5.2.3) will avoid downstream caching issues.

**Comment by bighappyface** [comment]
![Grumpy tag](https://i.imgflip.com/1x25oq.jpg)

https://github.com/justinrainbow/json-schema/releases/tag/5.2.4

**Comment by erayd** [comment]
@bighappyface Thanks! That was extremely fast :+1:.
