### ISSUE TITLE
integer shouldn't match -123424

### ISSUE THREAD

**Issue by ke-liang** [justinrainbow/json-schema#461]
data is like ""created": -34245",
and json schema is 
`"created": {
      "type": "integer",
      "pattern": "^15[0-9]{8}$"
    },`

that's should be an exception! but validate pass!

**Comment by erayd** [comment]
`-34245` is a valid integer - a pass result is correct. This is not a bug.

The `pattern` keyword only applies to strings; ignoring it when validating integer values is the intended behavior, and is in accordance with the spec.

**Comment by erayd** [comment]
If you are trying to limit your integer values to within a certain range, the correct way to do that is with the `minimum` and `maximum` keywords. I'm your case, that would mean a minimum of 1500000000 and a maximum of 1599999999.

**Comment by ke-liang** [comment]
Thanks，you're right！
