### ISSUE TITLE
Support for php7

### ISSUE THREAD

**Issue by leroy0211** [justinrainbow/json-schema#463]
When will be there support for PHP 7? 

Because PHP already flagged PHP 5.5 as End Of Life. And php 5.6 will be End Of Life in January 2019

**Comment by bighappyface** [comment]
See the Travis build configs. PHP 7 and 7.1 are included.

**Comment by leroy0211** [comment]
That's weird, when I try to require this package, it will throw a php version error that the latest version allowed is `5.5.9`. Maybe there's something wrong with my environment, let me check that first.

**Comment by leroy0211** [comment]
That's weird, when I try to require this package, it will throw a php version error that the latest version allowed is `5.5.9`. Maybe there's something wrong with my environment, let me check that first.
