### ISSUE TITLE
Can't use recursive $ref

### ISSUE THREAD

**Issue by sirdawidd** [justinrainbow/json-schema#472]
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "license": {
      "name": "MIT"
    }
  },
  "servers": [
    {
      "url": "http://petstore.swagger.io/v2"
    }
  ],
  "paths": {
    "/pet/findByStatus": {
      "get": {
        "summary": "Finds Pets by status",
        "description": "Multiple status values can be provided with comma separated strings",
        "operationId": "findPetsByStatus",
        "tags": [
          "pets"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "required": true,
            "description": "Status values that need to be considered for filter",
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "available",
                  "pending",
                  "sold"
                ]
              },
              "default": "available"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/Pets"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Pets"
                }
              }
            }
          },
          "400": {
            "description": "Invalid status value"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "required": [
          "name",
          "photoUrls"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string",
            "example": "doggie"
          },
          "tag": {
            "type": "string"
          },
          "photoUrls": {
            "type": "array",
            "xml": {
              "name": "photoUrl",
              "wrapped": true
            },
            "items": {
              "type": "string"
            }
          }
        }
      },
      "Pets": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Pet"
        }
      }
    }
  }
}
Following schema validation produce
JsonSchema\Exception\UnresolvableJsonPointerException : File: internal://provided-schema/ is found, but could not resolve fragment: #/components/schemas/Pet

but it will work when I will change

>  "schema": {
>                   "type": "array",
>                   "items": {
>                     "$ref": "#/components/schemas/Pet"
>                   }

without using ref to "$ref": "#/components/schemas/Pets"

Seems when there is $ref which follows to next $ref current solutions is not working.

**Comment by erayd** [comment]
Could you please edit the issue post to put that code inside a ``` block? It's rather annoying to read without the proper indentation.

**Comment by erayd** [comment]
OK, have reformatted it below:
```JSON
{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "Swagger Petstore",
        "license": {
            "name": "MIT"
        }
    },
    "servers": [
    {
        "url": "http://petstore.swagger.io/v2"
    }
    ],
    "paths": {
        "/pet/findByStatus": {
            "get": {
                "summary": "Finds Pets by status",
                "description": "Multiple status values can be provided with comma separated strings",
                "operationId": "findPetsByStatus",
                "tags": [
                    "pets"
                ],
                "parameters": [
                {
                    "name": "status",
                    "in": "query",
                    "required": true,
                    "description": "Status values that need to be considered for filter",
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": [
                                "available",
                            "pending",
                            "sold"
                            ]
                        },
                        "default": "available"
                    }
                }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Pets"
                                }
                            },
                            "application/xml": {
                                "schema": {
                                    "$ref": "#/components/schemas/Pets"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid status value"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Pet": {
                "required": [
                    "name",
                "photoUrls"
                ],
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64"
                    },
                    "name": {
                        "type": "string",
                        "example": "doggie"
                    },
                    "tag": {
                        "type": "string"
                    },
                    "photoUrls": {
                        "type": "array",
                        "xml": {
                            "name": "photoUrl",
                            "wrapped": true
                        },
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "Pets": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Pet"
                }
            }
        }
    }
}
```

**Comment by erayd** [comment]
What exactly are you passing to the validator as the schema? Because the document you have posted isn't actually a JSON schema, although it does contain some elements that can be parsed as such.

**Comment by sirdawidd** [comment]
Thanks I forgot to upload whole schema, I just did 
```
["items"]=>
  object(stdClass)#60 (1) {
    ["$ref"]=>
    string(24) "#/components/schemas/Pet"
  }
```
without Pet ;)
