### ISSUE TITLE
$data reference is not supported (compatibility with AJV)

### ISSUE THREAD

**Issue by thatside-zaraffa** [justinrainbow/json-schema#474]
It is not possible to use $data reference in schema like: 
```
"password": {
      "type": "string"
  },
  "passwordRepeat": {
      "type": "string",
      "const": { "$data": "#/register/password" 
}
```
AJV already supports this: https://github.com/epoberezkin/ajv/pull/289
Discussion on this feature in JSON Schema repo: https://github.com/json-schema-org/json-schema-spec/issues/51 #

**Comment by bighappyface** [comment]
PRs are welcome

**Comment by handrews** [comment]
Note that `$data` remains a controversial proposal and is not guaranteed to be added to the spec in the future.  We will probably resolve it one way or the other during draft-09 (so, probably six months to a year from now, depending on how long it takes us to finish the current draft-08 work).

**Comment by thatside** [comment]
A little bit more info here (for those who will read this issue): https://github.com/opis/json-schema/issues/1
