### ISSUE TITLE
Retrieve inline schema

### ISSUE THREAD

**Issue by alex-voigt** [justinrainbow/json-schema#492]
We are already using the library to validate data against a schema which works perfectly fine.

In addition we want to expose a schema that is split into pieces via references as a whole in an endpoint. Is there any way to return the inlined/resolved schema?

Looks like it was quite easy in an older version like we found [here](https://gist.github.com/graste/2fccfa710a375f93105d).

**Comment by erayd** [comment]
Unfortunately this isn't possible, as a schema cannot be fully dereferenced without risking infinite recursion (e.g. `{"$ref": "#"}`). The old behavior was actually a bug, and in violation of the spec, which says validator implementations may not infinitely recurse. The correct (and current) behavior is to dereference on-demand.

If you do need a fully-dereferenced copy of the schema for some reason, it's fairly simple to implement, but this library is not the right tool for the job. Note also that you'll have to trust the input schema not to be infinitely recursive, or else implement some kind of check to deal with it.
