### ISSUE TITLE
Replacing non-valid data with default value

### ISSUE THREAD

**Issue by siimots** [justinrainbow/json-schema#496]
If something is missing, then default value is added from schema. It works perfectly.

I can get non-valid fields from getErrors(), but how to replace non-valid data with default value?

```
foreach ($validator->getErrors() as $error) {
	echo $error['property'];
	echo $error['pointer'];
}
```

Sorry, PHP is not my main language.

**Comment by shmax** [comment]
It could be that the coercion functionality is what you need. Can you give an example of what you mean?

**Comment by siimots** [comment]
PHP file:

    use JsonSchema\Validator;
    use JsonSchema\Constraints\Constraint;

    $data = json_decode(file_get_contents('https://gis.ee/meri/data/ilmaandmed'));
    $validator = new JsonSchema\Validator;
    $validator->validate($data, (object)['$ref' => 'file://' . realpath('schema.json')], 
    Constraint::CHECK_MODE_COERCE_TYPES | Constraint::CHECK_MODE_APPLY_DEFAULTS);


Original file: https://gis.ee/meri/data/ilmaandmed
Schema file: https://gis.ee/meri/data/validate/schema.json
Validated file, with some default values added by json-schema script: https://gis.ee/meri/data/validate/

Example of getErrors():

    ilmateenistus[25].airpressure
    /ilmateenistus/25/airpressure
    Must have a minimum value of 920
    Integer value found, but a string is required
    Failed to match at least one schema

in validated result:

    "airpressure": 0

in schema:

    "airpressure": {
        "anyOf": [
           {
            "type": "number",
            "minimum": 920,
            "maximum": 1070
        },
        {
            "type": "string",
            "value": "-"
        }
    ],
        "default": "-"
    }


expected result is:

    "airpressure": "-"

**Comment by erayd** [comment]
@siimots You cannot do that - that's not how the `default` feature in this library is supposed to work.

It's supposed to insert missing values, but it will never alter existing data, regardless of whether or not that data is valid.

If override-type behaviour is essential for your use-case, then you will need to add this functionality yourself.

**Comment by shmax** [comment]
Also: what is the `value` property in your second `anyOf` block? Not familiar with that one...

**Comment by shmax** [comment]
By the way, this strikes me as sort of an odd use case, anyway. If "-" is meant to mean "not provided", then why bother with it? Just let the user go ahead and not provide it, and in your handler code you can do whatever logic you were going to do had "-" come through...

**Comment by siimots** [comment]
Thanks!

I guess `value` should be replaced with:  `"enum": ["-"]`

It is for some odd javascript graph library. It treats missing values as 0.

Is there any easy way to use these strings for accessing PHP array?

ilmateenistus[25].airpressure
/ilmateenistus/25/airpressure

**Comment by shmax** [comment]
In that case, your best bet is probably not to try to correct invalid values; the client sent them in good faith, and you are doing it a disservice by trying to correct it. Just let the exception happen and let them work out their own correction mechanism.

> Is there any easy way to use these strings for accessing PHP array?
> ilmateenistus[25].airpressure

Nothing easy comes to mind, but a few ideas:

1. use a [router](https://github.com/nikic/FastRoute) 
2. find some library that does this kind of thing (eg. https://github.com/peridot-php/object-path)
3. do something horrible with `eval` (not advised)

**Comment by erayd** [comment]
@siimots 
> Is there any easy way to use these strings for accessing PHP array?

Yes - the second one is a JSON path, and can be easily used as input to a recursive function that will do what you need.

[This](https://github.com/baacode/json-browser) library can do it out of the box for you already (`$browser->getValueAt('#/ilmateenistus/25/airpressure')`, or if you would like to write your own, take a look at the following methods within that library to get an idea of what is required:

 * Util::decodePointer (src/Util.php)
 * Context::setValueAt (src/Context.php)
 * Context::setValueAt (src/Context.php)

**Comment by siimots** [comment]
Thanks I will look into those.

**Comment by erayd** [comment]
@shmax peridot-php/object-path probably isn't suitable - the README doesn't mention compatibility with JSON pointers at all, which it would need. Otherwise the OP may run into escaping issues with `~`, `/` and `%` characters.

**Comment by shmax** [comment]
No argument, but he didn't explicitly say what purpose he had in mind, so I just googled and grabbed the first thing I found for illustrative purposes.  Your baacode project is no doubt a better solution...

**Comment by erayd** [comment]
@shmax
> Your baacode project is no doubt a better solution...

Really, it's probably overkill - it can do what he wants, but it also does a lot more than he needs - but as I'm familiar what the code for that one, it was the fastest way to find him an example that covered all the edge cases, that could give him some idea of what's required :-).
