### ISSUE TITLE
How to use the library without installing with composer?

### ISSUE THREAD

**Issue by ghost** [justinrainbow/json-schema#504]

**Comment by erayd** [comment]
@rumanpasha This library is intended to be installed using composer. Using it without composer is not a supported configuration.

If you wish to use it anyway, you will need to manually install the dependencies, and provide a suitable autoloader.

**Comment by shmax** [comment]
You don't need to use composer for this or any other package. Given that we know nothing about your restrictions, technology stack, or server permissions here are a few random ideas:

1. Sloppy approach: download the code, unzip it into a folder in your project. Update your [include_path](http://php.net/manual/en/ini.core.php#ini.include-path) accordingly 
2. If you're using git, you can learn about [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)
3. If what you object to is packagist and not composer itself, you can retrieve the code directly from github. Google around for it (eg. http://tech.osteel.me/posts/2015/08/10/how-to-use-the-fork-of-a-repository-with-composer.html)

As @eryad says you may or may not need to adjust your autoloader. If you have a fairly robust default loader it may be enough to just refer to the various classes via their namespaces.

**Comment by DannyvdSluijs** [comment]
@erayd this one can be closed directly as the issue reporter is now a ghost user (deleted profile)
