### ISSUE TITLE
Contents of 'vendor/autoload.php' file

### ISSUE THREAD

**Issue by rumanpasha** [justinrainbow/json-schema#511]
I'm trying to use this library without installing with composer, so i need the contents of vendor folder. can anyone please share me.

PS: Composer is not allowed to be installed in our server

**Comment by erayd** [comment]
The contents of this folder will vary depending on your PHP version. If you're not allowed composer on your server, just run 'composer install' on any machine with the same PHP version and then copy the entire `vendor` folder.

Alternatively, and probably easier if you're allowed, download [https://getcomposer.org/composer.phar](https://getcomposer.org/composer.phar), run `./composer.phar install`, then delete `composer.phar` again.

**Comment by curry684** [comment]
> just run composer install on any machine with the same PHP version

It's safer to use Composer's [platform settings](https://getcomposer.org/doc/06-config.md#platform) to lock dependencies to the production environment so you get full [dev/prod parity](https://12factor.net/dev-prod-parity) by running the same dependencies everywhere.

**Comment by rumanpasha** [comment]
@curry684, i can install composer in development server, but when i try to install the library with composer, the composer uses '/tmp' directory (using sys_get_temp_dir()), which is our server system temp folder , but the folder is not allowed to be accessed by libraries. how i config composer to use some other temp directory?

**Comment by curry684** [comment]
With my answer you don't need to run Composer in production, you can just upload `vendor` recursively from any dev/CI machine.

To override the temp dir see [this answer](http://php.net/manual/en/function.sys-get-temp-dir.php#118001).
