### ISSUE TITLE
Empty objects and array validation

### ISSUE THREAD

**Issue by theofidry** [justinrainbow/json-schema#513]
If you have the following JSON file:

```json
{
    "foo": []
}
```

With the following validation schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "name": "Package",
    "type": "object",
    "additionalProperties": false,
    "properties": {
                "foo": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
        }
    }
}

```

Will fail, because `[]` is not an object. While this might look alright, I think in this peculiar case no validation error should be thrown. Indeed JSON encoding/decoding is a bit tricky in PHP:

https://3v4l.org/IBpIH

It may be a bug in PHP as it seems to change if you don't include the `JSON_PRETTY_PRINT` flag, but I think this library should account for it still.

**Comment by erayd** [comment]
An array is not an object - throwing an error here is the correct behaviour.

While there might be a bug in PHP's JSON implementation under those particular circumstances, that's not a good reason for this library to assume objects and arrays are the same thing. Doing so would violate both the spec and users' expectations in a bad way.

There are already type casting / coercion options available in this library if you would like this kind of sloppiness with the typing - it would be better to use those. If any further modification is necessary, that would be the place to put it.

**Comment by erayd** [comment]
After looking into that behaviour further, there's not a bug, and PHP's JSON handling is working correctly. The reason you're seeing this problem is because you're using it wrong.

The second argument to `json_decode` is not a bitmask, it's a boolean, and controls whether JSON objects should be decoded to associative arrays. It defaults to false. `JSON_PRETTY_PRINT` is not a valid argument to use there. However, because it's a nonzero integer, it's equivalent to `true`, and therefore results in the object decoding to an array.

**Comment by theofidry** [comment]
Indeed, thanks!

**Comment by theofidry** [comment]
I'm actually a bit too hasty. I think my point is still valid. Consider the following:

```json
{
    "foo": [],
    "bar": {}
}
```

With the following validation schema:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "name": "Package",
    "type": "object",
    "additionalProperties": false,
    "properties": {
                "foo": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "bar": {
                    "type": "arrray",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
        }
    }
}

```

Now regardless of how you decode/encode that file, you will always end up with an invalid JSON file.

**Comment by erayd** [comment]
Why is this a problem? The data you've provided there is invalid against that schema, so an error is the expected outcome.

Also, your schema is invalid - there's an extra 'r' in 'arrray' for the `bar` definition.

**Comment by theofidry** [comment]
It's a problem because the first JSON file is valid, but if you decode + encode it again it will not be valid anymore

**Comment by theofidry** [comment]
I appreciate that an object and an array are not the same thing, but also this is PHP: it does not have a proper data structure management so when you have an empty array, you cannot know if that array is a list or a hashmap.

I'll give you a more concrete example: with a certain config, simply decoding + encoding the `composer.json` file will make Composer unable to dump the autoloader due to an invalid schema. I personally really don't feel that it is right.

**Comment by erayd** [comment]
What you're describing is a problem with PHP, which can only occur under specific circumstances. Why should this library violate both the spec and user expectations, when there is already logic in place to deal with potential type mismatches?

Or are you saying that you have enabled type coercion / casting, and that feature is not working? If so, please provide a code example which replicates the issue.

**Comment by erayd** [comment]
> It's a problem because the first JSON file is valid, but if you decode + encode it again it will not be valid anymore.

This is incorrect - the output is identical. See below:

```PHP
$json = '{"foo":[],"bar":{}}';
echo(json_encode(json_decode($json)));
```

**Comment by theofidry** [comment]
Ah indeed, if `assoc` is not forced out then `{}` will be `stdClass`, I had it set to `true` where I expected set to `false`.

I'll have to change quite a lot of code due to that but at least there is way to make it work without requiring any patching here. Thanks for the help!

**Comment by erayd** [comment]
Yup :-). Generally you want to avoid forcing decoding objects to associative arrays unless you have a very specific use-case.

If you have done this for a reason and would like to avoid the need to change large amounts of your code which expects an associative array, recursively casting stdclass to array after validation may be an easier option for you.
