### ISSUE TITLE
Const & enum deep comparison is not strictly typed

### ISSUE THREAD

**Issue by erayd** [justinrainbow/json-schema#517]
The `const` implementation from #507, and the existing `enum` implementation, [does not properly compare objects](https://github.com/justinrainbow/json-schema/pull/507#discussion_r182204595). Objects are compared in a loosely-typed manner (`==`), which also results in a loosely-typed comparison of all members.

This behavior is incorrect, and results in spec violations. For example, `"string" == true` returns true, despite being clearly invalid - both the type and content are completely different.

**Comment by shmax** [comment]
Would you like me to take a crack at this? I feel like you need some video game time...

**Comment by erayd** [comment]
Please! I'm flat out right now...

**Comment by shmax** [comment]
Righto, then. I have some time on Sunday.
