### ISSUE TITLE
i ran 'composer require justinrainbow/json-schema' command in ubuntu - nothing happened

### ISSUE THREAD

**Issue by ghost** [justinrainbow/json-schema#519]
i ran the command nothing happened except composer.json got updated. 
how  to install this library?

**Comment by erayd** [comment]
Please see the documentation [here](https://getcomposer.org/doc/01-basic-usage.md).

**Comment by DannyvdSluijs** [comment]
@erayd here is another issue that can be closed as the report is now from a ghost user (deleted profile).
