### ISSUE TITLE
JSON Hyper-Schema

### ISSUE THREAD

**Issue by sneakingJ** [justinrainbow/json-schema#522]
Is it possible to validate against a Hyperschema document?

**Comment by erayd** [comment]
This project does not implement hyper-schema sorry, just validation.

**Comment by alobeejay** [comment]
Well it would be just validation but against a JSON Hyperschema document. There would be multiple links (endpoints) in it.

**Comment by DannyvdSluijs** [comment]
@sneakingJ in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.
