### ISSUE TITLE
Custom coercion to types.

### ISSUE THREAD

**Issue by adjenks** [justinrainbow/json-schema#524]
I believe you should be able to enable more elaborate coercion of data types.
For example, coercing 'on' to true, or 'off' to false.
This could be implemented via a custom callback.
Just swap out functions like TypeConstrain->toBoolean() with optional custom callbacks.
For example:
```
$v = new \JsonSchema\Validator();
$v->setBooleanCoercion(function ($value)
    {
        if ($value === 'true' || $value === 'on') {
            return true;
        }

        if ($value === 'false' || $value === 'off') {
            return false;
        }

        return $value;
    }
});
```

**Comment by shmax** [comment]
PRs welcome.

**Comment by DannyvdSluijs** [comment]
@adjenks in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, and no effort was made to create a PR? Feel free to close it yourself with some comments if helpful.
