### ISSUE TITLE
internal://provided-schema/ should be ignored by URI retriever

### ISSUE THREAD

**Issue by estahn** [justinrainbow/json-schema#538]
```Message was: "file_get_contents(internal://provided-schema/definitions.schema.json): failed to open stream: No such file or directory```

**Comment by ricardofiorani** [comment]
I'm having the exact same problem on a lib that depends on this one.

**Comment by ricardofiorani** [comment]
Ok, I explained how I solved it in here -> https://github.com/PaddleHQ/openapi-validator/issues/6
I hope it helps anyone to either solve this issue on their projects or someone to create a bugfix for this

**Comment by DannyvdSluijs** [comment]
@estahn in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which was provided with some answer and can be closed? Feel free to close it yourself with some comments if helpful.
