### ISSUE TITLE
Extendable format constraints?

### ISSUE THREAD

**Issue by vicary** [justinrainbow/json-schema#539]
I am currently hitting the l10n area in `tel` format, we want to extend the validation from a US-only REGEXP to multiple countries base on the country code provided.

Is there a way we can plug a specific format without disabling everything with `Constraint::CHECK_MODE_DISABLE_FORMAT`?

**Comment by DannyvdSluijs** [comment]
@vicary in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.

**Comment by vicary** [comment]
@DannyvdSluijs thanks for replying, we had since moved on to other solutions such as zod and joi.

Wish JSON Schema a bright future and hopefully we may use it again some day.
