### ISSUE TITLE
Mime type for schema issues

### ISSUE THREAD

**Issue by dylanneild** [justinrainbow/json-schema#540]
Having a minor issue with validation against a Schema that's being served off of GitHub (using the raw URL retrieve):

```Fatal error: Uncaught JsonSchema\Exception\InvalidSchemaMediaTypeException: Media type application/schema+json expected in /Users/dylan/GitHub/swimguide-web/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php:73
Stack trace:
#0 /Users/dylan/GitHub/swimguide-web/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php(190): JsonSchema\Uri\UriRetriever->confirmMediaType(Object(JsonSchema\Uri\Retrievers\FileGetContents), 'https://raw.git...')
#1 /Users/dylan/GitHub/swimguide-web/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php(162): JsonSchema\Uri\UriRetriever->loadSchema('https://raw.git...')
#2 /Users/dylan/GitHub/swimguide-web/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(52): JsonSchema\Uri\UriRetriever->retrieve('https://raw.git...')
#3 /Users/dylan/GitHub/swimguide-web/vendor/justinrainbow/json-schema/src/JsonSchema/SchemaStorage.php(115): JsonSchema\SchemaStorage->addSchema('https://raw.git...')
#4 /Users/dylan/GitHub/swimguide-web/vendor/justinrainb in /Users/dylan/GitHub/swimguide-web/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriRetriever.php on line 73
```

Basically, it looks like UriRetriever.php is demanding that the mime type of the schema document is `application/schema+json`.  GitHub spits out `text/plain`.

Any flag or option possible to make UrlValidator ignore this and simply validate the schema syntactically?

**Comment by estahn** [comment]
@simplepanda This should be available in master now.

**Comment by simplepanda** [comment]
@estahn Thanks. I'm seeing `UriRetriever->addInvalidContentTypeEndpoint($endPoint)` and the associated data structures but by default the invalid content type array only lists json-schema.org.

What's the best practice for adding a URL to this list other than editing the module directly? I can't see where to get access to the `UriRetriever` instance from my validator. I can see `getUriRetriever()` in the `Factory` class, but `BaseConstraint->factory` is a protected variable and there is no `BaseConstruct->getFactory()` - so getting access to the factory via my validator seems like it's not the intended practice here?

```
Fatal error: Uncaught Error: Cannot access protected property JsonSchema\Validator::$factory in /Users/dylan/GitHub/swimguide-web/resources/classes/RecML.php:85
```

**Comment by erayd** [comment]
@simplepanda Create a factory first, and then create a validator which uses it.

**Comment by simplepanda** [comment]
All good. Tx.

**Comment by DannyvdSluijs** [comment]
@dylanneild in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.

Also this seem related to what I've been addressing in #709 where the HTTPS redirect returns a `Content-Type` header which is matched first instead of the last `Content-Type: application/schema+json`

**Comment by dylanneild** [comment]
@DannyvdSluijs - The project I had using this code has been EOL'd for a while so I'm not sure what the current state of this is in terms of workarounds/production. If you feel it's closable, it can be closed.
