### ISSUE TITLE
SchemaStorage::getSchema() should not add schema

### ISSUE THREAD

**Issue by estahn** [justinrainbow/json-schema#542]
The method `SchemaStorage::getSchema` is currently not just getting a schema, but adding if missing.

```php
    public function getSchema($id)
    {
        if (!array_key_exists($id, $this->schemas)) {
            $this->addSchema($id);
        }

        return $this->schemas[$id];
    }
```

Based on the documentation of the interface this is wrong:
```
Returns schema for given identifier, or null if it does not exist
```

**Comment by erayd** [comment]
@estahn The behavior is correct. The `addSchema` step is used to load remote schemas when they are first needed. Note that 'doesn't exist' is not the same thing as 'not currently loaded'.

The documentation could definitely use some clarification :-).

**Comment by estahn** [comment]
@erayd Fair enough.
