### ISSUE TITLE
how can i filter data

### ISSUE THREAD

**Issue by jediliang** [justinrainbow/json-schema#550]
for examle 
json data:
```
{
"name":"jedi", 
"addr":"xxxxxxxx", 
"phone":"1122330"
}
```
json-schema data: 
``` 
{
    "type": "object",
    "properties": {
        "name": {
            "type":"string",
        },
        "addr": {
            "type":"string"
        }
    },
    "required": ["name","addr"]
}
```

after validate the data , i want to get  the data  
```
{
"name":"jedi", 
"addr":"xxxxxxxx"
}
```

**Comment by erayd** [comment]
@jediliang You can't. This library is a JSON-Schema validator; JSON-schema doesn't define any kind of filtering mechanism.

**Comment by jediliang** [comment]
thanks for your  reply! 
 I was wondering just like https://github.com/epoberezkin/ajv#filtering-data , if  we can add a new mode or option just like Constraint::CHECK_MODE_APPLY_DEFAULTS can do this . anything thanks a lot

**Comment by erayd** [comment]
@jediliang I would prefer that such a feature *not* be added to this library. It's out of scope, and while ajv does it, it's very definitely not a JSON-schema thing. 

We're also very short on manpower here, so that's another reason to avoid bloating the codebase with extraneous features.

**Comment by jediliang** [comment]
@erayd ok, thanks very much for your reply!
