### ISSUE TITLE
How to include the library in code

### ISSUE THREAD

**Issue by ghost** [justinrainbow/json-schema#554]
I have installed the library with composer, when i run my code, i'm getting error - "Fatal error: Class 'JsonSchema\Validator' not found in".

How to include the library in my php file.
My file location is - /var/www/html/
json-schema library - /var/www/html/jsonvalidator

**Comment by shmax** [comment]
Questions:

1. Did you install via composer.json?
2. If yes, do you see the library in your `vendors` folder? 
3. What does your code look like?
4. What does the "include_path" property look like when you run `phpinfo()`?

**Comment by rumanpasha** [comment]
1. i installed it as - composer require justinrainbow/json-schema
2. yes i can see the library in vendors folder
3. my code is just an empty php file, where im testing this library before using in actual code.
4. include_path => .:/usr/share/pear => .:/usr/share/pear

**Comment by shmax** [comment]
Really need to see your code. Did you remember to require the autloader? Something like:

```
require_once 'vendor/autoload.php';
```

**Comment by DannyvdSluijs** [comment]
@erayd  here is another issue that can be closed as the report is now from a ghost user (deleted profile).
