### ISSUE TITLE
Is it possible to validate only schema?

### ISSUE THREAD

**Issue by lulco** [justinrainbow/json-schema#556]
I just want to check if the schema I wrote is correct (before I send some data to validation). Thanks

**Comment by erayd** [comment]
Yes - you can do this by validating it as a document against the meta-schema.

**Comment by lulco** [comment]
Do you mean something like:

```
$validator->validate($schema, json_decode('{"$ref": "http://json-schema.org/draft-04/schema"}'));
```

I tried this and it seems it works, but my users can use any version of schema. How to validate schema against list of meta-schemas?

**Comment by erayd** [comment]
@lulco Yes, that's what I mean.

Ideally your users will declare `$schema`, and you will know which meta-schema to use. However, if you wish to validate against multiple, then you can either do so in a loop, or use `anyOf`.

Note that this library currently only supports draft-03 and see draft-04. You cannot currently use newer versions of the spec.

**Comment by lulco** [comment]
Is it planned to add other drafts (up to 07)?

**Comment by erayd** [comment]
@lulco Contributions are welcome. We have almost no manpower on this project, and a 6.0 release to get out the door before we even consider it.

If someone pays me to work on it, then it'll happen a lot faster. Otherwise, it's basically down to when I have the free time for it, which I don't have much of lately.

**Comment by lulco** [comment]
I understand, thank you. I am a newbie in json schema, so for now I don't feel to make contribution to this library. But I hope it will change soon.
