### ISSUE TITLE
Constraint#checkUndefined() method is very expensive

### ISSUE THREAD

**Issue by Tatsh** [justinrainbow/json-schema#56]
Currently running this in a batch mode in a loop and with profiling it looks like `#checkUndefined()` (in `Constraints/Constraint.php`) is the method that most time is spent in.

Is there any possibility of speeding this up? For now, with this batch operation, I will have to use alternative ways of validating.

![kcachegrind](https://f.cloud.github.com/assets/724848/830398/1b872c40-f14d-11e2-9b75-1d49ace59fc7.png)

**Comment by SereneAnt** [comment]
There is a huge space for performance improvement.
For example see this - https://github.com/justinrainbow/json-schema/pull/331
But looks like it's not possible without major changes, e.g breaking Constraint methods signatures.
