### ISSUE TITLE
Array validation is failing for single object-item: Undefined offset: 1 (2,3,...)

### ISSUE THREAD

**Issue by optimalisatie** [justinrainbow/json-schema#560]
Hi!

Thanks a lot for the great solution! We are using json-validator for many projects and it has performed very well!

Regrettably, we currently experience a PHP Notice error issue when validating a JSON schema with 
 type `array` and a single `object` as item.

```php
Undefined offset: 1
```

The following code causes the issue:

https://github.com/justinrainbow/json-schema/blob/3921012b92bdda17ec9b5a9f62cd25b2d0591b70/src/JsonSchema/Constraints/CollectionConstraint.php#L120-L126

When validating an array with more than 5 items, the error is not present. It only occurs for small arrays.

The JSON schema's that are being used are:

1. https://style.tools/json-schemas/conditions.json
2. https://style.tools/json-schemas/critical-conditions.json

The PHP code used is:

```php
// critical-conditions.json
$schema = (object)$this->get('https://style.tools/json-schemas/critical-conditions.json');

// load references
$schemaStorage = new \JsonSchema\SchemaStorage();
$schemaStorage->addSchema('conditions.json', (object)$this->get('https://style.tools/json-schemas/conditions.json'));

// load validator
$schema_validator = new \JsonSchema\Validator(new \JsonSchema\Constraints\Factory($schemaStorage));

// validate configuration
$schema_validator->validate(
        $json,
        (object)$schema,
       0x00000002 // fuzzy type assoc array vs object
    );

// notice error
// ...

// invalid, handle error
if (!$schema_validator->isValid()) {

    // error message
    $this->errors = $schema_validator->getErrors();

    return false;
}

return true;
```

**Comment by erayd** [comment]
@optimalisatie Thanks for reporting this. Could you please post a minimal test case that illustrates the problem?

I notice you are attempting to cast a schema to an object using `(object)` - you can't do this, because it isn't possible to cast recursively. You must provide an actual object as the schema.

**Comment by optimalisatie** [comment]
Thank you for the quick reply!

You were correct, when changing the json_decode $assoc flag the issue is resolved. My apologies for reporting the issue.

This issue can be closed.
