### ISSUE TITLE
Array value found, but an object is required for empty object "{}"

### ISSUE THREAD

**Issue by dharmavir** [justinrainbow/json-schema#562]
With following json schema,
```
{
  "title": "foo.bar",
  "id": "/",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "foo": {
      "id": "foo",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bar": {
            "id": "bar",
            "type": ["object"],
            "additionalProperties": false,
            "properties": {
                "attr1": {
                  "id": "attr1",
                  "type": ["boolean","null"]
                },
                "attr2": {
                  "id": "attr2",
                  "type": ["boolean","null"]
                }
            }
        }
      }
    }
  }
}
```
If user sends following:
```
{
  "foo": {
    "bar": {}
  }
}
```
It gives "foo.bar; Array value found, but an object is required"

Would it not be easier if it could accept empty ```"bar": {} ``` and ignore it because it doesn't have any mandatory attributes?

**Comment by erayd** [comment]
This is probably user error - the library handles this just fine, in both the 5.2.8 release and in 6.0.0-dev (master branch).

Working example using the schema and data you provided above:
```PHP
<?php
$schema = json_decode(<<<'eot'
{
  "title": "foo.bar",
  "id": "/",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "foo": {
      "id": "foo",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "bar": {
            "id": "bar",
            "type": ["object"],
            "additionalProperties": false,
            "properties": {
                "attr1": {
                  "id": "attr1",
                  "type": ["boolean","null"]
                },
                "attr2": {
                  "id": "attr2",
                  "type": ["boolean","null"]
                }
            }
        }
      }
    }
  }
}
eot
);

$data = json_decode(<<<'eot'
{
  "foo": {
    "bar": {}
  }
}
eot
);

require 'vendor/autoload.php';

$v = new \JsonSchema\Validator();
$v->validate($data, $schema);
var_dump($v->isValid()); //true
```

How are you providing the input data? Based on your description, it sounds like you might be attempting to decode the JSON as an array, and then passing it as a shallow-cast object (i.e. using `(object)` to cast, which isn't recursive and therefore any child arrays will be left as arrays).

If you're stuck with having to pass it an array, then you may wish to investigate the type coercion feature, which is intended to help work around such restrictions in input data.

**Comment by erayd** [comment]
> Would it not be easier if it could accept empty `"bar": {}` and ignore it because it doesn't have any mandatory attributes?

To clarify this point - if your schema for the property `bar` says `"type": "object"`, then `"bar": []` violates that, even though it's empty, because it's an array. However, `"bar": {}` is compliant, and will pass validation successfully.

Note that even an empty object may have constraints applied to it (such as type, minimum number of properties etc.), even though there may not be any mandatory properties defined. Empty objects cannot be ignored just because they are empty.

**Comment by dharmavir** [comment]
Thanks guys for quick response, it was my mistake. I was using laravel and in the middleware was using ```json_decode(json_encode($request->all()))``` instead of ```json_decode($request->getContent()``` (God knows why, it was stupid thing to do) which created all the problem.

Thanks again!

**Comment by dharmavir** [comment]
Closing issue.

**Comment by dharmavir** [comment]
> Thanks guys for quick response, it was my mistake. I was using laravel and in the middleware was using `json_decode(json_encode($request->all()))` instead of `json_decode($request->getContent()` (God knows why, it was stupid thing to do) which created all the problem.
> 
> Thanks again!

initially wrote it >2 years back and was revisiting it today.!
