### ISSUE TITLE
how to generate schema

### ISSUE THREAD

**Issue by A07110517** [justinrainbow/json-schema#568]
How to base data generate json schema？Is there a ready-made tool?

**Comment by A07110517** [comment]
i found it
https://www.jsonschema.net/

**Comment by erayd** [comment]
@A07110517 Note that the tool you have linked generates schemas for a newer version of the spec than this library supports. The newest version with full support is currently draft-04.

Many aspects of newer spec schemas will still work, but you should not rely on full compliance with the spec, and you are likely to run across things that don't behave as expected.

**Comment by A07110517** [comment]
> @A07110517 Note that the tool you have linked generates schemas for a newer version of the spec than this library supports. The newest version with full support is currently draft-04.
> 
> Many aspects of newer spec schemas will still work, but you should not rely on full compliance with the spec, and you are likely to run across things that don't behave as expected.

@erayd I got it, thank you
