### ISSUE TITLE
Format `date-time` rejects negative timezone offsets incorrectly

### ISSUE THREAD

**Issue by duckbrain** [justinrainbow/json-schema#572]
[RFC-3339](https://tools.ietf.org/html/rfc3339#section-5.6) allows a `+` or `-` for the timezone offset, but this library rejects `2500-01-01T03:02:00-7:00` as a valid `date-time`.

**Comment by shmax** [comment]
Please post a minimal (but complete) snippet so we'll have a better idea of what you're talking about.

**Comment by duckbrain** [comment]
I'm sorry, it was my mistake. I was missing the preceding zero on my timezone offset. I just so happened to have the two digits when I tested with a positive. I was trying to reproduce it with a unit test on the project until I found the difference.

```diff
- `2500-01-01T03:02:00-7:00`
+ `2500-01-01T03:02:00-07:00`
```

**Comment by shmax** [comment]
Awesome, glad it worked out.
