### ISSUE TITLE
The validate-json binary autoload deprecation warning in PHP 7.2+

### ISSUE THREAD

**Issue by CupOfTea696** [justinrainbow/json-schema#574]
When running the validate-json command in cli using PHP 7.2 or later, the following deprecation warning shows:

```
PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in
~/.composer/vendor/justinrainbow/json-schema/bin/validate-json on line 16
```

**Comment by SignpostMarv** [comment]
was this fixed already by #401 & 9fe7822f76f1ff798d6c1593af54af98d0c59e9e ?

**Comment by erayd** [comment]
@SignpostMarv Yep, we haven't used `__autoload` for two years now. However, that change only applies to v6, which doesn't yet have a production release (although it's reasonable stable for most uses).

The current production branch (5.x.x) still uses the old code. I'm not sure why I haven't backported that change - possibly because the bug it was fixing didn't apply to 5.x.x either - but let's keep this issue open, and I'll deal with it for the next backport release.

**Comment by erayd** [comment]
Resolved by @sanmai in #589.

**Comment by sanmai** [comment]
It appears Packagist integration got outdated, can you have a look? I recall this is just a matter of a push of a button.

[E.g. the newest version isn't available there yet.](https://packagist.org/packages/justinrainbow/json-schema)

**Comment by erayd** [comment]
@bighappyface Could you look at the packagist integration please?

**Comment by bighappyface** [comment]
I don’t have access, unfortunately.

**Comment by erayd** [comment]
@bighappyface No I.

Do you still have a useful line of communication with @justinrainbow, and do you think he would be OK settings more admins on this repo (or moving it into an org)? This kind of bus factor is incredibly frustrating.

**Comment by SignpostMarv** [comment]
I've noticed this happening on my own packages recently; On github under `repo settings > webhooks  packagist` there's a log of recent messages, with an option to resend.

**Comment by SignpostMarv** [comment]
@erayd ah, my bad- thought it was just about admin access to packagist.

**Comment by erayd** [comment]
@SignpostMarv It might be that _as well_, if the hook hasn't been updated since Packagist deprecated their old one in January. I'm not sure on that count.

**Comment by SignpostMarv** [comment]
@erayd the master branch commit ref seems to be up-to-date on packagist, but the issue might be that master, 5.x.x & 6.0.0-dev all have the same branch alias configured.

**Comment by erayd** [comment]
@SignpostMarv Can you clarify? While 6.0.0-dev is the same as master, 5.x.x is a completely independent branch, which diverged from master quite some time ago.

**Comment by SignpostMarv** [comment]
@erayd clarification on what I'd misread from the commits;

dev-master is the only one with a branch alias, so I don't know if that'd trip up w/ packagist.

might suggest adjusting the branch aliases on master & 5.x.x in case that's what's stripping up packagist?

**Comment by erayd** [comment]
@justinrainbow ^

**Comment by SignpostMarv** [comment]
i.e. https://github.com/justinrainbow/json-schema/blob/5.x.x/composer.json#L39 should probably be different to https://github.com/justinrainbow/json-schema/blob/master/composer.json#L41

**Comment by erayd** [comment]
Ooh, good catch. Sorry, I thought you were talking about something on the packagist site. It's been a while since I've looked at that file in any detail.

That particular setup isn't valid for *either* branch, so we definitely need to correct that!
