### ISSUE TITLE
Request for information

### ISSUE THREAD

**Issue by thawkins** [justinrainbow/json-schema#580]
This is a request for pointers on how i can use the validator to create a fake data generator. 

I am looking for a way to create a list of all of the possible pointer values for a schema, with thier type and description properties, for arrays i would need to create a fake pointer element of "[item]", as a placeholder for an index. 

Using this information and the faker library, i can build a utilty that can generate bulk fake data directly from a json-schema file.  I would use annotations in the description to further refine the data types generated by faker. 

If anybody has any ideas on how to extract this information from the validator, i would be gretefull, otherwise i am going to have to generste my own schema parser, something im not looking forward to.

**Comment by erayd** [comment]
You'll have to write your own parser for this I'm afraid - we parse the schema in an on-demand manner as required to match the data being validated, so the information you're wanting doesn't actually exist within the validator at all.

Note that schemas may be recursive, so if you do try to write something that can do this, you'll need to be careful you don't run it into an infinite loop. This also means that it's impossible to generate a fully comprehensive set of dummy data for such a schema, as a fully comprehensive data set would be infinite in size. However, you may well be able to generate a more limited set of data that still fulfills whatever need you have for this.
