### ISSUE TITLE
running this script on a linux machine

### ISSUE THREAD

**Issue by michapixel** [justinrainbow/json-schema#59]
i ran into problems.
i have however successfully run this on my local testmachine (win).
so this has obviously sth to do with wrong schema paths.
Here's my code:
`private function validateFeedItems($feeditems, $schema) {
        $retriever = new JsonSchema\Uri\UriRetriever;
        $schema = dirname(__FILE__).'/' . ($schema);
        $schema = $retriever->retrieve($schema);
        $refResolver = new JsonSchema\RefResolver($retriever);
        $refResolver->resolve($schema, __DIR__);
        $validator = new JsonSchema\Validator();
        $validator->check($feeditems, $schema);
        return $validator;
}`
And this produces the following error:

PHP Fatal error:  Uncaught exception 'JsonSchema\Exception\UriResolverException' with message 'Unable to resolve URI '/is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/schemata/json-calendar.schema' from base ''' in /is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/JsonSchema/Uri/UriResolver.php:110\nStack trace:\n#0 /is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/JsonSchema/Uri/UriResolver.php(89): JsonSchema\Uri\UriResolver::combineRelativePathWithBasePath('/is/htdocs/wp10...', '')\n#1 /is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/JsonSchema/Uri/UriRetriever.php(115): JsonSchema\Uri\UriResolver-]resolve('/is/htdocs/wp10...', NULL)\n#2 /is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/wp_feedcollector.php(86): JsonSchema\Uri\UriRetriever-]retrieve('/is/htdocs/wp10...')\n#3 /is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/wp_feedcollector.php(145): wp_feedcollector-]validateFeedItems(Object(stdClass), 'schemata/json-c...')\n#4 [internal function]: wp_feedcollector-]pushToFeedlist(Object(stdClass), Array, 0)\n#5 /is/htdocs/wp10606769_ZYB0S33ES7/ in /is/htdocs/wp10606769_ZYB0S33ES7/JSON_Feed/inc/JsonSchema/Uri/UriResolver.php on line 110

any clues/hints much appreciated.

**Comment by reod** [comment]
@michapixel, any chances that you resolved this issue and you remember the answer? ;) Two years later I have the same problem as you had (I'm not using WP but Cake PHP).
