### ISSUE TITLE
5.2.9 is not available on Packagist

### ISSUE THREAD

**Issue by localheinz** [justinrainbow/json-schema#592]
The latest tag is currently [`5.2.9`](https://github.com/justinrainbow/json-schema/tree/5.2.9).

However, when taking a look at [Packagist](https://packagist.org/packages/justinrainbow/json-schema), then you will notice that the latest tag is [`5.2.8`](https://github.com/justinrainbow/json-schema/tree/5.2.8).

Perhaps the synchronization isn't properly set up?

**Comment by erayd** [comment]
@localheinz We are already aware of this, but thanks :-). It's already been flagged in #574 - need someone with admin access to give it a kick, add that's just one guy.

@justinrainbow Please sort this out - the bus factor here is *extremely* annoying!

**Comment by bighappyface** [comment]
5.2.9 is available on packagist - https://packagist.org/packages/justinrainbow/json-schema#5.2.9
