### ISSUE TITLE
Conditional validations

### ISSUE THREAD

**Issue by GinoPane** [justinrainbow/json-schema#610]
Hi!

Shouldn't this support conditional validations as per schema draft-07? 

I'm trying to use something like

      "if": {
        "properties": {
          "varName": {
            "enum": ["A", "B"]
          }
        }
      },
      "then": {
        "required": ["newColumn"]
      }

But this does not seem to work. The validations still passes even if `newColumn` is missing for valid condition.

**Comment by erayd** [comment]
The newest version of the standard supported by this library is draft-04 - that is why your conditionals are not working, as they simply weren't a thing at that point. If you have time to work on draft-07 support, PRs would be welcome - this project is *extremely* short on manpower.
