### ISSUE TITLE
Deprecated warning message on composer install command

### ISSUE THREAD

**Issue by peter279k** [justinrainbow/json-schema#613]
When using the `composer install` command on this repository folder, it will present following warning message:

```
Deprecation warning: require-dev.json-schema/JSON-Schema-Test-Suite is invalid, it should not contain uppercase characters. Please use json-schema/json-schema-test-suite instead. Make sure you fix this as Composer 2.0 will error.
```

It seems that the `json-schema/JSON-Schema-Test-Suite` package name should be changed with lower-case.

**Comment by erayd** [comment]
It should. Please feel free to open a PR that makes this change.

**Comment by Ayesh** [comment]
I came across the same notice :) I also opened a PR #626 to backport it to 5.x.x. Thank you.
