### ISSUE TITLE
Specify supported JSON Schema version

### ISSUE THREAD

**Issue by janlucaklees** [justinrainbow/json-schema#617]
I would love to see the actual JSON Schema version that is supported by the library somewhere in the readme. Sure I can go look in the tests and infer that only Draft-4 of the JSON Schema is supported, but you need to be very desperate to do that.

Context: I spent a whole lot of time figuring out why 'contains' is not working for an array. Not sure, but maybe with `Constraint::CHECK_MODE_VALIDATE_SCHEMA` set, it should warn you about properties in your JSON Schema that are not supported.

I would be open to "implement" those changes myself and open a PR for them to be merged.

**Comment by erayd** [comment]
Good suggestion. A PR for this would be appreciated :-).

**Comment by yannickroger** [comment]
@erayd @janlucaklees I think we can close that one 😉

**Comment by janlucaklees** [comment]
@yannickroger Yess, thank you for reminding me!
