### ISSUE TITLE
Deprecated warnings with PHP 8

### ISSUE THREAD

**Issue by matbech** [justinrainbow/json-schema#618]
Deprecated: Required parameter $path follows optional parameter $schema in justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php on line 62
PHP Deprecated:  Required parameter $path follows optional parameter $schema in justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php on line 108

**Comment by erayd** [comment]
Thanks - please feel free to submit a PR fixing this.

**Comment by erayd** [comment]
Fixed by @matbech in #619.
