### ISSUE TITLE
Change Language for errors message

### ISSUE THREAD

**Issue by FuriosoJack** [justinrainbow/json-schema#623]
It would be awesome to be able to set a message translation file or the ConstraintError class can be overwritten to change the messages

**Comment by erayd** [comment]
@FuriosoJack You are welcome to open a PR that implements this. Note it's a low priority though.

**Comment by shmax** [comment]
I don't think there's anything stopping you from doing this already. Each error payload has a meaningful identifier that you can use to map to your own localized strings. Something like this:

```php
foreach(  $validator->getErrors() as $error ) {
    $msgId = "msg_json_schema_error_{$error['constraint']";
    // insert your favorite localization technology here
    echo $i18n->loc($msgId, $error['params'];
}
```

**Comment by DannyvdSluijs** [comment]
@FuriosoJack in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.
