### ISSUE TITLE
get property when validate path or header -  justinrainbow-json-schema

### ISSUE THREAD

**Issue by tomzdon** [justinrainbow/json-schema#627]
I would like to get a property when validating a path or header (GET method - REST API). My application was written in laravel 6 version.

My part json-schematic about parameters
"Parameters": [
{
"In": "header",
"Name": "customer ID",
"Required": true,
"Type": "string"
},
{
"In": "path",
"Name": "product_id",
"Required": true,
"Type": "string",
"MaxLength": 24
}
]
When I send GET, where product_identifier has 25 words, I get errors, but without properties

0 => array: 6 [
"Property" => ""
"Pointer" => ""
"Message" => "Must be up to 24 characters"
"Constraint" => "maxLength"
"Context" => 1
"MaxLength" => 24
]

How can I get property?

**Comment by erayd** [comment]
Can you please provide an example JSON schema and document to reproduce using this library only. I'd like to see what the library is being expected to take as input.

**Comment by DannyvdSluijs** [comment]
@tomzdon it seems like you mixed (parts of) OpenApiSpec/Swagger with json-schema. This library is used for validating a JSON document it doesnt help out with request parameters such as path or headers.
In an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.
