### ISSUE TITLE
Not finding branch dev-master 

### ISSUE THREAD

**Issue by seiberdrache10** [justinrainbow/json-schema#628]
I am trying to setup OAuth authentication for Wordpress. After downloading the client-cli by:
$ git clone https://github.com/WP-API/client-cli

I execute:
$ cd client-cli
$ composer install

My composer.json looks like this:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/63503008/79044670-abab4e00-7c06-11ea-9afd-ffb4c52f62d8.png">

And my terminal outputs the following:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/63503008/79044694-c8478600-7c06-11ea-9241-3e356b25fdc2.png">

The problem seems to be that I don't find the dev-master branch. I can replace dev-master by an existing branch like 5.2.9 in my composer.json, but the package wp-api/client requires the master branch, as of my understanding. 

I also tried adding "@dev" to "dev-master" in the requirements, but that did not change anything. 

I am kinda new to this topic, forgive me if I overlook something obvious.

**Comment by ktomk** [comment]
@seiberdrache10 this is likely more an issue using composer. were you able to figure it out so far or do you still need some pointers?

**Comment by DannyvdSluijs** [comment]
@seiberdrache10 in an attempt to cleanup this repo we are trying to filter the issues and see which ones might be closed. Is it safe to assume this is a rather old issue, which sadly was left unanswered, and can be closed? Feel free to close it yourself with some comments if helpful.
