### ISSUE TITLE
PHP 8 Deprecation Notices using composer

### ISSUE THREAD

**Issue by williamdes** [justinrainbow/json-schema#633]
https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/692060394#L211

```
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///home/travis/.phpenv/versions/master/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///home/travis/.phpenv/versions/master/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///home/travis/.phpenv/versions/master/bin/composer/src/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///home/travis/.phpenv/versions/master/bin/composer/src/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///home/travis/.phpenv/versions/master/bin/composer/src/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///home/travis/.phpenv/versions/master/bin/composer/src/Composer/Repository/RepositoryManager.php:130
```

**Comment by erayd** [comment]
@Seldaek FYI - I think we need to sort this one too.

I recall somebody doing a PR for that recently, but not certain it was on this project - will have a hunt for it, and if not then I'll fix it tomorrow and backport to 5.x.x.

**Comment by Seldaek** [comment]
I think it's fixed already. It's just not in Composer 1.10.6. Snapshot builds should run without warnings now but that's 2.0 so might cause other problems for you ;)

I'll try and release a 1.10.7 soonish. Keeping this open until then.

**Comment by Seldaek** [comment]
Oh this isn't on Composer repo I see, never mind the last comment :D The rest remains valid.

**Comment by erayd** [comment]
Confirming that this has already been fixed in master and was part of the backport for v5.2.10.

**Comment by williamdes** [comment]
Thank you !
https://github.com/justinrainbow/json-schema/releases/tag/5.2.10

**Comment by Seldaek** [comment]
1.10.7 is out, should fix all php 8 warnings
