### ISSUE TITLE
Accept Sponsorship

### ISSUE THREAD

**Issue by adjenks** [justinrainbow/json-schema#639]
You have 48 **million** downloads on packagist.org
469 **known** projects depend on this.
It's time to take donations so that you can better support the community:

https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/receiving-sponsorships-through-github-sponsors

**Comment by erayd** [comment]
Can you clarify what you are intending here? If somebody wants to pay me to work on this, I'm happy to set it up accordingly, but nobody has expressed a desire for this to date. Are *you* wanting to pay for development work on this project?

**Comment by shmax** [comment]
I'm assuming this is some kind of bot doing its thing.

**Comment by adjenks** [comment]
I would be happy to tip the developers a modest amount for their work and I think that others may also be inclined to do so considering how many projects depend on it. So, I think this project should provide a means of accepting donations / sponsorship.

**Comment by adjenks** [comment]
Haha, a bot. Yeah I sounded pretty scripted didn't I?

**Comment by shmax** [comment]
Well, color me surprised. 48 million downloads, eh?

**Comment by erayd** [comment]
@adjenks Please correct me if I'm wrong - but the impression I'm getting here is that you are suggesting in a more general sense that we attempt to fundraise, and you are willing to chip in a few dollars.

I see a few problems with that:

1. I don't have the time or inclination to run a fundraising campaign.
2. Simply existing in a state capable of receiving donations seems unlikely to generate much.
3. Very few people care enough to help out with coding on this project; it seems likely even fewer would pay something.
4. If it only generates a few dollars, it's not worth the tax & accounting headaches at my end.
5. I'm not going to turn down good, paying clients for the sake of a few dollars here either.
6. I have very little available time to work on this, which means if I'm going to do more here, I *must* turn clients away.

If you have a proposal that is likely to pay a decent rate for my time, then I'm happy to consider this project / whoever is paying as a client like any other, and manage my workload accordingly. If not, then I'm not particularly interested, and will keep maintaining this as and when I have available free time to do so (which tends to be very limited).

@shmax What are your thoughts on this?

**Comment by shmax** [comment]
> What are your thoughts on this?

Gosh, I don't know. I'm retired from this project at this point (I've moved on to graphql), so I think any embarrassment of riches will be yours to bear. Philosophically, the idea of trying to solicit money out of people for open source seems like a bizarre turn to me, but what do I know? Now, if you can convince each of the 49 million downloaders to donate a buck I may start singing a different tune, but that's why github comments have an edit button.

**Comment by erayd** [comment]
Mmm, given that resounding endorsement, I think I'll close this issue without action then. Can always two of en it if someone provides a compelling reason to change my mind 🙂.

**Comment by adjenks** [comment]
Okay, no problem for me, I basically just wanted to buy you guys a couple "beers". Lots of developers (and other creators of sorts) these days have a Patreon account, or something like that, so I find it pretty normal for people to accept money for creating open source software. I mean, people who work on open source stuff are donating to the community, so I don't think it's too much of a stretch to think that someone may want to give back if they appreciate something that was built. In many cases, depending on the platform being used, there is no contract or expectation of further work, but a creator might feel encouraged to do so.

Anyhow, I wish you both all the best, thanks for doing what you do, and good luck on your future projects.

**Comment by shmax** [comment]
Well, when you put it that way it sounds a bit less objectionable. I don't know about @erayd, but I'll have to confess that the contributions I make to OSS projects are not always pure of heart--I'm generally fixing some bug or adding a feature or optimization to enable or benefit my own diabolical use of them. I guess I could see fishing some change out of the fountain every now and then if we had a documentation site with hosting to pay for or something, but I don't think we have any kind of overhead on this project. At any rate, thanks for your kind consideration. I appreciate the virtual beer, but I'll tell you what: plant me a [few trees](https://onetreeplanted.org/) and we'll call it square.

**Comment by adjenks** [comment]
@shmax Nice idea. Here are your [trees](https://str.rise-ai.com/claim/greeting?cart_id=7ea4dd07b1774553b40fbafcb20069e8).

**Comment by shmax** [comment]
Wonderful, thank you!
