### ISSUE TITLE
Unexpected performance issues

### ISSUE THREAD

**Issue by unguul** [justinrainbow/json-schema#640]
I'm experiencing some performance issues and I can't tell where the problem is. XDebug profiling does not show anything unusual. However, neither the schema or the data are extreme in terms of complexity or amount of data so I'm kind of stuck. Maybe a fresh pair of eyes can help.

Validating the below data(on php 7.4 with json-schema 5.2.10) takes 6s+ and adding subsequent layers to the data exponentially increases that time to over 2 minutes if the data is 5 layers deep.

### Schema

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "things": {
      "type": "array",
      "items": {
        "oneOf": [
          { "$ref": "#/definitions/foo" },
          { "$ref": "#/definitions/fooH" },
          { "$ref": "#/definitions/fooF" },
          { "$ref": "#/definitions/fooLS" },
          { "$ref": "#/definitions/fooRS" },
          { "$ref": "#/definitions/bar" },
          { "$ref": "#/definitions/fooBar" },
          { "$ref": "#/definitions/fooBarFoo" },
          { "$ref": "#/definitions/fooBarFooBar" }
        ]
      }
    },

    "thingParent": {
      "type": "object",
      "required": [
        "type",
        "things"
      ],
      "properties": {
        "type": { "type": "string" },
        "note": { "type": "string" },
        "fooProperties": {
          "type": "object",
          "required": [
            "fooProperty1",
            "fooProperty2",
            "fooProperty3"
          ],
          "properties": {
            "fooProperty1": { "type": "integer" },
            "fooProperty2": { "type": "integer" },
            "fooProperty3": { "type": "integer" }
          }
        },
        "things": { "$ref": "#/definitions/things" }
      }
    },

    "foo": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "foo" ] }
          }
        }
      ]
    },
    "fooH": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "fooH" ] }
          }
        }
      ]
    },
    "fooF": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "fooF" ] }
          }
        }
      ]
    },
    "fooLS": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "fooLS" ] }
          }
        }
      ]
    },
    "fooRS": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "fooRS" ] }
          }
        }
      ]
    },
    "bar": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "bar" ] },
            "id": { "type": "string" }
          }
        }
      ]
    },
    "fooBar": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "fooBar" ] }
          }
        }
      ]
    },
    "fooBarFoo": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "properties": {
            "type": { "enum": [ "fooBarFoo" ] }
          }
        }
      ]
    },
    "fooBarFooBar": {
      "allOf": [
        { "$ref": "#/definitions/thingParent" },
        {
          "required": [
            "id"
          ],
          "properties": {
            "type": { "enum": [ "fooBarFooBar" ] },
            "id": { "type": "string" },
            "fooBarFooBarProperty": { "type": "integer" },
            "isNew": {
              "type": "boolean",
              "default": false
            }
          }
        }
      ]
    }
  },

  "type": "object",
  "required": [
    "metadata",
    "things"
  ],
  "properties": {
    "metadata": {
      "type": "object",
      "required": [
        "editorVersion"
      ],
      "properties": {
        "editorVersion": { "type": "string" }
      }
    },
    "things": { "$ref": "#/definitions/things" }
  }
}
```

### Data

```
{
  "metadata": {
    "editorVersion": "1.1.1"
  },
  "things": [
    {
      "type": "fooBarFooBar",
      "id": "someId",
      "note": "some notes",
      "things": [
        {
          "type": "foo",
          "fooBarFooBar": {
            "fooProperty1": 1,
            "fooProperty2": 2,
            "fooProperty3": 3
          },
          "things": [
            {
              "type": "bar",
              "things": []
            }
          ]
        },
        {
          "type": "foo",
          "fooBarFooBar": {
            "fooProperty1": 1,
            "fooProperty2": 2,
            "fooProperty3": 3
          },
          "things": [
            {
              "type": "bar",
              "note": "some notes",
              "things": []
            }
          ]
        }
      ]
    },
    {
      "type": "fooBarFooBar",
      "id": "some id",
      "fooBarFooBar": {
        "fooProperty1": 1,
        "fooProperty2": 2,
        "fooProperty3": 3
      },
      "things": [
        {
          "type": "bar",
          "things": []
        },
        {
          "type": "bar",
          "things": []
        },
        {
          "type": "bar",
          "things": [
            {
              "type": "fooBarFooBar",
              "id": "some identifier",
              "fooBarFooBarProperty": 4,
              "things": []
            },
            {
              "type": "fooBarFooBar",
              "id": "some other identifier",
              "fooBarFooBarProperty": 5,
              "things": []
            }
          ]
        }
      ]
    }
  ]
}
```

Thank you!!

**Comment by erayd** [comment]
Could you please advise what kind of system you are running this on? I have not yet been able to replicate that kind of extreme performance issue here (although the performance I'm seeing here certainly isn't stunning either).

**Comment by unguul** [comment]
@erayd Debian 9 VM running off an SSD with php 7.4.

**Comment by erayd** [comment]
@unguul I was asking about hardware, rather than software - I should have made that clear sorry. The time difference between our tests I think simply reflects that my system may have a better (or more lightly loaded) CPU than yours does.

Looking at your example in more detail, there's an issue with the way you have structured your schema, in that it will result in an extremely high number of constraint checks in order to satisfy all the possible combinations for that `oneOf` at every level. The example you have provided results in 28,571 checks - I have provided a breakdown of how many checks must be run against each data path in your example in order to properly validate it. Bear in mind that constraints must be checked to their full depth, and that `oneOf` will check ***every*** branch in order to ensure that there is exactly one positive match. This means that the number of checks will increase exponentially with data depth.

This library isn't exactly the most efficient thing on the planet, so all the small delays really add up - when you're running tens of thousands of checks, the total time required to complete validation can be quite a while!

```
2268 #/things/1/things/2/things/1
2268 #/things/1/things/2/things/0
2268 #/things/0/things/1/things/0
2268 #/things/0/things/0/things/0
1458 #/things/1/things/2/things/1/type
1458 #/things/1/things/2/things/0/type
1458 #/things/0/things/1/things/0/type
1458 #/things/0/things/0/things/0/type
 729 #/things/1/things/2/things/1/things
 729 #/things/1/things/2/things/1/note
 729 #/things/1/things/2/things/1/fooProperties
 729 #/things/1/things/2/things/0/things
 729 #/things/1/things/2/things/0/note
 729 #/things/1/things/2/things/0/fooProperties
 729 #/things/0/things/1/things/0/things
 729 #/things/0/things/1/things/0/note
 729 #/things/0/things/1/things/0/fooProperties
 729 #/things/0/things/0/things/0/things
 729 #/things/0/things/0/things/0/note
 729 #/things/0/things/0/things/0/fooProperties
 252 #/things/1/things/2
 252 #/things/1/things/1
 252 #/things/1/things/0
 252 #/things/0/things/1
 252 #/things/0/things/0
 162 #/things/1/things/2/type
 162 #/things/1/things/2/things/1/id
 162 #/things/1/things/2/things/0/id
 162 #/things/1/things/1/type
 162 #/things/1/things/0/type
 162 #/things/0/things/1/type
 162 #/things/0/things/1/things/0/id
 162 #/things/0/things/0/type
 162 #/things/0/things/0/things/0/id
  81 #/things/1/things/2/things/1/isNew
  81 #/things/1/things/2/things/1/fooBarFooBarProperty
  81 #/things/1/things/2/things/0/isNew
  81 #/things/1/things/2/things/0/fooBarFooBarProperty
  81 #/things/1/things/2/things
  81 #/things/1/things/2/note
  81 #/things/1/things/2/fooProperties
  81 #/things/1/things/1/things
  81 #/things/1/things/1/note
  81 #/things/1/things/1/fooProperties
  81 #/things/1/things/0/things
  81 #/things/1/things/0/note
  81 #/things/1/things/0/fooProperties
  81 #/things/0/things/1/things/0/isNew
  81 #/things/0/things/1/things/0/fooBarFooBarProperty
  81 #/things/0/things/1/things
  81 #/things/0/things/1/note
  81 #/things/0/things/1/fooProperties
  81 #/things/0/things/0/things/0/isNew
  81 #/things/0/things/0/things/0/fooBarFooBarProperty
  81 #/things/0/things/0/things
  81 #/things/0/things/0/note
  81 #/things/0/things/0/fooProperties
  28 #/things/1
  28 #/things/0
  18 #/things/1/type
  18 #/things/1/things/2/id
  18 #/things/1/things/1/id
  18 #/things/1/things/0/id
  18 #/things/0/type
  18 #/things/0/things/1/id
  18 #/things/0/things/0/id
   9 #/things/1/things/2/isNew
   9 #/things/1/things/2/fooBarFooBarProperty
   9 #/things/1/things/1/isNew
   9 #/things/1/things/1/fooBarFooBarProperty
   9 #/things/1/things/0/isNew
   9 #/things/1/things/0/fooBarFooBarProperty
   9 #/things/1/things
   9 #/things/1/note
   9 #/things/1/fooProperties
   9 #/things/0/things/1/isNew
   9 #/things/0/things/1/fooBarFooBarProperty
   9 #/things/0/things/0/isNew
   9 #/things/0/things/0/fooBarFooBarProperty
   9 #/things/0/things
   9 #/things/0/note
   9 #/things/0/fooProperties
   2 #/things/1/id
   2 #/things/0/id
   1 #/things/1/isNew
   1 #/things/1/fooBarFooBarProperty
   1 #/things/0/isNew
   1 #/things/0/fooBarFooBarProperty
   1 #/things
   1 #/metadata/editorVersion
   1 #/metadata
   1 #
```

**Comment by unguul** [comment]
@erayd I wasn't sure about your question either, thanks for clarifying.

The VM has 4 cores from [this i7](https://ark.intel.com/content/www/us/en/ark/products/191045/intel-core-i7-9750h-processor-12m-cache-up-to-4-50-ghz.html) so it should be enough to handle most things.

I noticed the high number of calls too, it's kind of the reason I opened this issue as I wasn't sure if it's my schema that's awkward to process or if this library does something weird when dealing with nested data.

Thanks for the breakdown of checks and accompanying explanation.

I also found [this old post on the subject of slow JSON schema validations](https://groups.google.com/g/json-schema/c/ZAfzrvmFV2s) linking to [this schema](https://gist.github.com/jimklo/5416348) which looks orders of magnitude more complex than what I have and their validation times are still lower than what I'm getting.

While looking at this I've also given https://github.com/swaggest/php-json-schema a try and I'm getting similar results so the schema is definitely not easy to deal with.

Do you have any recommendations for making the schema easier to process?

**Comment by erayd** [comment]
> I wasn't sure if it's my schema that's awkward to process or if this library does something weird when dealing with nested data.

It's the schema. This library does lazy expansion of references as needed to validate the data, so the expansion is limited to whatever your data requires. This library is slow though, which does make your problem worse than it would be using something like e.g. [AJV](https://ajv.js.org/) for validation. In particular, any compiling validator is likely to be considerably faster than this one. I don't believe there are any publicly available compiling validators for PHP at present.

I have written a closed-source compiling validator for PHP, fully compliant with draft-06, that I am trying to get released as open-source, but the licensing for that has been tied up in red tape for quite some time (multiple years), so don't expect anything on that front soon. It's much faster though, so when (if) that happens, it may help.

> ...which looks orders of magnitude more complex than what I have and their validation times are still lower than what I'm getting.

Unfortunately, *"looks complicated"* is not a reliable way of evaluating the number of execution steps. Of particular note is that your schema is recursive, and you have designed it in such a way that the number of checks will increase exponentially with the depth of data. That is not an issue with this library; you'll see the same behavior in any standards-compliant validator (obviously some will perform better than others, but they should all conduct the same checks).

> Do you have any recommendations for making the schema easier to process?

What is the actual scenario you are trying to address? The example is very generic.

The biggest issue here is the combination of recursion via many `oneOf` branches, combined with the data depth. If you can address any of those factors, you should see a significant performance improvement. That may or may not be an option for you, depending on your requirements - for some systems there simply is no other option if you wish to retain full validation.

If you cannot refactor the schema to cut down on the number of checks needed for compliance, consider implementing lazy validation. If you can get away with only validating part of your document, that will significantly cut down on the time required, even if all the other stuff stays the same.

**Comment by slavcodev** [comment]
@unguul you can try reorder the composition
~~~json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "things": {
      "type": "array",
      "items": {
        "allOf": [
          { "$ref": "#/definitions/thingParent" },
          {
            "oneOf": [
              { "$ref": "#/definitions/foo" },
              { "$ref": "#/definitions/fooH" },
              { "$ref": "#/definitions/fooF" },
              { "$ref": "#/definitions/fooLS" },
              { "$ref": "#/definitions/fooRS" },
              { "$ref": "#/definitions/bar" },
              { "$ref": "#/definitions/fooBar" },
              { "$ref": "#/definitions/fooBarFoo" },
              { "$ref": "#/definitions/fooBarFooBar" }
            ]
          }
        ]
      }
    },

    "thingParent": {
      "type": "object",
      "required": [
        "type",
        "things"
      ],
      "properties": {
        "type": { "type": "string" },
        "note": { "type": "string" },
        "fooProperties": {
          "type": "object",
          "required": [
            "fooProperty1",
            "fooProperty2",
            "fooProperty3"
          ],
          "properties": {
            "fooProperty1": { "type": "integer" },
            "fooProperty2": { "type": "integer" },
            "fooProperty3": { "type": "integer" }
          }
        },
        "things": { "$ref": "#/definitions/things" }
      }
    },

    "foo": {
      "properties": {
        "type": { "enum": [ "foo" ] }
      }
    },
    "fooH": {
      "properties": {
        "type": { "enum": [ "fooH" ] }
      }
    },
    "fooF": {
      "properties": {
        "type": { "enum": [ "fooF" ] }
      }
    },
    "fooLS": {
      "properties": {
        "type": { "enum": [ "fooLS" ] }
      }
    },
    "fooRS": {
      "properties": {
        "type": { "enum": [ "fooRS" ] }
      }
    },
    "bar": {
      "properties": {
        "type": { "enum": [ "bar" ] },
        "id": { "type": "string" }
      }
    },
    "fooBar": {
      "properties": {
        "type": { "enum": [ "fooBar" ] }
      }
    },
    "fooBarFoo": {
      "properties": {
        "type": { "enum": [ "fooBarFoo" ] }
      }
    },
    "fooBarFooBar": {
      "required": [
        "id"
      ],
      "properties": {
        "type": { "enum": [ "fooBarFooBar" ] },
        "id": { "type": "string" },
        "fooBarFooBarProperty": { "type": "integer" },
        "isNew": {
          "type": "boolean",
          "default": false
        }
      }
    }
  },

  "type": "object",
  "required": [
    "metadata",
    "things"
  ],
  "properties": {
    "metadata": {
      "type": "object",
      "required": [
        "editorVersion"
      ],
      "properties": {
        "editorVersion": { "type": "string" }
      }
    },
    "things": { "$ref": "#/definitions/things" }
  }
}
~~~
and this validator will work 10x faster

**Comment by unguul** [comment]
@erayd & @slavcodev Thank you both for the input. I can confirm that replacing the `oneOf` with `anyOf` and reordering the composition has a huge impact on performance. I'm curious on if/how this library could change to help with this kind of scenario.

**Comment by erayd** [comment]
> I'm curious on if/how this library could change to help with this kind of scenario.

There's not that much we can do to it, but it would probably be useful for someone to go over the constraint processing order and shuffle it around so the cheap rejections are at the top. Otherwise, it's more down to the schema writer to design something sane IMO.

Something else that would potentially improve performance a bit is by adding some result caching.
