### ISSUE TITLE
Conditions are supported?

### ISSUE THREAD

**Issue by ZhukV** [justinrainbow/json-schema#642]
Hi. I have a one question. In specification, I see what the spec supports [conditions](https://json-schema.org/understanding-json-schema/reference/conditionals.html). But Ii don't see implementation in library.

**Comment by erayd** [comment]
Conditionals are a new feature in the draft-07 spec. However, the newest version of the spec currently supported by this library is draft-04.

If you would like to submit a PR implementing draft-07 support, that would be very welcome.
