### ISSUE TITLE
JSON schema not found

### ISSUE THREAD

**Issue by TechOverflow** [justinrainbow/json-schema#643]
I have a problem with the JSON schema not found Exception:

`PHP Fatal error:  Uncaught JsonSchema\\Exception\\ResourceNotFoundException: JSON schema not found at file:// in ... JsonSchema\\Uri\\UriRetriever->loadSchema('file://') ...`

Is there any reason why the exception doesn't list the whole path to the file that's missing, or at least the file name? It's hard to debug which file JsonSchema is looking for.

**Comment by erayd** [comment]
How are you loading the file?

**Comment by erayd** [comment]
To clarify - it's not displaying a full file path, because the resolver wasn't given one - it was simply instructed to load `file://`. If you can explain how you're using it, that will help to determine whether it's user error, or whether we have a bug somewhere that's causing this.

**Comment by TechOverflow** [comment]
After some testing, it seems that the file path being given was null, therefore just `file://`. My bad.

**Comment by erayd** [comment]
That would explain it! Glad you got to the bottom of it 😁.
