### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by gilbert-rehling** [justinrainbow/json-schema#644]
After upgrading to PHP 7.4 this error is consistently reported, and prevents try catch code from running.

This library is being called by:
https://github.com/eloquent/composer-config-reader

I am using this library to read data from compser.json, and all was well untill the 7.4 update. Unfortunately PHP 7.4 is required by other applications on the server, so back tracking is not possible.

This is the reported error:
#message: "Array and string offset access syntax with curly braces is deprecated"
#code: 0
#file: "/var/hosting/sites/php-mongo-admin/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php"
#line: 112
#severity: E_DEPRECATED

In my case, I will create a temporary fix of the vendor source to fix problem.
I'm using eloquent/composer-config-reader in my project:
https://github.com/php-mongo/admin

Thank you..

**Comment by erayd** [comment]
Which version of this library are you using? That particular syntax issue was fixed years ago.

**Comment by gilbert-rehling** [comment]
> Which version of this library are you using? That particular syntax issue was fixed years ago.

As noted in my report, the library is being included by another library:
https://github.com/eloquent/composer-config-reader

They must be referencing an older version of your library. I have mention the issue at their github account.
"require": {
    "php": ">=5.3",
    "eloquent/enumeration": "^5",
    "justinrainbow/json-schema": "^4"
},

Alternatively I may just require your latest version directly and try that as a resolution.

Thanks for the prompt response!

**Comment by erayd** [comment]
Aah yes, that looks like they are requiring v4, which predates the fix 🙂.
