### ISSUE TITLE
Only the first item of the array is validated

### ISSUE THREAD

**Issue by rodrigoio** [justinrainbow/json-schema#648]
Using the json-schema bellow, only the first item of array is validated. There is any setup to force validate all the items from array?
 
```json
{
    "type": "object",
    "properties": {
        "data": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"}
                    },
                    "required": ["name"]
                }
            ]
        }
    },
    "required": ["data"]
}
```

This case is validated:
```
{"data":[{"other": "value"},{"name": "foo"}]}
```

But this case is not validated: 
```
{"data":[{"name": "foo"},{"other": "value"}]}
```

**Comment by erayd** [comment]
This isn't a bug - your schema is faulty. If `items` is an array, as it is in your example, then the restrictions in that array apply only to their corresponding data; e.g. `items[3]` applies only to `data[3]`.

If you define `items` as an object, then the restrictions apply to all items in the data array.

If you wish to combine the two, and apply different restrictions to data that does not have a matching schema in an array form of `items`, then use `additionalItems`.

**Comment by rodrigoio** [comment]
Wow, it makes perfect sense now. I was just setting the first item.
Thanks!
