### ISSUE TITLE
Bug: Unescaped slash throws error, when pattern contains slash

### ISSUE THREAD

**Issue by a-r-m-i-n** [justinrainbow/json-schema#649]
Here you don't escape slashes in expression: https://github.com/justinrainbow/json-schema/blob/fa4d2d3c1e40a222ded125b679891086c9a6c7d6/src/JsonSchema/Constraints/FormatConstraint.php#L200

Here you do: https://github.com/justinrainbow/json-schema/blob/fa4d2d3c1e40a222ded125b679891086c9a6c7d6/src/JsonSchema/Constraints/StringConstraint.php#L43

The first check should do the same here. 

Thanks for this great lib! And a happy new year! 🥳

**Comment by erayd** [comment]
Thanks for reporting this. A PR that fixes it would be very welcome 🙂.

**Comment by ktomk** [comment]
would you consider to file a PR on this? @a-r-m-i-n

**Comment by ktomk** [comment]
Just asking, as I may also pick a take on it. For that I would be also interested in the "throws error" details, specifically how to provoke an error and what message of that error mentioned is. /cc @a-r-m-i-n 

The `str_replace` looks fishy to me as `preg_match` is in use. Me thinks better of `preg_quote` for that.

**Comment by a-r-m-i-n** [comment]
Here we go. I just copied the preg_match from the second place. If you want to replace the used function, feel free. I think this will at least solve the issue I currently have, when I try to use Composer's JSON schema. The "name" property there, got a check pattern for "abc/def", including the unescaped / which is also used as delimiter before.

**Comment by erayd** [comment]
> The `str_replace` looks fishy to me as `preg_match` is in use. Me thinks better of `preg_quote` for that.

That method uses `preg_match` *to check whether `$regex` is a valid regular expression*, by attempting to compile it and checking for an error condition. It does not use a regular expression to validate a string. Using `preg_quote` would defeat the entire purpose of the `validateRegex` method.

**Comment by ktomk** [comment]
Thanks!
