### ISSUE TITLE
 [Question]: Is using with swagger-php possible

### ISSUE THREAD

**Issue by nikoladsp** [justinrainbow/json-schema#667]
Hi,
I would like to use Json-Schema in my PHP project, but also I am interested if it can (an how) be used with swagger-php to document API.

Thank you kindly

**Comment by infisamk** [comment]
OpenAPI is modified JSON Schema. And they cannot be transformed among themselves.

I could not find any documentation tool for JSON schemas. So I wrote my own tool to display documentation from JSON schemas. It's for internal use, so I can't publish it.

**Comment by nikoladsp** [comment]
Thank you, seems I will also have to do it manually.

Best regards
