### ISSUE TITLE
started getting error "nothing provides"

### ISSUE THREAD

**Issue by rferguson10** [justinrainbow/json-schema#671]
sudo yum install -y composer --enablerepo=remi

on centos 8 or 7

 Problem: cannot install the best candidate for the job
  - nothing provides (php-composer(justinrainbow/json-schema) >= 5.2.11 with php-composer(justinrainbow/json-schema) < 6) needed by composer-2.1.4-1.el8.remi.noarch

**Comment by Seldaek** [comment]
cc @remicollet - I guess justinrainbow/json-schema 5.2.11 wasn't built yet, but composer/composer 2.1.4 (which requires it) was built already somehow?

**Comment by remicollet** [comment]
justinrainbow/json-schema 5.2.11 is build but only in "remi"

Should be fixed now (also pushed in "remi-safe")

**Comment by remicollet** [comment]
> sudo yum install -y composer --enablerepo=remi

Hmm.. with "remi" enabled should have work... perhaps unsync mirror, try "--refresh" or outdated metadata

**Comment by remicollet** [comment]
```
# dnf update
====================================================================================================================================================================================
 Paquet                                                   Architecture                     Version                                     Dépôt                                  Taille
====================================================================================================================================================================================
Mise à jour:
 composer                                                 noarch                           2.1.4-1.el8.remi                            remi-modular                           494 k
 php-justinrainbow-json-schema5                           noarch                           5.2.11-1.el8.remi                           remi                                    45 k

```

(sorry, in French)

**Comment by remicollet** [comment]
@rferguson10 better to report such issue (related to packaging) to proper place, i.e. https://github.com/remicollet/remirepo/issues

This one can be closed.
