### ISSUE TITLE
Question about Dependency (json-schema/json-schema-test-suite)

### ISSUE THREAD

**Issue by summea** [justinrainbow/json-schema#676]
I was looking through a recent `composer.lock` file after adding a dev dependency that includes `justinrainbow/json-schema` and noticed that there was a `require-dev` entry listed as: `"json-schema/json-schema-test-suite": "1.2.0"`.

When I checked packagist.org to see what this package was about, I landed on the following page after searching for `json-schema/json-schema-test-suite`:
https://packagist.org/packages/json-schema/json-schema-test-suite

This package doesn't look like it has very many installs and has a lot of "test" related meta information.

Am I looking in the wrong place for information about the dev dependency of `json-schema/json-schema-test-suite`?

If so, where can I find information about the actual dependency used by `justinrainbow/json-schema`?

**Comment by erayd** [comment]
This library does not depend on the package you have linked to. The entry in `composer.json` does not refer to it, although Packagist seems to be a little confused, as it lists this library as a dependent.

The dependency actually refers to [this](https://github.com/json-schema/JSON-Schema-Test-Suite) test suite, which is used to validate this library's validation logic against the official JSON schema specification. The test suite is not available via packagist, and is therefore defined in `composer.json` as a direct repository reference.

<img width="583" alt="Screen Shot 2021-10-12 at 13 24 04" src="https://user-images.githubusercontent.com/121486/136870419-2ac024cf-ace8-4f2a-8bb9-1584ac274451.png">
