### ISSUE TITLE
Show line numbers

### ISSUE THREAD

**Issue by abitrolly** [justinrainbow/json-schema#680]
Does this lib allows to show the line number in original file where the validation fails? I don't see it is possible from examples.

The problem originally appeared here - https://github.com/composer/composer/issues/10380#issuecomment-999477032

**Comment by erayd** [comment]
No. This library provides an error path, but not a line number.

**Comment by DannyvdSluijs** [comment]
@abitrolly adding errors can be found [here](https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/BaseConstraint.php#L47) in code. 
As you can see an error is an array containing named keys such as `pointer` and `property` which seem to be good candidates to checkout. Probably best to start with the `property` one as that seems to call a function called `convertJsonPointerIntoPropertyPath`

If this answers your questions (or maybe we are too late in answering them) would you  close the issue in an attempt te revive the project and get a better overview of what still is pending?
