### ISSUE TITLE
oneOf, and anyOf annotation example

### ISSUE THREAD

**Issue by lewiscowleschipuk** [justinrainbow/json-schema#684]
Hello 👋 

Looking at the code, I can see some of the `of` validated; but not oneOf or anyOf, just allOf.

Is this a gap in testing, or documentation, or a hint that annotating action endpoints of controllers is not advised?

Thanks for authoring and hope you're having a great day.

**Comment by lewiscowleschipuk** [comment]
😊 I think I was using this incorrectly maybe, or expecting to be able to use in `Response` annotation. Here is a usage I can see in our codebase for property.

```
     *                  @OA\Property(
     *                      property="payment_method",
     *                      type="string",
     *                      description="Payment method: card, apple-pay, google-pay.",
     *                      oneOf={
     *                         @OA\Schema(example="card"),
     *                         @OA\Schema(example="google-pay"),
     *                         @OA\Schema(example="apple-pay"),
     *                      }
     *                  ),
```

This is an example of how the library is being used where I work. I could not find an example of this usage. Instead of the JSON examples given in the repo, I was looking specifically at the annotation, method of building the JSON. It was non-obvious to me how I would build a `Response` using `oneOf`. When I tried in the same way as this, it failed.

**Comment by erayd** [comment]
I still have no idea what you are talking about sorry. The code examples you've provided also are neither JSON nor PHP. Finally, this library has no class named `Response`, and has nothing to do with annotations.

This library is used to validate data against a JSON schema. That is its sole purpose. Are you sure you have filed this issue against the correct project?

If you are sure this is the right place, can you please provide the simplest possible description of your problem, and a minimal PHP or JSON code example that reproduces it.
