### ISSUE TITLE
not validating nested array with Symfony phpunit, or prop names

### ISSUE THREAD

**Issue by BernardA** [justinrainbow/json-schema#696]
Using in the context of a Symfony/API-Platform app, with phpunit to validate the response from the API.

Current justinrainbow/json-schema: "version": "5.2.12",

The JSON returned by the API looks like this:

       {
           "count": 1,
            "results": [
                   {
                         "code": "0081279X38",
                         "companyName: "a company name",
                         "id": "1"
                   }
           ]
      }

This is the schema array I am validating against:

       $schema = [
            "properties" =>(object) [
                "count" => [
                    "type" => "integer",
                ],
                "results" =>(object) [
                    "type" => "array",
                    "properties" => (object) [
                        "code" => [
                            "type" => "string"
                        ],
                        "companyName" => [
                            "type" => "string"
                        ],
                        "id" => [
                            "type" => "string"
                        ]
                    ]
                ]
            ]
        ]

And this is the code for the test:

        $client = self::createClient();
        $client->request('GET', '/api/my_request',[
            'headers' => [
                'Accept' => 'application/json',
            ]
        ]);

        $this->assertResponseStatusCodeSame(200);

        $this->assertMatchesJsonSchema($schema);

I will get an error if I change the type of the property `count` to `string`. So that's fine.

I will NOT get error if I change the type of any of the properties within `result`.

I will NOT get error if I change the name of any property. For instance, if I change `count` to `counted` it will still pass the test.

The expected outcome is that it throws  validation error for any mismatch on the property name and any type mismatch.

Currently it does not validate at all the property name nor does it validates the type on the nested array `result`.

**Comment by erayd** [comment]
This is a problem with your schema, not a bug. JSON arrays do not have named properties (they are simply an ordered list of items), so the `properties` keyword in your schema is simply being ignored, as the spec says it should be. According to the spec, your data should (and does) pass validation.

Yiou need to modify your schema to validate the actual array items (via [`items` or `additionalItems`](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-01#section-6.9)). In this case, what you probably want is to define a single schema for `items` that declares every array item should be of type `object`, with the `properties` constraints from your original schema above.

**Comment by erayd** [comment]
Oh, and regarding this:

> The expected outcome is that it throws validation error for any mismatch on the property name...

You need to make those properties compulsory via [`required`](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-01#section-6.17), and then set [`additionalProperties`](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-01#section-6.20) to `false`. This will constrain the object to contain all of those properties, with those names, and throw errors if a property with another name is present.

**Comment by BernardA** [comment]
For the record, this is what worked for me:

Thanks for pointing me on the right direction.

       $schema =  [
            "type" => "object",
            "properties" => (object) [
                "count" => [
                    "type" => "integer",
                ],
                "results" =>(object) [
                    "type" => "array",
                    "items" => (object) [
                        "type" => "object",
                        "properties" => [
                            "code" => [
                                "type" => "string"
                            ],
                            "companyName" => [
                                "type" => "string"
                            ],
                            "id" => [
                                "type" => "string"
                            ]
                        ],
                        "additionalProperties" => false
                    ]
                ]
            ],
            "additionalProperties" => false
        ];
