### ISSUE TITLE
Why do we support higher version json-schema?

### ISSUE THREAD

**Issue by hzb1115** [justinrainbow/json-schema#699]
As we all know, Json-schema has been upgraded to draft-06 draft-07.... But why do we only support draft-4?  
And I want to know if we can support a higher version Json-schema.

**Comment by erayd** [comment]
The master branch supports almost all of draft-06.

> But why do we only support draft-4?

Because nobody on this project has the time to implement it. It's basically on life support.

**Comment by DannyvdSluijs** [comment]
@hzb1115 in an effort to clean up this repo and see if we can move forward if the above answer your question, could you close the issue?

**Comment by erayd** [comment]
@DannyvdSluijs Given the time elapsed since I answered this, with no further reply, I'm happy to unilaterally close it.
