### ISSUE TITLE
Version number format changed in 5.2.13

### ISSUE THREAD

**Issue by shadowhand** [justinrainbow/json-schema#703]
When upgrading a project's packages, I noticed that:

```
- Upgrading justinrainbow/json-schema (5.2.12 => v5.2.13): Extracting archive
```

Why did this release suddenly get a `v` prefix when no others have?

**Comment by erayd** [comment]
It's accidental - I forgot that this repo doesn't follow the usual convention of a leading `v` when I tagged the release.

Feel free to ignore it; it'll be back to normal with the next release. If it's causing you problems, let me know, and I'll roll an identical 5.2.14 without the leading `v`.
