### ISSUE TITLE
Mixing properties and patternProperties fails for properties not matching the patternProperties definition

### ISSUE THREAD

**Issue by fabian-mcfly** [justinrainbow/json-schema#705]
### Schema (incomplete, just the important part):
```json
"link": {
  {
    "type": "object",
    "properties": {
      "controller": {
        "type": "string",
        "pattern": "^[A-Z][a-zA-Z0-9]+$"
      },
      "action": {
        "type": "string",
        "pattern": "^[a-z][a-z0-9-]+$"
      }
    },
    "patternProperties": {
      "^[a-z][a-z0-9-]+$": {"pattern": "^[a-z0-9-]+$"}
    },
    "required": ["controller", "action"],
    "additionalProperties": false
  }
}
```

### Data:
```json
"link": {
  "controller": "Dashboard",
  "action": "overview",
  "param1": 123,
  "param2": "foobar"
}
```

Validating this data will result in an error:
`Violations: [link.controller] Does not match the regex pattern ^[a-z0-9-]+$ `
Maybe I am the problem here, but I understand the "patternProperties" to only require validation for properties that aren't explicitly defined.
Since "controller" already is set, no validation with the regex pattern in `patternProperties` should occur.

I already found a fix, but I'd like to wait with a PR until someone can tell me whether this is, indeed, a bug or just my misunderstanding of how `properties` & `patternProperties` work.

**Comment by erayd** [comment]
This isn't a bug; it's how the spec says it should behave 🙂

> Maybe I am the problem here, but I understand the "patternProperties" to only require validation for properties that aren't explicitly defined.

Your understanding is incorrect. According to the spec, `patternProperties` applies to all matching properties, and does not exclude those which also match a `properties` rule. The two keywords operate entirely independently of each other.

The [relevant spec wording](https://json-schema.org/draft-06/draft-wright-json-schema-validation-01#rfc.section.6.19) is:
> ## 6.19 patternProperties
> The value of "patternProperties" MUST be an object. Each property name of this object SHOULD be a valid regular expression, according to the ECMA 262 regular expression dialect. Each property value of this object MUST be a valid JSON Schema.
>
> This keyword determines how child instances validate for objects, and does not directly validate the immediate instance itself. Validation of the primitive instance type against this keyword always succeeds.
>
> *Validation succeeds if, for each instance name that matches any regular expressions that appear as a property name in this keyword's value, the child instance for that name successfully validates against each schema that corresponds to a matching regular expression.*
>
>Omitting this keyword has the same behavior as an empty object.

A contrasting example is `additionalProperties`, which *does* contain such an exclusion:
> Validation with "additionalProperties" applies only to the child values of instance names that do not match any names in "properties", and do not match any regular expression in "patternProperties".

**Comment by erayd** [comment]
If you are *wanting* `patternProperties` to apply only to properties which do not pass validation against `properties`, the spec-compliant way to do this is with `oneOf`. For example:

```json
{
    "type": "object",
    "oneOf": [
        {
            "properties": {...},
            "additionalProperties": false
        {,
        {
            "patternProperties": {...}
        }
    ]
}
```

Note that `additionalProperties` is necessary in order to ensure that non-matching property names fail validation on the `properties` branch of the `oneOf` constraint.

**Comment by fabian-mcfly** [comment]
Thanks for the quick reply and clarification. It seems like PHPStorm's implementation is wrong.

Sadly, I cannot make this work using anyOf like this results - it results in errors as well:

```json
"title": {
  "type": "object",
  "anyOf": [
    {
      "properties": {
        "controller": {
          "type": "string",
          "pattern": "^[A-Z][a-zA-Z0-9]+$"
        },
        "action": {
          "type": "string",
          "pattern": "^[a-z][a-z0-9-]+$"
        }
      },
      "additionalProperties": false
    },
    {
      "patternProperties": {
        "^[a-z][a-z0-9-]+$": {"pattern": "^[a-z0-9-]+$"}
      }
    }
  ]
}
```

```
[link] The property param1 is not defined and the definition does not allow additional properties 
[link] The property param2 is not defined and the definition does not allow additional properties 
[link.controller] Does not match the regex pattern ^[a-z0-9-]+$
[link] Failed to match at least one schema
```

I was able to make it work using a negative lookahead in the patternProperties:
`^((?!^(controller|action)))[a-z][a-z0-9-]+$`

Thanks again and sorry for any inconvenience.
