### ISSUE TITLE
Latest version named `v5.2.13` introduced issues in other soft that use versionning comparaison 

### ISSUE THREAD

**Issue by llaville** [justinrainbow/json-schema#708]
Hello,

I would like to notice you that latest version `v5.2.13` published with prefix `v` have introduced issues in other soft that use versionning comparaison (with https://github.com/composer/semver)

```php
<?php
use Composer\Semver\Comparator;

$source = '5.2.12';
$target = 'v5.2.13';

$currentCompare = Comparator::greaterThan($source, $target);
$bool = $currentCompare ? 'true' : 'false';
var_dump("$source > $target = $bool");
```

That gave wrong expected comparaison: `string(23) "5.2.12 > v5.2.13 = true"`

While with workaround 

```php
<?php
use Composer\Semver\Comparator;
use Composer\Semver\VersionParser;

$source = '5.2.12';
$target = 'v5.2.13';

$parser = new VersionParser();

$normalizedSource = $parser->normalize($source);
$normalizedTarget = $parser->normalize($target);

$normalizedCompare = Comparator::greaterThan($normalizedSource, $normalizedTarget);
$bool = $normalizedCompare ? 'true' : 'false';
var_dump("$source > $target = $bool");
```
Gave good expected comparaison : `string(24) "5.2.12 > v5.2.13 = false"`

**Comment by Seldaek** [comment]
There are other problems with non-normalized versions than v prefixes. Normalization is a must IMO and composer always normalizes internally.

**Comment by llaville** [comment]
@Seldaek Thanks, but FYI I've already proposed a PR (https://github.com/JBZoo/Composer-Diff/pull/31/files) for the package that run in trouble in current context !

**Comment by erayd** [comment]
I've updated the release tag to 5.2.13. Is this sufficient to resolve your issue, or do you need another release?

**Comment by llaville** [comment]
By opening this ticket, I just want to keep you aware that version naming change may occurs some issue in other packages, that's all !

**Comment by llaville** [comment]
As I've already proposed a patch to fix at least the package I've found recently, I will close this issue

**Comment by erayd** [comment]
OK, thanks. If there are any issues persisting after retagging the release as 5.2.13, let me know, and I'll roll an identical release as 5.2.14.

The 'v' prefix on the original tag was a mistake; it shouldn't have been there.
