### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Opis\Uri\Uri' not found

### ISSUE THREAD

**Issue by vijayjshinde6** [justinrainbow/json-schema#713]
@soyuka 
Fatal error: Uncaught Error: Class 'Opis\Uri\Uri' not found

**Comment by DannyvdSluijs** [comment]
@vijayjshinde6 thanks for your report. But I’m m afraid this isn’t very actionable. If you can share reproduction steps en which version of JSON-schema you’re using we can take a look. 

Also noticeable is that you’re referring to Opis which is a different library.

**Comment by vijayjshinde6** [comment]
Sorry,
Looks like i was checking with some different library..
It's not related with this one.
