### ISSUE TITLE
Not proper "oneOf" handling

### ISSUE THREAD

**Issue by antonCPU** [justinrainbow/json-schema#76]
```json
{
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "test1": {
                    "type": "string"
                }
            },
            "required": ["key", "test1"]
        },
        {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "test2": {
                    "type": "string"
                }
            },
            "required": ["key", "test2"]
        }
    ]
}
```

This schema will pass for:
```json
{
     "test2" : "ok"
}
```
Because of **array_unique()** usage in `JsonSchema\Constraints\Constraint::getErrors()`.
When the second schema will be checked a list of errors will contain "key" and "test1" errors. During checking will be added another error with "key" required, but **array_unique()** will erase it, so this schema will pass a criteria in `JsonSchema\Constraints\Underfined::validateOfProperties()` as a result.

**Comment by jojo1981** [comment]
Tested this issue with version: 2.0.0 and it works like supposed.

    
    [
        {
            "property": "key",
            "message": "The property key is required",
            "constraint": "required"
        },
        {
            "property": "test1",
            "message": "The property test1 is required",
            "constraint": "required"
        },
        {
            "property": "",
            "message": "Failed to match exactly one schema",
            "constraint": "oneOf"
        }
    ]
    
@bighappyface I think this one can also be closed?

**Comment by bighappyface** [comment]
@jojo1981 thanks!
