### ISSUE TITLE
"$ref" not implemented in object/properties

### ISSUE THREAD

**Issue by cweiske** [justinrainbow/json-schema#80]
A reference within object properties does currently not work:

```
"type": "object",
"properties": {
    "$ref": "base.json#/definitions/typedString/properties"
}
```

Related to #77 and #13.

**Comment by bighappyface** [comment]
Closed with https://github.com/justinrainbow/json-schema/pull/174

**Comment by cweiske** [comment]
I don't think that this is fixed by updating phpunit.

**Comment by bighappyface** [comment]
@cweiske good catch! Copy/paste FTW
